package parquet

import (
	"bytes"
	"fmt"
	"hash/crc32"
	"os"
	"strings"
	"testing"

	gp "github.com/parquet-go/parquet-go"
)

// The reader trusts nothing it can verify (ADR-0018 §11): a page that carries
// a checksum is held to it before any value comes out of it.
//
// These cells exist because it did not. A parquet-go-written uncompressed
// PLAIN INT64 page with one payload bit flipped read [42, 43] as [43, 43]
// with a nil error, while parquet-go refused the identical bytes (#891). The
// checksum was in the file, decoded into PageHeader.CRC, and consulted by
// nothing.

// crcPage is one page's position inside a file, as a walk of the footer's
// chunk offsets and the page headers finds it.
type crcPage struct {
	column   string
	kind     PageType
	headerAt int // file offset of the page header
	bodyAt   int // file offset of the page body
	bodyLen  int
	crc      uint32
	crcSet   bool
}

// walkPages enumerates every page of every column chunk in a file.
func walkPages(tb testing.TB, data []byte) []crcPage {
	tb.Helper()
	md, err := ReadFileMetaData(bytes.NewReader(data), int64(len(data)))
	if err != nil {
		tb.Fatalf("footer: %v", err)
	}
	var out []crcPage
	for rgi := range md.RowGroups {
		rg := &md.RowGroups[rgi]
		for ci := range rg.Columns {
			cm := rg.Columns[ci].MetaData
			if cm == nil {
				continue
			}
			start := cm.DataPageOffset
			if cm.DictionaryPageOffset > 0 && cm.DictionaryPageOffset < start {
				start = cm.DictionaryPageOffset
			}
			end := start + cm.TotalCompressedSize
			for off := int(start); off < int(end); {
				ph, n, err := DecodePageHeader(data[off:])
				if err != nil {
					tb.Fatalf("page header at %d: %v", off, err)
				}
				out = append(out, crcPage{
					column:   strings.Join(cm.PathInSchema, "."),
					kind:     ph.Type,
					headerAt: off,
					bodyAt:   off + n,
					bodyLen:  int(ph.CompressedPageSize),
					crc:      uint32(ph.CRC),
					crcSet:   ph.CRCSet,
				})
				off += n + int(ph.CompressedPageSize)
			}
		}
	}
	return out
}

// checksummedFixture is one file the CRC cells run over, with the values it
// must read back when nothing is mutated.
type checksummedFixture struct {
	name string
	data []byte
}

// parquetGoFile writes a two-column file with parquet-go, which emits a page
// checksum for every page it writes.
func parquetGoFile(tb testing.TB, pageVersion int, codec gp.WriterOption, dict bool, n int) []byte {
	tb.Helper()
	type plainRec struct {
		X int64  `parquet:"x,plain"`
		S string `parquet:"s,plain"`
	}
	type dictRec struct {
		X int64  `parquet:"x,plain"`
		S string `parquet:"s,dict"`
	}
	var b bytes.Buffer
	opts := []gp.WriterOption{gp.DataPageVersion(pageVersion), gp.PageBufferSize(1024), codec}
	if dict {
		w := gp.NewGenericWriter[dictRec](&b, opts...)
		rows := make([]dictRec, n)
		for i := range rows {
			rows[i] = dictRec{int64(i), fmt.Sprintf("v%d", i%13)}
		}
		if _, err := w.Write(rows); err != nil {
			tb.Fatal(err)
		}
		if err := w.Close(); err != nil {
			tb.Fatal(err)
		}
	} else {
		w := gp.NewGenericWriter[plainRec](&b, opts...)
		rows := make([]plainRec, n)
		for i := range rows {
			rows[i] = plainRec{int64(i), fmt.Sprintf("v%d", i)}
		}
		if _, err := w.Write(rows); err != nil {
			tb.Fatal(err)
		}
		if err := w.Close(); err != nil {
			tb.Fatal(err)
		}
	}
	return b.Bytes()
}

// checksummedFixtures is the corpus: two INDEPENDENT writers (parquet-go and
// PyArrow), both page-format versions, compressed and uncompressed, with and
// without a dictionary page.
func checksummedFixtures(tb testing.TB) []checksummedFixture {
	tb.Helper()
	out := []checksummedFixture{
		{"parquet-go/v1/uncompressed/plain", parquetGoFile(tb, 1, gp.Compression(&gp.Uncompressed), false, 300)},
		{"parquet-go/v1/uncompressed/dict", parquetGoFile(tb, 1, gp.Compression(&gp.Uncompressed), true, 300)},
		{"parquet-go/v1/snappy/dict", parquetGoFile(tb, 1, gp.Compression(&gp.Snappy), true, 300)},
		{"parquet-go/v1/zstd/plain", parquetGoFile(tb, 1, gp.Compression(&gp.Zstd), false, 300)},
		{"parquet-go/v2/uncompressed/plain", parquetGoFile(tb, 2, gp.Compression(&gp.Uncompressed), false, 300)},
		{"parquet-go/v2/snappy/dict", parquetGoFile(tb, 2, gp.Compression(&gp.Snappy), true, 300)},
		{"parquet-go/v2/zstd/plain", parquetGoFile(tb, 2, gp.Compression(&gp.Zstd), false, 300)},
	}
	for _, f := range []string{"testdata/page_crc.parquet", "testdata/page_crc_v2.parquet"} {
		data, err := os.ReadFile(f)
		if err != nil {
			tb.Fatalf("reading %s (regenerate with testdata/gen_page_crc.py): %v", f, err)
		}
		out = append(out, checksummedFixture{"pyarrow/" + f, data})
	}
	return out
}

// TestEveryChecksumFixtureActuallyCarriesChecksums keeps the bit-flip cells
// from going vacuous. A fixture regenerated by a writer that stopped emitting
// checksums would still "refuse" nothing, and every cell below would pass by
// never having a checksum to check.
func TestEveryChecksumFixtureActuallyCarriesChecksums(t *testing.T) {
	for _, fx := range checksummedFixtures(t) {
		t.Run(fx.name, func(t *testing.T) {
			pages := walkPages(t, fx.data)
			if len(pages) == 0 {
				t.Fatal("no pages")
			}
			for _, p := range pages {
				if !p.crcSet {
					t.Fatalf("%s %v at %d carries no checksum", p.column, p.kind, p.headerAt)
				}
				if got := crc32.ChecksumIEEE(fx.data[p.bodyAt : p.bodyAt+p.bodyLen]); got != p.crc {
					t.Fatalf("%s %v at %d: fixture's own checksum %#08x != %#08x over its stored body",
						p.column, p.kind, p.headerAt, p.crc, got)
				}
			}
		})
	}
}

// TestAFlippedBitInAChecksummedPageIsRefused is the #891 headline shape, one
// cell per page of every fixture: flip one payload bit and the read must fail
// naming the column, rather than answer with a value the file's own checksum
// contradicts.
func TestAFlippedBitInAChecksummedPageIsRefused(t *testing.T) {
	for _, fx := range checksummedFixtures(t) {
		t.Run(fx.name, func(t *testing.T) {
			clean, err := readEveryRow(fx.data)
			if err != nil {
				t.Fatalf("unmutated file must read: %v", err)
			}
			if len(clean) == 0 {
				t.Fatal("unmutated file read zero rows")
			}
			pages := walkPages(t, fx.data)
			for i, p := range pages {
				if p.bodyLen == 0 {
					continue
				}
				for _, bit := range []int{0, p.bodyLen * 8 / 2, p.bodyLen*8 - 1} {
					name := fmt.Sprintf("page%d_%v_bit%d", i, p.kind, bit)
					t.Run(name, func(t *testing.T) {
						mutated := append([]byte(nil), fx.data...)
						mutated[p.bodyAt+bit/8] ^= 1 << (bit % 8)
						rows, err := readEveryRow(mutated)
						if err == nil {
							t.Fatalf("column %s: a flipped bit in the %v at %d read %d rows with no error",
								p.column, p.kind, p.headerAt, len(rows))
						}
						if !strings.Contains(err.Error(), "fails its own checksum") {
							t.Fatalf("column %s: refused, but not for the checksum: %v", p.column, err)
						}
						if !strings.Contains(err.Error(), p.column) {
							t.Fatalf("refusal does not name column %s: %v", p.column, err)
						}
					})
				}
			}
		})
	}
}

// TestAPresentZeroChecksumIsStillVerified is the presence-versus-value cell.
//
// crc is an OPTIONAL thrift field and zero is a legal checksum. A reader that
// tests `CRC != 0` — parquet-go's own does — cannot tell "this writer emits no
// checksums" from "this body hashes to zero", and skips verification on the
// second. The header's field PRESENCE is what the reader gates on, so a page
// header carrying a zero checksum over a body that does not hash to zero is
// refused.
func TestAPresentZeroChecksumIsStillVerified(t *testing.T) {
	data := parquetGoFile(t, 1, gp.Compression(&gp.Uncompressed), false, 8)
	pages := walkPages(t, data)
	if len(pages) == 0 {
		t.Fatal("no pages")
	}
	p := pages[0]

	// Re-encode the page's header with its checksum set to a present zero.
	// The bodies do not move: the encoder emits the same fields, and the
	// i32 checksum is the same width whatever its value.
	ph, hdrLen, err := DecodePageHeader(data[p.headerAt:])
	if err != nil {
		t.Fatal(err)
	}
	if !ph.CRCSet {
		t.Fatalf("fixture page carries no checksum to rewrite")
	}
	ph.CRC = 0
	newHdr := EncodePageHeader(ph)

	mutated := append([]byte(nil), data[:p.headerAt]...)
	mutated = append(mutated, newHdr...)
	mutated = append(mutated, data[p.headerAt+hdrLen:]...)
	if len(newHdr) != hdrLen {
		// Re-encoding shifted everything after this header; the footer's
		// offsets no longer describe the file, and the cell would be
		// testing offset arithmetic rather than the checksum. Rebuilding
		// the footer is not worth it — the shape is asserted by the
		// re-decode below either way.
		t.Skipf("re-encoded header is %d bytes, was %d", len(newHdr), hdrLen)
	}

	back, _, err := DecodePageHeader(mutated[p.headerAt:])
	if err != nil {
		t.Fatal(err)
	}
	if !back.CRCSet || back.CRC != 0 {
		t.Fatalf("round trip lost the present-zero checksum: set=%v crc=%d", back.CRCSet, back.CRC)
	}
	if crc32.ChecksumIEEE(data[p.bodyAt:p.bodyAt+p.bodyLen]) == 0 {
		t.Skip("this body genuinely hashes to zero")
	}

	rows, err := readEveryRow(mutated)
	if err == nil {
		t.Fatalf("a present-zero checksum over a body that hashes otherwise read %d rows with no error", len(rows))
	}
	if !strings.Contains(err.Error(), "fails its own checksum") {
		t.Fatalf("refused, but not for the checksum: %v", err)
	}
}

// TestAnAbsentChecksumIsNotInvented is the other side of the presence
// boundary: every fixture in testdata/ that was written WITHOUT checksums
// still reads, and a bit flipped in one of those pages is not reported as a
// checksum failure (there is no checksum to fail). The reader verifies what
// the file carries; it does not require the file to carry it.
func TestAnAbsentChecksumIsNotInvented(t *testing.T) {
	data, err := os.ReadFile("testdata/dict_runs.parquet")
	if err != nil {
		t.Fatal(err)
	}
	for _, p := range walkPages(t, data) {
		if p.crcSet {
			t.Fatalf("fixture unexpectedly carries a checksum at %d", p.headerAt)
		}
	}
	if _, err := readEveryRow(data); err != nil {
		t.Fatalf("checksum-free file must still read: %v", err)
	}
}

// TestACorruptPageIsNotPersistedByARewrite: a rewrite reads with the row
// reader and writes what it read. Before the checksum was consulted a flipped
// bit became a value, and the rewrite made that value the durable one — the
// file that could still prove itself wrong replaced by one that cannot. The
// rewrite must fail instead.
//
// The compaction package's own gate drives the real compactor over the object
// store; this cell is the seam in the package that owns the reader.
func TestACorruptPageIsNotPersistedByARewrite(t *testing.T) {
	src := parquetGoFile(t, 1, gp.Compression(&gp.Uncompressed), false, 300)
	pages := walkPages(t, src)
	var target crcPage
	for _, p := range pages {
		if p.kind == PageDataV1 && p.bodyLen > 0 {
			target = p
			break
		}
	}
	if target.bodyLen == 0 {
		t.Fatal("no data page in fixture")
	}
	mutated := append([]byte(nil), src...)
	mutated[target.bodyAt] ^= 1

	r, err := NewReaderFromBytes(mutated)
	if err != nil {
		t.Fatal(err)
	}
	rows, err := r.ReadRows(nil)
	if err == nil {
		t.Fatalf("the rewrite's read produced %d rows out of a page that fails its checksum", len(rows))
	}

	// And nothing was written: the rewrite never reaches its writer.
	var out bytes.Buffer
	w, err := NewWriter(&out, r.Schema(), WriterConfig{})
	if err != nil {
		t.Fatal(err)
	}
	if err := w.Close(); err != nil {
		t.Fatal(err)
	}
	if len(rows) != 0 {
		t.Fatalf("rows escaped the refusal: %d", len(rows))
	}
}

func readEveryRow(data []byte) ([]map[string]any, error) {
	r, err := NewReaderFromBytes(data)
	if err != nil {
		return nil, err
	}
	return r.ReadRows(nil)
}

// FuzzPageBodyMutation mutates the BODY bytes of a checksummed page and
// asserts the only two admissible outcomes: the read is refused, or it
// produces exactly what the unmutated file produces. A third outcome — a
// different answer, quietly — is the defect.
func FuzzPageBodyMutation(f *testing.F) {
	base := parquetGoFile(f, 1, gp.Compression(&gp.Uncompressed), false, 64)
	pages := walkPages(f, base)
	if len(pages) == 0 {
		f.Fatal("no pages")
	}
	want, err := readEveryRow(base)
	if err != nil {
		f.Fatal(err)
	}
	wantStr := fmt.Sprint(want)

	f.Add(0, 0, byte(1))
	f.Add(1, 3, byte(0x80))
	f.Add(0, 7, byte(0xff))

	f.Fuzz(func(t *testing.T, pageIdx, byteIdx int, mask byte) {
		if pageIdx < 0 || byteIdx < 0 || mask == 0 {
			return
		}
		p := pages[pageIdx%len(pages)]
		if p.bodyLen == 0 {
			return
		}
		mutated := append([]byte(nil), base...)
		mutated[p.bodyAt+byteIdx%p.bodyLen] ^= mask

		got, err := readEveryRow(mutated)
		if err != nil {
			return // refused: admissible
		}
		if fmt.Sprint(got) != wantStr {
			t.Fatalf("mutating the %v at %d (byte %d, mask %#x) changed the answer without an error:\n got %v\nwant %v",
				p.kind, p.headerAt, byteIdx%p.bodyLen, mask, got, want)
		}
	})
}
