// SPDX-License-Identifier: AGPL-3.0-only

package coordinator

// The ND cells. See arc_nd_declarations_test.go for the rule and the arms.

func ndCells() []ndCell {
	return []ndCell{
		{name: "813/sum_i32_over", sql: `SELECT SUM(w_i32) OVER () AS v FROM numwidth WHERE w_key = 0`,
			want: "v:INT64 | 2<i8>"},
		{name: "813/sum_i64_over", sql: `SELECT SUM(w_i64) OVER () AS v FROM numwidth WHERE w_key = 0`,
			want: "v:DECIMAL(38,0) | 2"},
		{name: "813/cast_sum_over_bigint", sql: `SELECT CAST(SUM(w_i32) OVER () AS BIGINT) AS v FROM numwidth WHERE w_key = 0`,
			want: "v:INT64 | 2<i8>"},
		{name: "813/ctl_sum_i32_grouped", sql: `SELECT SUM(w_i32) AS v FROM numwidth`,
			want: "v:INT64 | 2164260874<i8>"},
		{name: "954/setop_sum_i32_computed", sql: `SELECT SUM(v*3000000) OVER () AS w FROM (SELECT w_i32 AS v FROM numwidth WHERE w_key < 3 UNION ALL SELECT NULL) y LIMIT 1`,
			want: "w:INT64 | 51000000<i8>"},
		{name: "954/setop_sum_i64_computed", sql: `SELECT SUM(v*3) OVER () AS w FROM (SELECT w_i64 AS v FROM numwidth WHERE w_key < 3 UNION ALL SELECT NULL) y LIMIT 1`,
			want: "w:DECIMAL(38,0) | 51"},
		{name: "954/setop_sum_dec_computed", sql: `SELECT SUM(v*1) OVER () AS w FROM (SELECT w_d4 AS v FROM numwidth WHERE w_key < 3 UNION ALL SELECT NULL) y LIMIT 1`,
			want: "w:DECIMAL(38,4) | 14.8500"},
		{name: "954/ctl_setop_sum_bare", sql: `SELECT SUM(v) OVER () AS w FROM (SELECT w_i32 AS v FROM numwidth WHERE w_key < 3 UNION ALL SELECT NULL) y LIMIT 1`,
			want: "w:INT64 | 17<i8>"},
		{name: "1011/rowfield_max_over", sql: `SELECT MAX((c_row).b) OVER (PARTITION BY id) AS v FROM typemx_nested WHERE id = 0`,
			want: "v:INT64 | 0<i8>"},
		{name: "1011/rowfield_sum_over", sql: `SELECT SUM((c_row).b) OVER (PARTITION BY id) AS v FROM typemx_nested WHERE id = 0`,
			want: "v:DECIMAL(38,0) | 0"},
		{name: "1011/rowfield_avg_over", sql: `SELECT AVG((c_row).b) OVER (PARTITION BY id) AS v FROM typemx_nested WHERE id = 0`,
			want: "v:DECIMAL(38,4) | 0.0000",
			why:  "PostgreSQL 17.11 renders 0.00000000000000000000 under unconstrained numeric: the same AvgScale digit-count divergence cell 952/avg_i32_grouped names, one spelling over. The NUMBER agrees."},
		{name: "1011/rowfield_min_dec_over", sql: `SELECT MIN((c_row).dc) OVER (PARTITION BY id) AS v FROM typemx_nested WHERE id = 0`,
			want: "v:DECIMAL(18,4) | 0.0000",
			pin:  map[string]string{"dag": "v:DECIMAL | 0.0000", "dagshuf": "v:DECIMAL | 0.0000", "morsel": "v:DECIMAL | 0.0000"},
			why:  "The VALUE is the same on all five arms. The stage arms declare DECIMAL with no (p,s) where the single arm declares DECIMAL(18,4): on the DAG the result schema is the worker's BATCH schema, and a ROW-FIELD-PATH window key loses its (p,s) somewhere between the stage spec and the window output column. The non-field twin (column_min_dec_over) agrees on all five, which is what says this is the field path and not the DECIMAL window path."},
		{name: "1011/column_min_dec_over", sql: `SELECT MIN(c_dec) OVER (PARTITION BY id) AS v FROM typemx WHERE id = 0`,
			want: "v:DECIMAL(18,4) | 0.0000"},
		{name: "1011/rowfield_max_date_over", sql: `SELECT MAX((c_row).dt) OVER (PARTITION BY id) AS v FROM typemx_nested WHERE id = 0`,
			want: "v:DATE | 2010-01-01"},
		{name: "1011/rowfield_count_over", sql: `SELECT COUNT((c_row).b) OVER (PARTITION BY id) AS v FROM typemx_nested WHERE id = 0`,
			want: "v:INT64 | 1<i8>"},
		{name: "951/minmax_i32_grouped", sql: `SELECT MIN(w_i32) AS lo, MAX(w_i32) AS hi FROM numwidth GROUP BY w_key HAVING w_key = 5`,
			want: "lo:INT32 hi:INT32 | -20<i4>,-20<i4>"},
		{name: "951/minmax_i32_scalar", sql: `SELECT MIN(w_i32) AS lo, MAX(w_i32) AS hi FROM numwidth`,
			want: "lo:INT32 hi:INT32 | -20<i4>,2147483647<i4>"},
		{name: "951/minmax_i32_filtered", sql: `SELECT MIN(w_i32) AS lo, MAX(w_i32) AS hi FROM numwidth WHERE w_key >= 0`,
			want: "lo:INT32 hi:INT32 | -20<i4>,2147483647<i4>"},
		{name: "951/minmax_i32_over", sql: `SELECT MIN(w_i32) OVER () AS lo FROM numwidth WHERE w_key = 0`,
			want: "lo:INT32 | 2<i4>"},
		{name: "951/ctl_minmax_i64", sql: `SELECT MIN(w_i64) AS lo, MAX(w_i64) AS hi FROM numwidth`,
			want: "lo:INT64 hi:INT64 | -20<i8>,9007199254740993<i8>"},
		{name: "1018/band_i32", sql: `SELECT BITWISE_AND(w_i32, 6) AS v FROM numwidth WHERE w_key = 2`,
			want: "v:INT32 | 4<i4>"},
		{name: "1018/bor_i32", sql: `SELECT BITWISE_OR(w_i32, 6) AS v FROM numwidth WHERE w_key = 2`,
			want: "v:INT32 | 14<i4>"},
		{name: "1018/bxor_i32", sql: `SELECT BITWISE_XOR(w_i32, 6) AS v FROM numwidth WHERE w_key = 2`,
			want: "v:INT32 | 10<i4>"},
		{name: "1018/bnot_i32", sql: `SELECT BITWISE_NOT(w_i32) AS v FROM numwidth WHERE w_key = 2`,
			want: "v:INT32 | -13<i4>"},
		{name: "1018/band_i64", sql: `SELECT BITWISE_AND(w_i64, 6) AS v FROM numwidth WHERE w_key = 2`,
			want: "v:INT64 | 4<i8>"},
		{name: "1018/band_mixed", sql: `SELECT BITWISE_AND(w_i32, w_i64) AS v FROM numwidth WHERE w_key = 2`,
			want: "v:INT64 | 12<i8>"},
		{name: "1018/band_port", sql: `SELECT BITWISE_AND(c_port, 6) AS v FROM typemx WHERE id = 0`,
			want: "v:INT32 | 0<i4>"},
		{name: "1018/shift_left_i32_still_answers", sql: `SELECT BITWISE_LEFT_SHIFT(w_i32, 2) AS v FROM numwidth WHERE w_key = 9`,
			want: "v:INT64 | 8589934588<i8>",
			why:  "PostgreSQL 17.11 declares integer and answers -4: its int4 shift is MODULAR. This engine shifts on the int64 carrier and answers 8589934588 under bigint — ADR-0012's shift divergence, and the reason the bitwise family's int4 declaration stops at AND/OR/XOR/NOT (expr.PGIntegerResult.FitsOperands)."},
		{name: "1018/sum_band_i32", sql: `SELECT SUM(BITWISE_AND(w_i32, 3)) AS v FROM numwidth`,
			want: "v:INT64 | 10<i8>"},
		{name: "1018/sum_band_i64", sql: `SELECT SUM(BITWISE_AND(w_i64, 3)) AS v FROM numwidth`,
			want: "v:DECIMAL(38,0) | 8"},
		{name: "1029/sum_over_grouped_key_i32", sql: `SELECT SUM(k) AS v FROM (SELECT BITWISE_AND(w_i32, 3) AS k, COUNT(*) AS n FROM numwidth GROUP BY w_i32) s`,
			want: "v:INT64 | 10<i8>"},
		{name: "1029/sum_band_over_grouped_key_i32", sql: `SELECT SUM(BITWISE_AND(g, 3)) AS v FROM (SELECT w_i32 AS g, COUNT(*) AS n FROM numwidth GROUP BY w_i32) s`,
			want: "v:INT64 | 10<i8>"},
		{name: "1029/sum_band_over_grouped_key_i64", sql: `SELECT SUM(BITWISE_AND(g, 3)) AS v FROM (SELECT w_i64 AS g, COUNT(*) AS n FROM numwidth GROUP BY w_i64) s`,
			want: "v:DECIMAL(38,0) | 8"},
		{name: "1029/sum_count_times_two", sql: `SELECT SUM(n * 2) AS v FROM (SELECT w_i32 AS g, COUNT(*) AS n FROM numwidth GROUP BY w_i32) s`,
			want: "v:DECIMAL(38,0) | 20"},
		{name: "1029/sum_band_over_agg_output", sql: `SELECT SUM(BITWISE_AND(m, 3)) AS v FROM (SELECT w_i32 AS g, MIN(w_i32) AS m FROM numwidth GROUP BY w_i32) s`,
			want: "v:INT64 | 10<i8>"},
		// The shapes that actually reach the site #1029 names: an int4-WIDTH
		// expression whose CARRIER is an int64. PREFIX_LENGTH is `masklen` on
		// the server, whose result is integer, and this engine stores it in an
		// int64 — so the width has to ride the derived key's declaration or
		// the SUM above it declares numeric where PostgreSQL declares bigint.
		{name: "1029/sum_derived_key_width4", sql: `SELECT SUM(p) AS v FROM (SELECT g, PREFIX_LENGTH(c_cidr) AS p FROM typemx GROUP BY g, c_cidr) s`,
			want: "v:INT64 | 91048<i8>"},
		{name: "1029/sum_derived_key_width8", sql: `SELECT SUM(p) AS v FROM (SELECT g, BIT_COUNT(c_bytes) AS p FROM typemx GROUP BY g, c_bytes) s`,
			want: "v:DECIMAL(38,0) | 0"},
		{name: "1070/literal_one", sql: `SELECT 1 AS v`,
			want: "v:INT32 | 1<i4>"},
		{name: "1070/scalar_subquery_literal", sql: `SELECT (SELECT 1) AS v FROM numwidth WHERE w_key = 0`,
			want: "v:INT32 | 1<i4>"},
		{name: "1070/scalar_subquery_arith", sql: `SELECT (SELECT w_i32 + 1 FROM numwidth WHERE w_key = 0) AS v FROM numwidth WHERE w_key = 0`,
			want: "v:INT64 | 3<i8>",
			why:  "PostgreSQL 17.11 declares integer. int4 ARITHMETIC and an integer CAST keep bigint here: the three stage arms type an expression written over a PUBLISHED SLOT (`__agg_N`, `__win_N`) from something coarser than the single-process walk reads, so narrowing this gave one expression two declarations — #813 item 1's class, which this arc exists to forbid. Measured on both halves (1e1a6ad8, reverted by 66105125 and b21070bd), put back, and recorded in ADR-0012 and ADR-0024 2b as residual R6."},
		{name: "1070/i32_plus_one", sql: `SELECT w_i32 + 1 AS v FROM numwidth WHERE w_key = 0`,
			want: "v:INT64 | 3<i8>",
			why:  "PostgreSQL 17.11 declares integer. int4 ARITHMETIC and an integer CAST keep bigint here: the three stage arms type an expression written over a PUBLISHED SLOT (`__agg_N`, `__win_N`) from something coarser than the single-process walk reads, so narrowing this gave one expression two declarations — #813 item 1's class, which this arc exists to forbid. Measured on both halves (1e1a6ad8, reverted by 66105125 and b21070bd), put back, and recorded in ADR-0012 and ADR-0024 2b as residual R6."},
		{name: "1070/cast_to_int", sql: `SELECT CAST(w_i32 AS INT) AS v FROM numwidth WHERE w_key = 0`,
			want: "v:INT64 | 2<i8>",
			why:  "PostgreSQL 17.11 declares integer. Every integer CAST spelling declares bigint here: the DAG declares a CAST OVER A WINDOW from the window's own output rather than from the cast, so `CAST(SUM(a) OVER () AS INTEGER)` was int4 locally and int8 on the stage arms — one expression, two declarations. Measured (1e1a6ad8), reverted (66105125), recorded in ADR-0012 item 12 and ADR-0024 2b as residual R6. The cast evaluator still enforces each spelling's RANGE, so the VALUE is int4's."},
		{name: "1070/neg_i32", sql: `SELECT -w_i32 AS v FROM numwidth WHERE w_key = 0`,
			want: "v:INT64 | -2<i8>",
			why:  "PostgreSQL 17.11 declares integer. int4 ARITHMETIC and an integer CAST keep bigint here: the three stage arms type an expression written over a PUBLISHED SLOT (`__agg_N`, `__win_N`) from something coarser than the single-process walk reads, so narrowing this gave one expression two declarations — #813 item 1's class, which this arc exists to forbid. Measured on both halves (1e1a6ad8, reverted by 66105125 and b21070bd), put back, and recorded in ADR-0012 and ADR-0024 2b as residual R6."},
		{name: "952/avg_i32_grouped", sql: `SELECT AVG(w_i32) AS v FROM numwidth GROUP BY w_key HAVING w_key = 5`,
			want: "v:DECIMAL(38,4) | -20.0000",
			why:  "PostgreSQL 17.11 renders -20.0000000000000000: its avg(int) keeps sixteen significant digits and this engine keeps batch.AvgScale(0) = 4. The NUMBER is the same and both are exact to min(scale) — ADR-0024 item 3's recorded digit-count divergence, which the DECIMAL carrier decides and this arc does not."},
		{name: "952/avg_i64_scalar", sql: `SELECT AVG(w_i64) AS v FROM numwidth`,
			want: "v:DECIMAL(38,4) | 1000800157666874.2222"},
		{name: "1117/real_plus_real", sql: `SELECT w_f32 + CAST(1.0 AS REAL) AS v FROM numwidth WHERE w_key = 3`,
			want: "v:FLOAT32 | 1.6777216e+07<f4>"},
		{name: "1117/real_times_real", sql: `SELECT w_f32 * CAST(2.0 AS REAL) AS v FROM numwidth WHERE w_key = 3`,
			want: "v:FLOAT32 | 3.3554432e+07<f4>"},
		{name: "1117/real_plus_numeric_literal", sql: `SELECT w_f32 + 1.0 AS v FROM numwidth WHERE w_key = 3`,
			want: "v:FLOAT64 | 1.6777217e+07<f8>"},
		{name: "1117/real_plus_integer", sql: `SELECT w_f32 + 1 AS v FROM numwidth WHERE w_key = 3`,
			want: "v:FLOAT64 | 1.6777217e+07<f8>"},
		{name: "1117/real_plus_double", sql: `SELECT w_f32 + w_f64 AS v FROM numwidth WHERE w_key = 3`,
			want: "v:FLOAT64 | 3.3554433e+07<f8>"},
		{name: "1117/neg_real", sql: `SELECT -w_f32 AS v FROM numwidth WHERE w_key = 3`,
			want: "v:FLOAT32 | -1.6777216e+07<f4>"},
		{name: "1117/real_overflow_is_loud", sql: `SELECT CAST(1e38 AS REAL) * CAST(10.0 AS REAL) AS v`,
			// The DAG arms' "two sentences" pin was deleted by arc PC: a coded
			// refusal is its own sentence on every door (#1145).
			want: "ERR value out of range: overflow"},
		{name: "1117/sum_real_computed", sql: `SELECT SUM(w_f32 + CAST(1.0 AS REAL)) AS v FROM numwidth`,
			want: "v:FLOAT32 | 1.6777232e+07<f4>"},
		{name: "1117/avg_real_computed", sql: `SELECT AVG(w_f32 + CAST(1.0 AS REAL)) AS v FROM numwidth`,
			want: "v:FLOAT64 | 2.097154012500003e+06<f8>",
			pin:  map[string]string{"dag": "v:FLOAT64 | 2.0971540125000477e+06<f8>", "dagshuf": "v:FLOAT64 | 2.0971540125000477e+06<f8>", "morsel": "v:FLOAT64 | 2.0971540125000477e+06<f8>"},
			why:  "ADR-0013 class 9 again, one function over: AVG(real) totals at float8's width (which is the server's type) over float4 SUMMANDS, so the arms differ in the eleventh digit by association alone."},
		{name: "1117/ctl_real_column", sql: `SELECT w_f32 AS v FROM numwidth WHERE w_key = 3`,
			want: "v:FLOAT32 | 1.6777216e+07<f4>"},
		// The BOUNDARY of #1117's rule, measured on five arms against
		// PostgreSQL 17.11. A set-operation ARM is the position where the
		// projection's own declaration is REPLACED by the union's common
		// type, so the store that does the rounding never happens — and the
		// three stage arms answered 1.6777217e+07 where the two local arms
		// answered PostgreSQL's 1.6777216e+07 until setOpCastExpr narrowed
		// the arm first. Each operation is its own signal: UNION ALL prints
		// both numbers, UNION folds them to one row, INTERSECT keeps a row
		// and EXCEPT keeps none.
		{name: "1117/setop_real_arm_union_all", sql: `SELECT w_f32 + CAST(1.0 AS REAL) AS v FROM numwidth WHERE w_key = 3 UNION ALL SELECT w_f64 - 1.0 FROM numwidth WHERE w_key = 3`,
			want: "v:FLOAT64 | 1.6777216e+07<f8> | 1.6777216e+07<f8>"},
		{name: "1117/setop_real_arm_union", sql: `SELECT w_f32 + CAST(1.0 AS REAL) AS v FROM numwidth WHERE w_key = 3 UNION SELECT w_f64 - 1.0 FROM numwidth WHERE w_key = 3`,
			want: "v:FLOAT64 | 1.6777216e+07<f8>"},
		{name: "1117/setop_real_arm_intersect", sql: `SELECT w_f32 + CAST(1.0 AS REAL) AS v FROM numwidth WHERE w_key = 3 INTERSECT SELECT w_f64 - 1.0 FROM numwidth WHERE w_key = 3`,
			want: "v:FLOAT64 | 1.6777216e+07<f8>"},
		{name: "1117/setop_real_arm_except", sql: `SELECT w_f32 + CAST(1.0 AS REAL) AS v FROM numwidth WHERE w_key = 3 EXCEPT SELECT w_f64 - 1.0 FROM numwidth WHERE w_key = 3`,
			want: "v:FLOAT64"},
		{name: "1117/setop_real_arm_in_a_cte", sql: `WITH u AS (SELECT w_f32 + CAST(1.0 AS REAL) AS v FROM numwidth WHERE w_key = 3 UNION ALL SELECT w_f64 - 1.0 FROM numwidth WHERE w_key = 3) SELECT v FROM u ORDER BY v`,
			want: "v:FLOAT64 | 1.6777216e+07<f8> | 1.6777216e+07<f8>"},
		{name: "1117/setop_real_arm_in_a_derived_block", sql: `SELECT v FROM (SELECT w_f32 + CAST(1.0 AS REAL) AS v FROM numwidth WHERE w_key = 3 UNION ALL SELECT w_f64 - 1.0 FROM numwidth WHERE w_key = 3) s ORDER BY v`,
			want: "v:FLOAT64 | 1.6777216e+07<f8> | 1.6777216e+07<f8>"},
		// The controls that keep the narrowing on the rung it belongs to:
		// real ∪ real reconciles to real and takes no cast at all, and the
		// integer ladder is untouched by a rule about float4.
		{name: "1117/ctl_setop_both_real", sql: `SELECT w_f32 + CAST(1.0 AS REAL) AS v FROM numwidth WHERE w_key = 3 UNION ALL SELECT w_f32 FROM numwidth WHERE w_key = 3`,
			want: "v:FLOAT32 | 1.6777216e+07<f4> | 1.6777216e+07<f4>"},
		{name: "1117/ctl_setop_int_ladder", sql: `SELECT w_i32 AS v FROM numwidth WHERE w_key = 0 UNION ALL SELECT w_i64 FROM numwidth WHERE w_key = 0`,
			want: "v:INT64 | 2<i8> | 2<i8>"},
		// The COMPARISON positions, where the declaration does not reach, so
		// the row the predicate selected prints a number the predicate says
		// it does not hold.
		{name: "1117/real_arith_in_a_predicate", sql: `SELECT w_f32 + CAST(1.0 AS REAL) AS v FROM numwidth WHERE w_key = 3 AND w_f32 + CAST(1.0 AS REAL) > CAST(16777216 AS REAL)`,
			want: "v:FLOAT32 | 1.6777216e+07<f4>",
			why:  "PostgreSQL 17.11 returns NO rows here, and answers the other way on each spelling below too: the row for `=`, key 3 for the bare filter, 'eq' for the CASE. #1117 narrows by DECLARATION — a projection stores the float64 carrier's result into the float4 vector its declaration names, and that STORE is the rounding. A comparison has no output vector, so the carrier's float8 digits reach the operator and 2^24 + 1.0::real compares as 16777217. The ROW SET is the base row set; what #1117 changed is that the row now PRINTS the number the predicate denies. The ctl cell below is the mechanism: spelling the CAST is PostgreSQL's answer on all five arms. Closing it means rounding AT the operator, and the three stage arms cannot take that from the local planner — a worker compiles its fragment's expressions from SQL text with no declaration walk — so a rewrite that lands on single and budget alone (measured: it does) replaces one wrong answer with two different ones. Filed rather than half-fixed; ADR-0012 carries it."},
		{name: "1117/real_arith_in_an_equality_predicate", sql: `SELECT w_f32 + CAST(1.0 AS REAL) AS v FROM numwidth WHERE w_key = 3 AND w_f32 + CAST(1.0 AS REAL) = CAST(16777216 AS REAL)`,
			want: "v:FLOAT32",
			why:  "The seam of 1117/real_arith_in_a_predicate, the other way round: PostgreSQL 17.11 returns the row and this returns none."},
		{name: "1117/real_arith_as_the_only_filter", sql: `SELECT w_key AS v FROM numwidth WHERE w_f32 + CAST(1.0 AS REAL) = CAST(16777216 AS REAL)`,
			want: "v:INT64",
			why:  "The same seam with no projection of the expression at all: PostgreSQL 17.11 returns key 3."},
		{name: "1117/real_arith_in_a_case_condition", sql: `SELECT CASE WHEN w_f32 + CAST(1.0 AS REAL) = CAST(16777216 AS REAL) THEN 'eq' ELSE 'ne' END AS v FROM numwidth WHERE w_key = 3`,
			want: "v:STRING | ne",
			why:  "The same seam inside a CASE condition: PostgreSQL 17.11 answers 'eq'."},
		{name: "1117/ctl_real_arith_cast_in_a_predicate", sql: `SELECT w_f32 + CAST(1.0 AS REAL) AS v FROM numwidth WHERE w_key = 3 AND CAST(w_f32 + CAST(1.0 AS REAL) AS REAL) > CAST(16777216 AS REAL)`,
			want: "v:FLOAT32"},
		{name: "1117/ctl_real_arith_cast_in_a_case_condition", sql: `SELECT CASE WHEN CAST(w_f32 + CAST(1.0 AS REAL) AS REAL) = CAST(16777216 AS REAL) THEN 'eq' ELSE 'ne' END AS v FROM numwidth WHERE w_key = 3`,
			want: "v:STRING | eq"},
		// NESTING, the other position with no output vector to round in.
		{name: "1117/nested_real_arith", sql: `SELECT (w_f32 + CAST(1.0 AS REAL)) + CAST(1.0 AS REAL) AS v FROM numwidth WHERE w_key = 3`,
			want: "v:FLOAT32 | 1.6777218e+07<f4>",
			why:  "PostgreSQL 17.11 answers 1.6777216e+07: it rounds at EVERY float4 operator, so the inner sum is already 16777216 when the second one runs. Here the whole expression computes on the float64 carrier and rounds once, at the projection's store — so an inner step keeps digits float4 does not have. Same seam and same filing as the predicate cells above; the ctl cell below is the mechanism."},
		{name: "1117/ctl_nested_real_arith_cast", sql: `SELECT CAST(w_f32 + CAST(1.0 AS REAL) AS REAL) + CAST(1.0 AS REAL) AS v FROM numwidth WHERE w_key = 3`,
			want: "v:FLOAT32 | 1.6777216e+07<f4>"},
		{name: "1118/sum_real_over", sql: `SELECT SUM(w_f32) OVER () AS v FROM numwidth WHERE w_key = 0`,
			want: "v:FLOAT32 | 2<f4>"},
		{name: "1118/sum_real_grouped", sql: `SELECT SUM(w_f32) AS v FROM numwidth`,
			want:   "v:FLOAT32 | 1.67772e+07<f4>",
			digits: 6,
			why: "ADR-0013 nondeterminism class 9 at float4's carrier: the DAG folds " +
				"three partial real totals and the association reaches the sixth " +
				"significant digit, and WHICH arm lands on which of 1.6777224e+07 and " +
				"1.6777226e+07 moves between runs. PostgreSQL's own parallel aggregate " +
				"has the property. Six digits is where the two agree, and the cell is " +
				"about the real DECLARATION either way."},
		{name: "1118/avg_real_over", sql: `SELECT AVG(w_f32) OVER () AS v FROM numwidth WHERE w_key = 0`,
			want: "v:FLOAT64 | 2<f8>"},
		{name: "1118/min_real_over", sql: `SELECT MIN(w_f32) OVER () AS v FROM numwidth WHERE w_key = 0`,
			want: "v:FLOAT32 | 2<f4>"},
		{name: "1119/bare_wide_integer_literal", sql: `SELECT 9007199254740993 AS v`,
			want: "v:INT64 | 9007199254740993<i8>"},
		{name: "1119/bare_wide_fractional_literal", sql: `SELECT 9007199254740993.25 AS v`,
			want: "v:FLOAT64 | 9.007199254740994e+15<f8>",
			why:  "PostgreSQL 17.11 declares numeric and answers 9007199254740993.25. A BARE numeric literal with a fractional part still goes through compileLit's float64 box here — ADR-0024's recorded literal deferral. The INTEGER spelling beside it agrees (bare_wide_integer_literal), and a CAST of the same literal has been exact since #1037."},
		{name: "1119/bare_int4_boundary_literal", sql: `SELECT 2147483648 AS v`,
			want: "v:INT64 | 2147483648<i8>"},
	}
}
