package coordinator

// PostgreSQL 17.11's OWN ANSWER for every cell of the join-arm table (arc R2),
// measured live in a container of this arc's own (`wadjet-pg-r2`, port 55452,
// `postgres:17.11`, `--locale=C` with `COLLATE "C"` text columns per
// CLAUDE.md) over the same rows the corpus holds — `lat_ord` (three orders,
// ids 1..3, customers Alice/Bob/Carol) and `lat_item` (four items, two for
// each of orders 1 and 2). Each cell was rendered through `\\gdesc` for the
// declared types and once more for the rows; the PostgreSQL type names map to
// wadjet's as bigint->INT64, integer->INT32, text->STRING, double
// precision->FLOAT64, numeric(p,s)->DECIMAL(p,s).
//
// The measurement was taken BEFORE any code in this arc changed, so a cell
// that agrees here agreed with PostgreSQL at base too. The gate fails a cell
// with no entry: the table is the claim, and a position nobody measured is
// not one.
var r2Want = map[string]string{
	"except-collide/both/distinct":                 "cols=[id:INT64 customer:STRING id:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"except-collide/both/group":                    "cols=[id:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"except-collide/both/list":                     "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=2 | 1,Alice,1,Alice | 2,Bob,2,Bob",
	"except-collide/both/ord":                      "cols=[customer:STRING id:INT64 id:INT64] rows=2 | Alice,1,1 | Bob,2,2",
	"except-collide/both/qual":                     "cols=[id:INT64] rows=2 | 1 | 2",
	"except-collide/both/star":                     "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=2 | 1,Alice,1,Alice | 2,Bob,2,Bob",
	"except-collide/left/distinct":                 "cols=[id:INT64 customer:STRING id:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"except-collide/left/group":                    "cols=[id:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"except-collide/left/list":                     "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=2 | 1,Alice,1,Alice | 2,Bob,2,Bob",
	"except-collide/left/ord":                      "cols=[customer:STRING id:INT64 id:INT64] rows=2 | Alice,1,1 | Bob,2,2",
	"except-collide/left/qual":                     "cols=[id:INT64] rows=2 | 1 | 2",
	"except-collide/left/star":                     "cols=[id:INT64 customer:STRING id:INT64 customer:STRING total:FLOAT64] rows=2 | 1,Alice,1,Alice,150 | 2,Bob,2,Bob,200",
	"except-collide/right/distinct":                "cols=[id:INT64 customer:STRING id:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"except-collide/right/group":                   "cols=[id:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"except-collide/right/list":                    "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=2 | 1,Alice,1,Alice | 2,Bob,2,Bob",
	"except-collide/right/ord":                     "cols=[customer:STRING id:INT64 id:INT64] rows=2 | Alice,1,1 | Bob,2,2",
	"except-collide/right/qual":                    "cols=[id:INT64] rows=2 | 1 | 2",
	"except-collide/right/star":                    "cols=[id:INT64 customer:STRING total:FLOAT64 id:INT64 customer:STRING] rows=2 | 1,Alice,150,1,Alice | 2,Bob,200,2,Bob",
	"except/both/distinct":                         "cols=[k:INT64 p:STRING k:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"except/both/group":                            "cols=[k:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"except/both/list":                             "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=2 | 1,Alice,1,Alice | 2,Bob,2,Bob",
	"except/both/ord":                              "cols=[p:STRING k:INT64 k:INT64] rows=2 | Alice,1,1 | Bob,2,2",
	"except/both/qual":                             "cols=[k:INT64] rows=2 | 1 | 2",
	"except/both/star":                             "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=2 | 1,Alice,1,Alice | 2,Bob,2,Bob",
	"except/left/distinct":                         "cols=[k:INT64 p:STRING id:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"except/left/group":                            "cols=[k:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"except/left/list":                             "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=2 | 1,Alice,1,Alice | 2,Bob,2,Bob",
	"except/left/ord":                              "cols=[p:STRING k:INT64 id:INT64] rows=2 | Alice,1,1 | Bob,2,2",
	"except/left/qual":                             "cols=[k:INT64] rows=2 | 1 | 2",
	"except/left/star":                             "cols=[k:INT64 p:STRING id:INT64 customer:STRING total:FLOAT64] rows=2 | 1,Alice,1,Alice,150 | 2,Bob,2,Bob,200",
	"except/right/distinct":                        "cols=[k:INT64 p:STRING id:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"except/right/group":                           "cols=[k:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"except/right/list":                            "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=2 | 1,Alice,1,Alice | 2,Bob,2,Bob",
	"except/right/ord":                             "cols=[p:STRING k:INT64 id:INT64] rows=2 | Alice,1,1 | Bob,2,2",
	"except/right/qual":                            "cols=[k:INT64] rows=2 | 1 | 2",
	"except/right/star":                            "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=2 | 1,Alice,150,1,Alice | 2,Bob,200,2,Bob",
	"grouped-alias-src-collide/both/distinct":      "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Doohickey,1 | 1,Gadget,1 | 2,Widget,2",
	"grouped-alias-src-collide/both/group":         "cols=[id:INT64 n:INT64] rows=2 | 1,4 | 2,1",
	"grouped-alias-src-collide/both/list":          "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=5 | 1,Doohickey,1,Doohickey | 1,Doohickey,1,Gadget | 1,Gadget,1,Doohickey | 1,Gadget,1,Gadget | 2,Widget,2,Widget",
	"grouped-alias-src-collide/both/ord":           "cols=[customer:STRING id:INT64 id:INT64] rows=5 | Doohickey,1,1 | Doohickey,1,1 | Gadget,1,1 | Gadget,1,1 | Widget,2,2",
	"grouped-alias-src-collide/both/qual":          "cols=[id:INT64] rows=5 | 1 | 1 | 1 | 1 | 2",
	"grouped-alias-src-collide/both/star":          "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=5 | 1,Doohickey,1,Doohickey | 1,Doohickey,1,Gadget | 1,Gadget,1,Doohickey | 1,Gadget,1,Gadget | 2,Widget,2,Widget",
	"grouped-alias-src-collide/left/distinct":      "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Doohickey,1 | 1,Gadget,1 | 2,Widget,2",
	"grouped-alias-src-collide/left/group":         "cols=[id:INT64 n:INT64] rows=2 | 1,2 | 2,1",
	"grouped-alias-src-collide/left/list":          "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=3 | 1,Doohickey,1,Alice | 1,Gadget,1,Alice | 2,Widget,2,Bob",
	"grouped-alias-src-collide/left/ord":           "cols=[customer:STRING id:INT64 id:INT64] rows=3 | Doohickey,1,1 | Gadget,1,1 | Widget,2,2",
	"grouped-alias-src-collide/left/qual":          "cols=[id:INT64] rows=3 | 1 | 1 | 2",
	"grouped-alias-src-collide/left/star":          "cols=[id:INT64 customer:STRING id:INT64 customer:STRING total:FLOAT64] rows=3 | 1,Doohickey,1,Alice,150 | 1,Gadget,1,Alice,150 | 2,Widget,2,Bob,200",
	"grouped-alias-src-collide/right/distinct":     "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Doohickey,1 | 1,Gadget,1 | 2,Widget,2",
	"grouped-alias-src-collide/right/group":        "cols=[id:INT64 n:INT64] rows=2 | 1,2 | 2,1",
	"grouped-alias-src-collide/right/list":         "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=3 | 1,Doohickey,1,Alice | 1,Gadget,1,Alice | 2,Widget,2,Bob",
	"grouped-alias-src-collide/right/ord":          "cols=[customer:STRING id:INT64 id:INT64] rows=3 | Doohickey,1,1 | Gadget,1,1 | Widget,2,2",
	"grouped-alias-src-collide/right/qual":         "cols=[id:INT64] rows=3 | 1 | 1 | 2",
	"grouped-alias-src-collide/right/star":         "cols=[id:INT64 customer:STRING total:FLOAT64 id:INT64 customer:STRING] rows=3 | 1,Alice,150,1,Doohickey | 1,Alice,150,1,Gadget | 2,Bob,200,2,Widget",
	"grouped-alias-src/both/distinct":              "cols=[k:INT64 p:STRING k:INT64] rows=3 | 1,Doohickey,1 | 1,Gadget,1 | 2,Widget,2",
	"grouped-alias-src/both/group":                 "cols=[k:INT64 n:INT64] rows=2 | 1,4 | 2,1",
	"grouped-alias-src/both/list":                  "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=5 | 1,Doohickey,1,Doohickey | 1,Doohickey,1,Gadget | 1,Gadget,1,Doohickey | 1,Gadget,1,Gadget | 2,Widget,2,Widget",
	"grouped-alias-src/both/ord":                   "cols=[p:STRING k:INT64 k:INT64] rows=5 | Doohickey,1,1 | Doohickey,1,1 | Gadget,1,1 | Gadget,1,1 | Widget,2,2",
	"grouped-alias-src/both/qual":                  "cols=[k:INT64] rows=5 | 1 | 1 | 1 | 1 | 2",
	"grouped-alias-src/both/star":                  "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=5 | 1,Doohickey,1,Doohickey | 1,Doohickey,1,Gadget | 1,Gadget,1,Doohickey | 1,Gadget,1,Gadget | 2,Widget,2,Widget",
	"grouped-alias-src/left/distinct":              "cols=[k:INT64 p:STRING id:INT64] rows=3 | 1,Doohickey,1 | 1,Gadget,1 | 2,Widget,2",
	"grouped-alias-src/left/group":                 "cols=[k:INT64 n:INT64] rows=2 | 1,2 | 2,1",
	"grouped-alias-src/left/list":                  "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=3 | 1,Doohickey,1,Alice | 1,Gadget,1,Alice | 2,Widget,2,Bob",
	"grouped-alias-src/left/ord":                   "cols=[p:STRING k:INT64 id:INT64] rows=3 | Doohickey,1,1 | Gadget,1,1 | Widget,2,2",
	"grouped-alias-src/left/qual":                  "cols=[k:INT64] rows=3 | 1 | 1 | 2",
	"grouped-alias-src/left/star":                  "cols=[k:INT64 p:STRING id:INT64 customer:STRING total:FLOAT64] rows=3 | 1,Doohickey,1,Alice,150 | 1,Gadget,1,Alice,150 | 2,Widget,2,Bob,200",
	"grouped-alias-src/right/distinct":             "cols=[k:INT64 p:STRING id:INT64] rows=3 | 1,Doohickey,1 | 1,Gadget,1 | 2,Widget,2",
	"grouped-alias-src/right/group":                "cols=[k:INT64 n:INT64] rows=2 | 1,2 | 2,1",
	"grouped-alias-src/right/list":                 "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=3 | 1,Doohickey,1,Alice | 1,Gadget,1,Alice | 2,Widget,2,Bob",
	"grouped-alias-src/right/ord":                  "cols=[p:STRING k:INT64 id:INT64] rows=3 | Doohickey,1,1 | Gadget,1,1 | Widget,2,2",
	"grouped-alias-src/right/qual":                 "cols=[k:INT64] rows=3 | 1 | 1 | 2",
	"grouped-alias-src/right/star":                 "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=3 | 1,Alice,150,1,Doohickey | 1,Alice,150,1,Gadget | 2,Bob,200,2,Widget",
	"grouped-collide/both/distinct":                "cols=[id:INT64 customer:STRING id:INT64] rows=2 | 1,Widget,1 | 2,Widget,2",
	"grouped-collide/both/group":                   "cols=[id:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"grouped-collide/both/list":                    "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=2 | 1,Widget,1,Widget | 2,Widget,2,Widget",
	"grouped-collide/both/ord":                     "cols=[customer:STRING id:INT64 id:INT64] rows=2 | Widget,1,1 | Widget,2,2",
	"grouped-collide/both/qual":                    "cols=[id:INT64] rows=2 | 1 | 2",
	"grouped-collide/both/star":                    "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=2 | 1,Widget,1,Widget | 2,Widget,2,Widget",
	"grouped-collide/left/distinct":                "cols=[id:INT64 customer:STRING id:INT64] rows=2 | 1,Widget,1 | 2,Widget,2",
	"grouped-collide/left/group":                   "cols=[id:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"grouped-collide/left/list":                    "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=2 | 1,Widget,1,Alice | 2,Widget,2,Bob",
	"grouped-collide/left/ord":                     "cols=[customer:STRING id:INT64 id:INT64] rows=2 | Widget,1,1 | Widget,2,2",
	"grouped-collide/left/qual":                    "cols=[id:INT64] rows=2 | 1 | 2",
	"grouped-collide/left/star":                    "cols=[id:INT64 customer:STRING id:INT64 customer:STRING total:FLOAT64] rows=2 | 1,Widget,1,Alice,150 | 2,Widget,2,Bob,200",
	"grouped-collide/right/distinct":               "cols=[id:INT64 customer:STRING id:INT64] rows=2 | 1,Widget,1 | 2,Widget,2",
	"grouped-collide/right/group":                  "cols=[id:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"grouped-collide/right/list":                   "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=2 | 1,Widget,1,Alice | 2,Widget,2,Bob",
	"grouped-collide/right/ord":                    "cols=[customer:STRING id:INT64 id:INT64] rows=2 | Widget,1,1 | Widget,2,2",
	"grouped-collide/right/qual":                   "cols=[id:INT64] rows=2 | 1 | 2",
	"grouped-collide/right/star":                   "cols=[id:INT64 customer:STRING total:FLOAT64 id:INT64 customer:STRING] rows=2 | 1,Alice,150,1,Widget | 2,Bob,200,2,Widget",
	"grouped/both/distinct":                        "cols=[k:INT64 p:STRING k:INT64] rows=2 | 1,Widget,1 | 2,Widget,2",
	"grouped/both/group":                           "cols=[k:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"grouped/both/list":                            "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=2 | 1,Widget,1,Widget | 2,Widget,2,Widget",
	"grouped/both/ord":                             "cols=[p:STRING k:INT64 k:INT64] rows=2 | Widget,1,1 | Widget,2,2",
	"grouped/both/qual":                            "cols=[k:INT64] rows=2 | 1 | 2",
	"grouped/both/star":                            "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=2 | 1,Widget,1,Widget | 2,Widget,2,Widget",
	"grouped/left/distinct":                        "cols=[k:INT64 p:STRING id:INT64] rows=2 | 1,Widget,1 | 2,Widget,2",
	"grouped/left/group":                           "cols=[k:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"grouped/left/list":                            "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=2 | 1,Widget,1,Alice | 2,Widget,2,Bob",
	"grouped/left/ord":                             "cols=[p:STRING k:INT64 id:INT64] rows=2 | Widget,1,1 | Widget,2,2",
	"grouped/left/qual":                            "cols=[k:INT64] rows=2 | 1 | 2",
	"grouped/left/star":                            "cols=[k:INT64 p:STRING id:INT64 customer:STRING total:FLOAT64] rows=2 | 1,Widget,1,Alice,150 | 2,Widget,2,Bob,200",
	"grouped/right/distinct":                       "cols=[k:INT64 p:STRING id:INT64] rows=2 | 1,Widget,1 | 2,Widget,2",
	"grouped/right/group":                          "cols=[k:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"grouped/right/list":                           "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=2 | 1,Widget,1,Alice | 2,Widget,2,Bob",
	"grouped/right/ord":                            "cols=[p:STRING k:INT64 id:INT64] rows=2 | Widget,1,1 | Widget,2,2",
	"grouped/right/qual":                           "cols=[k:INT64] rows=2 | 1 | 2",
	"grouped/right/star":                           "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=2 | 1,Alice,150,1,Widget | 2,Bob,200,2,Widget",
	"intersect-collide/both/distinct":              "cols=[id:INT64 customer:STRING id:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"intersect-collide/both/group":                 "cols=[id:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"intersect-collide/both/list":                  "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=2 | 1,Alice,1,Alice | 2,Bob,2,Bob",
	"intersect-collide/both/ord":                   "cols=[customer:STRING id:INT64 id:INT64] rows=2 | Alice,1,1 | Bob,2,2",
	"intersect-collide/both/qual":                  "cols=[id:INT64] rows=2 | 1 | 2",
	"intersect-collide/both/star":                  "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=2 | 1,Alice,1,Alice | 2,Bob,2,Bob",
	"intersect-collide/left/distinct":              "cols=[id:INT64 customer:STRING id:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"intersect-collide/left/group":                 "cols=[id:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"intersect-collide/left/list":                  "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=2 | 1,Alice,1,Alice | 2,Bob,2,Bob",
	"intersect-collide/left/ord":                   "cols=[customer:STRING id:INT64 id:INT64] rows=2 | Alice,1,1 | Bob,2,2",
	"intersect-collide/left/qual":                  "cols=[id:INT64] rows=2 | 1 | 2",
	"intersect-collide/left/star":                  "cols=[id:INT64 customer:STRING id:INT64 customer:STRING total:FLOAT64] rows=2 | 1,Alice,1,Alice,150 | 2,Bob,2,Bob,200",
	"intersect-collide/right/distinct":             "cols=[id:INT64 customer:STRING id:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"intersect-collide/right/group":                "cols=[id:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"intersect-collide/right/list":                 "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=2 | 1,Alice,1,Alice | 2,Bob,2,Bob",
	"intersect-collide/right/ord":                  "cols=[customer:STRING id:INT64 id:INT64] rows=2 | Alice,1,1 | Bob,2,2",
	"intersect-collide/right/qual":                 "cols=[id:INT64] rows=2 | 1 | 2",
	"intersect-collide/right/star":                 "cols=[id:INT64 customer:STRING total:FLOAT64 id:INT64 customer:STRING] rows=2 | 1,Alice,150,1,Alice | 2,Bob,200,2,Bob",
	"intersect/both/distinct":                      "cols=[k:INT64 p:STRING k:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"intersect/both/group":                         "cols=[k:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"intersect/both/list":                          "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=2 | 1,Alice,1,Alice | 2,Bob,2,Bob",
	"intersect/both/ord":                           "cols=[p:STRING k:INT64 k:INT64] rows=2 | Alice,1,1 | Bob,2,2",
	"intersect/both/qual":                          "cols=[k:INT64] rows=2 | 1 | 2",
	"intersect/both/star":                          "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=2 | 1,Alice,1,Alice | 2,Bob,2,Bob",
	"intersect/left/distinct":                      "cols=[k:INT64 p:STRING id:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"intersect/left/group":                         "cols=[k:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"intersect/left/list":                          "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=2 | 1,Alice,1,Alice | 2,Bob,2,Bob",
	"intersect/left/ord":                           "cols=[p:STRING k:INT64 id:INT64] rows=2 | Alice,1,1 | Bob,2,2",
	"intersect/left/qual":                          "cols=[k:INT64] rows=2 | 1 | 2",
	"intersect/left/star":                          "cols=[k:INT64 p:STRING id:INT64 customer:STRING total:FLOAT64] rows=2 | 1,Alice,1,Alice,150 | 2,Bob,2,Bob,200",
	"intersect/right/distinct":                     "cols=[k:INT64 p:STRING id:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"intersect/right/group":                        "cols=[k:INT64 n:INT64] rows=2 | 1,1 | 2,1",
	"intersect/right/list":                         "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=2 | 1,Alice,1,Alice | 2,Bob,2,Bob",
	"intersect/right/ord":                          "cols=[p:STRING k:INT64 id:INT64] rows=2 | Alice,1,1 | Bob,2,2",
	"intersect/right/qual":                         "cols=[k:INT64] rows=2 | 1 | 2",
	"intersect/right/star":                         "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=2 | 1,Alice,150,1,Alice | 2,Bob,200,2,Bob",
	"issue/1095":                                   "cols=[product:INT64 id:INT64] rows=9 | 1,1 | 1,1 | 1,2 | 1,2 | 1,3 | 1,3 | 2,1 | 2,2 | 2,3",
	"issue/1095-ctl-no-collision":                  "cols=[n:INT64 id:INT64] rows=9 | 1,1 | 1,1 | 1,2 | 1,2 | 1,3 | 1,3 | 2,1 | 2,2 | 2,3",
	"issue/1095-desc":                              "cols=[product:INT64 id:INT64] rows=9 | 2,1 | 2,2 | 2,3 | 1,1 | 1,1 | 1,2 | 1,2 | 1,3 | 1,3",
	"issue/1096-depth2":                            "cols=[p:STRING n:INT64 id:INT64 customer:STRING total:FLOAT64] rows=9 | Doohickey,1,1,Alice,150 | Doohickey,1,2,Bob,200 | Doohickey,1,3,Carol,0 | Gadget,1,1,Alice,150 | Gadget,1,2,Bob,200 | Gadget,1,3,Carol,0 | Widget,2,1,Alice,150 | Widget,2,2,Bob,200 | Widget,2,3,Carol,0",
	"issue/1096-depth3":                            "cols=[p:STRING n:INT64 id:INT64 customer:STRING total:FLOAT64] rows=9 | Doohickey,1,1,Alice,150 | Doohickey,1,2,Bob,200 | Doohickey,1,3,Carol,0 | Gadget,1,1,Alice,150 | Gadget,1,2,Bob,200 | Gadget,1,3,Carol,0 | Widget,2,1,Alice,150 | Widget,2,2,Bob,200 | Widget,2,3,Carol,0",
	"issue/1096-rename":                            "cols=[pp:STRING nn:INT64 id:INT64 customer:STRING total:FLOAT64] rows=9 | Doohickey,1,1,Alice,150 | Doohickey,1,2,Bob,200 | Doohickey,1,3,Carol,0 | Gadget,1,1,Alice,150 | Gadget,1,2,Bob,200 | Gadget,1,3,Carol,0 | Widget,2,1,Alice,150 | Widget,2,2,Bob,200 | Widget,2,3,Carol,0",
	"issue/1099":                                   "cols=[id:INT64 customer:STRING c:STRING k:INT64] rows=2 | 1,Alice,Alice,1 | 2,Bob,Bob,2",
	"issue/1099-block-first":                       "cols=[id:INT64 customer:STRING c:STRING k:INT64] rows=2 | 1,Alice,Alice,1 | 2,Bob,Bob,2",
	"issue/1099-boundary-in-outer":                 "cols=[c:INT64] rows=1 | 0",
	"issue/1099-boundary-not-in":                   "cols=[c:INT64] rows=1 | 3",
	"issue/1099-boundary-not-in-outer":             "cols=[c:INT64] rows=1 | 0",
	"issue/1099-ctl-plain-arm":                     "cols=[id:INT64 customer:STRING c:STRING k:INT64] rows=3 | 1,Alice,Alice,1 | 2,Bob,Bob,2 | 3,Carol,Carol,3",
	"issue/1099-no-distinct":                       "cols=[id:INT64 customer:STRING c:STRING k:INT64] rows=4 | 1,Alice,Alice,1 | 1,Alice,Alice,1 | 2,Bob,Bob,2 | 2,Bob,Bob,2",
	"issue/1102":                                   "cols=[id:INT64] rows=4 | 1 | 1 | 2 | 2",
	"issue/1102-all":                               "cols=[id:INT64] rows=8 | 1 | 1 | 1 | 1 | 2 | 2 | 2 | 2",
	"issue/1102-both-sides":                        "cols=[id:INT64 id:INT64] rows=4 | 1,1 | 1,2 | 2,3 | 2,4",
	"issue/1102-ctl-renamed":                       "cols=[kk:INT64] rows=4 | 1 | 1 | 2 | 2",
	"issue/b1-ctl-inner-joinbody":                  "cols=[id:INT64 k:INT64] rows=4 | 1,1 | 1,1 | 2,2 | 2,2",
	"issue/b1-ctl-left-grouped":                    "cols=[id:INT64 k:INT64] rows=3 | 1,1 | 2,2 | 3,NULL",
	"issue/b1-ctl-left-joinbody-barekey":           "cols=[total:FLOAT64 k:FLOAT64] rows=3 | 0,NULL | 150,NULL | 200,NULL",
	"issue/b1-ctl-left-joinbody-preserved":         "cols=[k:INT64 id:INT64] rows=4 | 1,1 | 1,1 | 2,2 | 2,2",
	"issue/b1-ctl-left-plain":                      "cols=[id:INT64 k:INT64] rows=3 | 1,1 | 2,2 | 3,3",
	"issue/b1-ctl-left-setop":                      "cols=[id:INT64 k:INT64] rows=3 | 1,1 | 2,2 | 3,3",
	"issue/b1-full-joinbody":                       "cols=[id:INT64 k:INT64] rows=5 | 1,1 | 1,1 | 2,2 | 2,2 | 3,NULL",
	"issue/b1-left-joinbody":                       "cols=[id:INT64 k:INT64] rows=5 | 1,1 | 1,1 | 2,2 | 2,2 | 3,NULL",
	"issue/b1-left-joinbody-distinct":              "cols=[id:INT64 k:INT64] rows=3 | 1,1 | 2,2 | 3,NULL",
	"issue/b1-left-joinbody-star":                  "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64] rows=5 | 1,Alice,150,1 | 1,Alice,150,1 | 2,Bob,200,2 | 2,Bob,200,2 | 3,Carol,0,NULL",
	"issue/b1-left-joinbody-two-cols":              "cols=[id:INT64 k:INT64 c:STRING] rows=5 | 1,1,Alice | 1,1,Alice | 2,2,Bob | 2,2,Bob | 3,NULL,NULL",
	"issue/b1-right-joinbody":                      "cols=[id:INT64 k:INT64] rows=5 | 1,1 | 1,1 | 2,2 | 2,2 | 3,NULL",
	"issue/r1n1-in-a":                              "cols=[a:INT64 b:INT64] rows=4 | 1,1 | 1,2 | 2,3 | 2,4",
	"issue/r1n1-plainjoin-distinct":                "cols=[a:INT64 b:INT64 id:INT64] rows=4 | 1,1,1 | 1,2,1 | 2,3,2 | 2,4,2",
	"issue/r1n1-plainjoin-nosub":                   "cols=[a:INT64 b:INT64 id:INT64] rows=4 | 1,1,1 | 1,2,1 | 2,3,2 | 2,4,2",
	"issue/r1n1-plainjoin-nosub-rev":               "cols=[a:INT64 b:INT64 id:INT64] rows=4 | 1,1,1 | 1,2,1 | 2,3,2 | 2,4,2",
	"joinbody-collide/both/distinct":               "cols=[id:INT64 customer:STRING id:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"joinbody-collide/both/group":                  "cols=[id:INT64 n:INT64] rows=2 | 1,4 | 2,4",
	"joinbody-collide/both/list":                   "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=8 | 1,Alice,1,Alice | 1,Alice,1,Alice | 1,Alice,1,Alice | 1,Alice,1,Alice | 2,Bob,2,Bob | 2,Bob,2,Bob | 2,Bob,2,Bob | 2,Bob,2,Bob",
	"joinbody-collide/both/ord":                    "cols=[customer:STRING id:INT64 id:INT64] rows=8 | Alice,1,1 | Alice,1,1 | Alice,1,1 | Alice,1,1 | Bob,2,2 | Bob,2,2 | Bob,2,2 | Bob,2,2",
	"joinbody-collide/both/qual":                   "cols=[id:INT64] rows=8 | 1 | 1 | 1 | 1 | 2 | 2 | 2 | 2",
	"joinbody-collide/both/star":                   "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=8 | 1,Alice,1,Alice | 1,Alice,1,Alice | 1,Alice,1,Alice | 1,Alice,1,Alice | 2,Bob,2,Bob | 2,Bob,2,Bob | 2,Bob,2,Bob | 2,Bob,2,Bob",
	"joinbody-collide/left/distinct":               "cols=[id:INT64 customer:STRING id:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"joinbody-collide/left/group":                  "cols=[id:INT64 n:INT64] rows=2 | 1,2 | 2,2",
	"joinbody-collide/left/list":                   "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=4 | 1,Alice,1,Alice | 1,Alice,1,Alice | 2,Bob,2,Bob | 2,Bob,2,Bob",
	"joinbody-collide/left/ord":                    "cols=[customer:STRING id:INT64 id:INT64] rows=4 | Alice,1,1 | Alice,1,1 | Bob,2,2 | Bob,2,2",
	"joinbody-collide/left/qual":                   "cols=[id:INT64] rows=4 | 1 | 1 | 2 | 2",
	"joinbody-collide/left/star":                   "cols=[id:INT64 customer:STRING id:INT64 customer:STRING total:FLOAT64] rows=4 | 1,Alice,1,Alice,150 | 1,Alice,1,Alice,150 | 2,Bob,2,Bob,200 | 2,Bob,2,Bob,200",
	"joinbody-collide/right/distinct":              "cols=[id:INT64 customer:STRING id:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"joinbody-collide/right/group":                 "cols=[id:INT64 n:INT64] rows=2 | 1,2 | 2,2",
	"joinbody-collide/right/list":                  "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=4 | 1,Alice,1,Alice | 1,Alice,1,Alice | 2,Bob,2,Bob | 2,Bob,2,Bob",
	"joinbody-collide/right/ord":                   "cols=[customer:STRING id:INT64 id:INT64] rows=4 | Alice,1,1 | Alice,1,1 | Bob,2,2 | Bob,2,2",
	"joinbody-collide/right/qual":                  "cols=[id:INT64] rows=4 | 1 | 1 | 2 | 2",
	"joinbody-collide/right/star":                  "cols=[id:INT64 customer:STRING total:FLOAT64 id:INT64 customer:STRING] rows=4 | 1,Alice,150,1,Alice | 1,Alice,150,1,Alice | 2,Bob,200,2,Bob | 2,Bob,200,2,Bob",
	"joinbody/both/distinct":                       "cols=[k:INT64 p:STRING k:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"joinbody/both/group":                          "cols=[k:INT64 n:INT64] rows=2 | 1,4 | 2,4",
	"joinbody/both/list":                           "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=8 | 1,Alice,1,Alice | 1,Alice,1,Alice | 1,Alice,1,Alice | 1,Alice,1,Alice | 2,Bob,2,Bob | 2,Bob,2,Bob | 2,Bob,2,Bob | 2,Bob,2,Bob",
	"joinbody/both/ord":                            "cols=[p:STRING k:INT64 k:INT64] rows=8 | Alice,1,1 | Alice,1,1 | Alice,1,1 | Alice,1,1 | Bob,2,2 | Bob,2,2 | Bob,2,2 | Bob,2,2",
	"joinbody/both/qual":                           "cols=[k:INT64] rows=8 | 1 | 1 | 1 | 1 | 2 | 2 | 2 | 2",
	"joinbody/both/star":                           "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=8 | 1,Alice,1,Alice | 1,Alice,1,Alice | 1,Alice,1,Alice | 1,Alice,1,Alice | 2,Bob,2,Bob | 2,Bob,2,Bob | 2,Bob,2,Bob | 2,Bob,2,Bob",
	"joinbody/left/distinct":                       "cols=[k:INT64 p:STRING id:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"joinbody/left/group":                          "cols=[k:INT64 n:INT64] rows=2 | 1,2 | 2,2",
	"joinbody/left/list":                           "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=4 | 1,Alice,1,Alice | 1,Alice,1,Alice | 2,Bob,2,Bob | 2,Bob,2,Bob",
	"joinbody/left/ord":                            "cols=[p:STRING k:INT64 id:INT64] rows=4 | Alice,1,1 | Alice,1,1 | Bob,2,2 | Bob,2,2",
	"joinbody/left/qual":                           "cols=[k:INT64] rows=4 | 1 | 1 | 2 | 2",
	"joinbody/left/star":                           "cols=[k:INT64 p:STRING id:INT64 customer:STRING total:FLOAT64] rows=4 | 1,Alice,1,Alice,150 | 1,Alice,1,Alice,150 | 2,Bob,2,Bob,200 | 2,Bob,2,Bob,200",
	"joinbody/right/distinct":                      "cols=[k:INT64 p:STRING id:INT64] rows=2 | 1,Alice,1 | 2,Bob,2",
	"joinbody/right/group":                         "cols=[k:INT64 n:INT64] rows=2 | 1,2 | 2,2",
	"joinbody/right/list":                          "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=4 | 1,Alice,1,Alice | 1,Alice,1,Alice | 2,Bob,2,Bob | 2,Bob,2,Bob",
	"joinbody/right/ord":                           "cols=[p:STRING k:INT64 id:INT64] rows=4 | Alice,1,1 | Alice,1,1 | Bob,2,2 | Bob,2,2",
	"joinbody/right/qual":                          "cols=[k:INT64] rows=4 | 1 | 1 | 2 | 2",
	"joinbody/right/star":                          "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=4 | 1,Alice,150,1,Alice | 1,Alice,150,1,Alice | 2,Bob,200,2,Bob | 2,Bob,200,2,Bob",
	"nested-rename-collide/both/distinct":          "cols=[id:INT64 customer:STRING id:INT64] rows=4 | 1,Gadget,1 | 1,Widget,1 | 2,Doohickey,2 | 2,Widget,2",
	"nested-rename-collide/both/group":             "cols=[id:INT64 n:INT64] rows=2 | 1,4 | 2,4",
	"nested-rename-collide/both/list":              "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=8 | 1,Gadget,1,Gadget | 1,Gadget,1,Widget | 1,Widget,1,Gadget | 1,Widget,1,Widget | 2,Doohickey,2,Doohickey | 2,Doohickey,2,Widget | 2,Widget,2,Doohickey | 2,Widget,2,Widget",
	"nested-rename-collide/both/ord":               "cols=[customer:STRING id:INT64 id:INT64] rows=8 | Doohickey,2,2 | Doohickey,2,2 | Gadget,1,1 | Gadget,1,1 | Widget,1,1 | Widget,1,1 | Widget,2,2 | Widget,2,2",
	"nested-rename-collide/both/qual":              "cols=[id:INT64] rows=8 | 1 | 1 | 1 | 1 | 2 | 2 | 2 | 2",
	"nested-rename-collide/both/star":              "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=8 | 1,Gadget,1,Gadget | 1,Gadget,1,Widget | 1,Widget,1,Gadget | 1,Widget,1,Widget | 2,Doohickey,2,Doohickey | 2,Doohickey,2,Widget | 2,Widget,2,Doohickey | 2,Widget,2,Widget",
	"nested-rename-collide/left/distinct":          "cols=[id:INT64 customer:STRING id:INT64] rows=4 | 1,Gadget,1 | 1,Widget,1 | 2,Doohickey,2 | 2,Widget,2",
	"nested-rename-collide/left/group":             "cols=[id:INT64 n:INT64] rows=2 | 1,2 | 2,2",
	"nested-rename-collide/left/list":              "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=4 | 1,Gadget,1,Alice | 1,Widget,1,Alice | 2,Doohickey,2,Bob | 2,Widget,2,Bob",
	"nested-rename-collide/left/ord":               "cols=[customer:STRING id:INT64 id:INT64] rows=4 | Doohickey,2,2 | Gadget,1,1 | Widget,1,1 | Widget,2,2",
	"nested-rename-collide/left/qual":              "cols=[id:INT64] rows=4 | 1 | 1 | 2 | 2",
	"nested-rename-collide/left/star":              "cols=[id:INT64 customer:STRING id:INT64 customer:STRING total:FLOAT64] rows=4 | 1,Gadget,1,Alice,150 | 1,Widget,1,Alice,150 | 2,Doohickey,2,Bob,200 | 2,Widget,2,Bob,200",
	"nested-rename-collide/right/distinct":         "cols=[id:INT64 customer:STRING id:INT64] rows=4 | 1,Gadget,1 | 1,Widget,1 | 2,Doohickey,2 | 2,Widget,2",
	"nested-rename-collide/right/group":            "cols=[id:INT64 n:INT64] rows=2 | 1,2 | 2,2",
	"nested-rename-collide/right/list":             "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=4 | 1,Gadget,1,Alice | 1,Widget,1,Alice | 2,Doohickey,2,Bob | 2,Widget,2,Bob",
	"nested-rename-collide/right/ord":              "cols=[customer:STRING id:INT64 id:INT64] rows=4 | Doohickey,2,2 | Gadget,1,1 | Widget,1,1 | Widget,2,2",
	"nested-rename-collide/right/qual":             "cols=[id:INT64] rows=4 | 1 | 1 | 2 | 2",
	"nested-rename-collide/right/star":             "cols=[id:INT64 customer:STRING total:FLOAT64 id:INT64 customer:STRING] rows=4 | 1,Alice,150,1,Gadget | 1,Alice,150,1,Widget | 2,Bob,200,2,Doohickey | 2,Bob,200,2,Widget",
	"nested-rename-grouped-collide/both/distinct":  "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Doohickey,1 | 1,Gadget,1 | 2,Widget,2",
	"nested-rename-grouped-collide/both/group":     "cols=[id:INT64 n:INT64] rows=2 | 1,4 | 2,1",
	"nested-rename-grouped-collide/both/list":      "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=5 | 1,Doohickey,1,Doohickey | 1,Doohickey,1,Gadget | 1,Gadget,1,Doohickey | 1,Gadget,1,Gadget | 2,Widget,2,Widget",
	"nested-rename-grouped-collide/both/ord":       "cols=[customer:STRING id:INT64 id:INT64] rows=5 | Doohickey,1,1 | Doohickey,1,1 | Gadget,1,1 | Gadget,1,1 | Widget,2,2",
	"nested-rename-grouped-collide/both/qual":      "cols=[id:INT64] rows=5 | 1 | 1 | 1 | 1 | 2",
	"nested-rename-grouped-collide/both/star":      "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=5 | 1,Doohickey,1,Doohickey | 1,Doohickey,1,Gadget | 1,Gadget,1,Doohickey | 1,Gadget,1,Gadget | 2,Widget,2,Widget",
	"nested-rename-grouped-collide/left/distinct":  "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Doohickey,1 | 1,Gadget,1 | 2,Widget,2",
	"nested-rename-grouped-collide/left/group":     "cols=[id:INT64 n:INT64] rows=2 | 1,2 | 2,1",
	"nested-rename-grouped-collide/left/list":      "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=3 | 1,Doohickey,1,Alice | 1,Gadget,1,Alice | 2,Widget,2,Bob",
	"nested-rename-grouped-collide/left/ord":       "cols=[customer:STRING id:INT64 id:INT64] rows=3 | Doohickey,1,1 | Gadget,1,1 | Widget,2,2",
	"nested-rename-grouped-collide/left/qual":      "cols=[id:INT64] rows=3 | 1 | 1 | 2",
	"nested-rename-grouped-collide/left/star":      "cols=[id:INT64 customer:STRING id:INT64 customer:STRING total:FLOAT64] rows=3 | 1,Doohickey,1,Alice,150 | 1,Gadget,1,Alice,150 | 2,Widget,2,Bob,200",
	"nested-rename-grouped-collide/right/distinct": "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Doohickey,1 | 1,Gadget,1 | 2,Widget,2",
	"nested-rename-grouped-collide/right/group":    "cols=[id:INT64 n:INT64] rows=2 | 1,2 | 2,1",
	"nested-rename-grouped-collide/right/list":     "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=3 | 1,Doohickey,1,Alice | 1,Gadget,1,Alice | 2,Widget,2,Bob",
	"nested-rename-grouped-collide/right/ord":      "cols=[customer:STRING id:INT64 id:INT64] rows=3 | Doohickey,1,1 | Gadget,1,1 | Widget,2,2",
	"nested-rename-grouped-collide/right/qual":     "cols=[id:INT64] rows=3 | 1 | 1 | 2",
	"nested-rename-grouped-collide/right/star":     "cols=[id:INT64 customer:STRING total:FLOAT64 id:INT64 customer:STRING] rows=3 | 1,Alice,150,1,Doohickey | 1,Alice,150,1,Gadget | 2,Bob,200,2,Widget",
	"nested-rename-grouped/both/distinct":          "cols=[k:INT64 p:STRING k:INT64] rows=3 | 1,Doohickey,1 | 1,Gadget,1 | 2,Widget,2",
	"nested-rename-grouped/both/group":             "cols=[k:INT64 n:INT64] rows=2 | 1,4 | 2,1",
	"nested-rename-grouped/both/list":              "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=5 | 1,Doohickey,1,Doohickey | 1,Doohickey,1,Gadget | 1,Gadget,1,Doohickey | 1,Gadget,1,Gadget | 2,Widget,2,Widget",
	"nested-rename-grouped/both/ord":               "cols=[p:STRING k:INT64 k:INT64] rows=5 | Doohickey,1,1 | Doohickey,1,1 | Gadget,1,1 | Gadget,1,1 | Widget,2,2",
	"nested-rename-grouped/both/qual":              "cols=[k:INT64] rows=5 | 1 | 1 | 1 | 1 | 2",
	"nested-rename-grouped/both/star":              "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=5 | 1,Doohickey,1,Doohickey | 1,Doohickey,1,Gadget | 1,Gadget,1,Doohickey | 1,Gadget,1,Gadget | 2,Widget,2,Widget",
	"nested-rename-grouped/left/distinct":          "cols=[k:INT64 p:STRING id:INT64] rows=3 | 1,Doohickey,1 | 1,Gadget,1 | 2,Widget,2",
	"nested-rename-grouped/left/group":             "cols=[k:INT64 n:INT64] rows=2 | 1,2 | 2,1",
	"nested-rename-grouped/left/list":              "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=3 | 1,Doohickey,1,Alice | 1,Gadget,1,Alice | 2,Widget,2,Bob",
	"nested-rename-grouped/left/ord":               "cols=[p:STRING k:INT64 id:INT64] rows=3 | Doohickey,1,1 | Gadget,1,1 | Widget,2,2",
	"nested-rename-grouped/left/qual":              "cols=[k:INT64] rows=3 | 1 | 1 | 2",
	"nested-rename-grouped/left/star":              "cols=[k:INT64 p:STRING id:INT64 customer:STRING total:FLOAT64] rows=3 | 1,Doohickey,1,Alice,150 | 1,Gadget,1,Alice,150 | 2,Widget,2,Bob,200",
	"nested-rename-grouped/right/distinct":         "cols=[k:INT64 p:STRING id:INT64] rows=3 | 1,Doohickey,1 | 1,Gadget,1 | 2,Widget,2",
	"nested-rename-grouped/right/group":            "cols=[k:INT64 n:INT64] rows=2 | 1,2 | 2,1",
	"nested-rename-grouped/right/list":             "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=3 | 1,Doohickey,1,Alice | 1,Gadget,1,Alice | 2,Widget,2,Bob",
	"nested-rename-grouped/right/ord":              "cols=[p:STRING k:INT64 id:INT64] rows=3 | Doohickey,1,1 | Gadget,1,1 | Widget,2,2",
	"nested-rename-grouped/right/qual":             "cols=[k:INT64] rows=3 | 1 | 1 | 2",
	"nested-rename-grouped/right/star":             "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=3 | 1,Alice,150,1,Doohickey | 1,Alice,150,1,Gadget | 2,Bob,200,2,Widget",
	"nested-rename/both/distinct":                  "cols=[k:INT64 p:STRING k:INT64] rows=4 | 1,Gadget,1 | 1,Widget,1 | 2,Doohickey,2 | 2,Widget,2",
	"nested-rename/both/group":                     "cols=[k:INT64 n:INT64] rows=2 | 1,4 | 2,4",
	"nested-rename/both/list":                      "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=8 | 1,Gadget,1,Gadget | 1,Gadget,1,Widget | 1,Widget,1,Gadget | 1,Widget,1,Widget | 2,Doohickey,2,Doohickey | 2,Doohickey,2,Widget | 2,Widget,2,Doohickey | 2,Widget,2,Widget",
	"nested-rename/both/ord":                       "cols=[p:STRING k:INT64 k:INT64] rows=8 | Doohickey,2,2 | Doohickey,2,2 | Gadget,1,1 | Gadget,1,1 | Widget,1,1 | Widget,1,1 | Widget,2,2 | Widget,2,2",
	"nested-rename/both/qual":                      "cols=[k:INT64] rows=8 | 1 | 1 | 1 | 1 | 2 | 2 | 2 | 2",
	"nested-rename/both/star":                      "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=8 | 1,Gadget,1,Gadget | 1,Gadget,1,Widget | 1,Widget,1,Gadget | 1,Widget,1,Widget | 2,Doohickey,2,Doohickey | 2,Doohickey,2,Widget | 2,Widget,2,Doohickey | 2,Widget,2,Widget",
	"nested-rename/left/distinct":                  "cols=[k:INT64 p:STRING id:INT64] rows=4 | 1,Gadget,1 | 1,Widget,1 | 2,Doohickey,2 | 2,Widget,2",
	"nested-rename/left/group":                     "cols=[k:INT64 n:INT64] rows=2 | 1,2 | 2,2",
	"nested-rename/left/list":                      "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=4 | 1,Gadget,1,Alice | 1,Widget,1,Alice | 2,Doohickey,2,Bob | 2,Widget,2,Bob",
	"nested-rename/left/ord":                       "cols=[p:STRING k:INT64 id:INT64] rows=4 | Doohickey,2,2 | Gadget,1,1 | Widget,1,1 | Widget,2,2",
	"nested-rename/left/qual":                      "cols=[k:INT64] rows=4 | 1 | 1 | 2 | 2",
	"nested-rename/left/star":                      "cols=[k:INT64 p:STRING id:INT64 customer:STRING total:FLOAT64] rows=4 | 1,Gadget,1,Alice,150 | 1,Widget,1,Alice,150 | 2,Doohickey,2,Bob,200 | 2,Widget,2,Bob,200",
	"nested-rename/right/distinct":                 "cols=[k:INT64 p:STRING id:INT64] rows=4 | 1,Gadget,1 | 1,Widget,1 | 2,Doohickey,2 | 2,Widget,2",
	"nested-rename/right/group":                    "cols=[k:INT64 n:INT64] rows=2 | 1,2 | 2,2",
	"nested-rename/right/list":                     "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=4 | 1,Gadget,1,Alice | 1,Widget,1,Alice | 2,Doohickey,2,Bob | 2,Widget,2,Bob",
	"nested-rename/right/ord":                      "cols=[p:STRING k:INT64 id:INT64] rows=4 | Doohickey,2,2 | Gadget,1,1 | Widget,1,1 | Widget,2,2",
	"nested-rename/right/qual":                     "cols=[k:INT64] rows=4 | 1 | 1 | 2 | 2",
	"nested-rename/right/star":                     "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=4 | 1,Alice,150,1,Gadget | 1,Alice,150,1,Widget | 2,Bob,200,2,Doohickey | 2,Bob,200,2,Widget",
	"outer/full/grouped/distinct":                  "cols=[id:INT64 k:INT64] rows=3 | 1,1 | 2,2 | 3,NULL",
	"outer/full/grouped/list":                      "cols=[id:INT64 k:INT64 p:STRING] rows=3 | 1,1,Widget | 2,2,Widget | 3,NULL,NULL",
	"outer/full/grouped/star":                      "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=3 | 1,Alice,150,1,Widget | 2,Bob,200,2,Widget | 3,Carol,0,NULL,NULL",
	"outer/full/joinbody/distinct":                 "cols=[id:INT64 k:INT64] rows=3 | 1,1 | 2,2 | 3,NULL",
	"outer/full/joinbody/list":                     "cols=[id:INT64 k:INT64 p:STRING] rows=5 | 1,1,Alice | 1,1,Alice | 2,2,Bob | 2,2,Bob | 3,NULL,NULL",
	"outer/full/joinbody/star":                     "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=5 | 1,Alice,150,1,Alice | 1,Alice,150,1,Alice | 2,Bob,200,2,Bob | 2,Bob,200,2,Bob | 3,Carol,0,NULL,NULL",
	"outer/full/nested-rename/distinct":            "cols=[id:INT64 k:INT64] rows=3 | 1,1 | 2,2 | 3,NULL",
	"outer/full/nested-rename/list":                "cols=[id:INT64 k:INT64 p:STRING] rows=5 | 1,1,Gadget | 1,1,Widget | 2,2,Doohickey | 2,2,Widget | 3,NULL,NULL",
	"outer/full/nested-rename/star":                "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=5 | 1,Alice,150,1,Gadget | 1,Alice,150,1,Widget | 2,Bob,200,2,Doohickey | 2,Bob,200,2,Widget | 3,Carol,0,NULL,NULL",
	"outer/full/union/distinct":                    "cols=[id:INT64 k:INT64] rows=3 | 1,1 | 2,2 | 3,3",
	"outer/full/union/list":                        "cols=[id:INT64 k:INT64 p:STRING] rows=3 | 1,1,Alice | 2,2,Bob | 3,3,Carol",
	"outer/full/union/star":                        "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=3 | 1,Alice,150,1,Alice | 2,Bob,200,2,Bob | 3,Carol,0,3,Carol",
	"outer/left/grouped/distinct":                  "cols=[id:INT64 k:INT64] rows=3 | 1,1 | 2,2 | 3,NULL",
	"outer/left/grouped/list":                      "cols=[id:INT64 k:INT64 p:STRING] rows=3 | 1,1,Widget | 2,2,Widget | 3,NULL,NULL",
	"outer/left/grouped/star":                      "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=3 | 1,Alice,150,1,Widget | 2,Bob,200,2,Widget | 3,Carol,0,NULL,NULL",
	"outer/left/joinbody/distinct":                 "cols=[id:INT64 k:INT64] rows=3 | 1,1 | 2,2 | 3,NULL",
	"outer/left/joinbody/list":                     "cols=[id:INT64 k:INT64 p:STRING] rows=5 | 1,1,Alice | 1,1,Alice | 2,2,Bob | 2,2,Bob | 3,NULL,NULL",
	"outer/left/joinbody/star":                     "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=5 | 1,Alice,150,1,Alice | 1,Alice,150,1,Alice | 2,Bob,200,2,Bob | 2,Bob,200,2,Bob | 3,Carol,0,NULL,NULL",
	"outer/left/nested-rename/distinct":            "cols=[id:INT64 k:INT64] rows=3 | 1,1 | 2,2 | 3,NULL",
	"outer/left/nested-rename/list":                "cols=[id:INT64 k:INT64 p:STRING] rows=5 | 1,1,Gadget | 1,1,Widget | 2,2,Doohickey | 2,2,Widget | 3,NULL,NULL",
	"outer/left/nested-rename/star":                "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=5 | 1,Alice,150,1,Gadget | 1,Alice,150,1,Widget | 2,Bob,200,2,Doohickey | 2,Bob,200,2,Widget | 3,Carol,0,NULL,NULL",
	"outer/left/union/distinct":                    "cols=[id:INT64 k:INT64] rows=3 | 1,1 | 2,2 | 3,3",
	"outer/left/union/list":                        "cols=[id:INT64 k:INT64 p:STRING] rows=3 | 1,1,Alice | 2,2,Bob | 3,3,Carol",
	"outer/left/union/star":                        "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=3 | 1,Alice,150,1,Alice | 2,Bob,200,2,Bob | 3,Carol,0,3,Carol",
	"outer/right/grouped/distinct":                 "cols=[id:INT64 k:INT64] rows=3 | 1,1 | 2,2 | 3,NULL",
	"outer/right/grouped/list":                     "cols=[id:INT64 k:INT64 p:STRING] rows=3 | 1,1,Widget | 2,2,Widget | 3,NULL,NULL",
	"outer/right/grouped/star":                     "cols=[k:INT64 p:STRING id:INT64 customer:STRING total:FLOAT64] rows=3 | 1,Widget,1,Alice,150 | 2,Widget,2,Bob,200 | NULL,NULL,3,Carol,0",
	"outer/right/joinbody/distinct":                "cols=[id:INT64 k:INT64] rows=3 | 1,1 | 2,2 | 3,NULL",
	"outer/right/joinbody/list":                    "cols=[id:INT64 k:INT64 p:STRING] rows=5 | 1,1,Alice | 1,1,Alice | 2,2,Bob | 2,2,Bob | 3,NULL,NULL",
	"outer/right/joinbody/star":                    "cols=[k:INT64 p:STRING id:INT64 customer:STRING total:FLOAT64] rows=5 | 1,Alice,1,Alice,150 | 1,Alice,1,Alice,150 | 2,Bob,2,Bob,200 | 2,Bob,2,Bob,200 | NULL,NULL,3,Carol,0",
	"outer/right/nested-rename/distinct":           "cols=[id:INT64 k:INT64] rows=3 | 1,1 | 2,2 | 3,NULL",
	"outer/right/nested-rename/list":               "cols=[id:INT64 k:INT64 p:STRING] rows=5 | 1,1,Gadget | 1,1,Widget | 2,2,Doohickey | 2,2,Widget | 3,NULL,NULL",
	"outer/right/nested-rename/star":               "cols=[k:INT64 p:STRING id:INT64 customer:STRING total:FLOAT64] rows=5 | 1,Gadget,1,Alice,150 | 1,Widget,1,Alice,150 | 2,Doohickey,2,Bob,200 | 2,Widget,2,Bob,200 | NULL,NULL,3,Carol,0",
	"outer/right/union/distinct":                   "cols=[id:INT64 k:INT64] rows=3 | 1,1 | 2,2 | 3,3",
	"outer/right/union/list":                       "cols=[id:INT64 k:INT64 p:STRING] rows=3 | 1,1,Alice | 2,2,Bob | 3,3,Carol",
	"outer/right/union/star":                       "cols=[k:INT64 p:STRING id:INT64 customer:STRING total:FLOAT64] rows=3 | 1,Alice,1,Alice,150 | 2,Bob,2,Bob,200 | 3,Carol,3,Carol,0",
	"plain-collide/both/distinct":                  "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"plain-collide/both/group":                     "cols=[id:INT64 n:INT64] rows=3 | 1,1 | 2,1 | 3,1",
	"plain-collide/both/list":                      "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=3 | 1,Alice,1,Alice | 2,Bob,2,Bob | 3,Carol,3,Carol",
	"plain-collide/both/ord":                       "cols=[customer:STRING id:INT64 id:INT64] rows=3 | Alice,1,1 | Bob,2,2 | Carol,3,3",
	"plain-collide/both/qual":                      "cols=[id:INT64] rows=3 | 1 | 2 | 3",
	"plain-collide/both/star":                      "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=3 | 1,Alice,1,Alice | 2,Bob,2,Bob | 3,Carol,3,Carol",
	"plain-collide/left/distinct":                  "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"plain-collide/left/group":                     "cols=[id:INT64 n:INT64] rows=3 | 1,1 | 2,1 | 3,1",
	"plain-collide/left/list":                      "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=3 | 1,Alice,1,Alice | 2,Bob,2,Bob | 3,Carol,3,Carol",
	"plain-collide/left/ord":                       "cols=[customer:STRING id:INT64 id:INT64] rows=3 | Alice,1,1 | Bob,2,2 | Carol,3,3",
	"plain-collide/left/qual":                      "cols=[id:INT64] rows=3 | 1 | 2 | 3",
	"plain-collide/left/star":                      "cols=[id:INT64 customer:STRING id:INT64 customer:STRING total:FLOAT64] rows=3 | 1,Alice,1,Alice,150 | 2,Bob,2,Bob,200 | 3,Carol,3,Carol,0",
	"plain-collide/right/distinct":                 "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"plain-collide/right/group":                    "cols=[id:INT64 n:INT64] rows=3 | 1,1 | 2,1 | 3,1",
	"plain-collide/right/list":                     "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=3 | 1,Alice,1,Alice | 2,Bob,2,Bob | 3,Carol,3,Carol",
	"plain-collide/right/ord":                      "cols=[customer:STRING id:INT64 id:INT64] rows=3 | Alice,1,1 | Bob,2,2 | Carol,3,3",
	"plain-collide/right/qual":                     "cols=[id:INT64] rows=3 | 1 | 2 | 3",
	"plain-collide/right/star":                     "cols=[id:INT64 customer:STRING total:FLOAT64 id:INT64 customer:STRING] rows=3 | 1,Alice,150,1,Alice | 2,Bob,200,2,Bob | 3,Carol,0,3,Carol",
	"plain/both/distinct":                          "cols=[k:INT64 p:STRING k:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"plain/both/group":                             "cols=[k:INT64 n:INT64] rows=3 | 1,1 | 2,1 | 3,1",
	"plain/both/list":                              "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=3 | 1,Alice,1,Alice | 2,Bob,2,Bob | 3,Carol,3,Carol",
	"plain/both/ord":                               "cols=[p:STRING k:INT64 k:INT64] rows=3 | Alice,1,1 | Bob,2,2 | Carol,3,3",
	"plain/both/qual":                              "cols=[k:INT64] rows=3 | 1 | 2 | 3",
	"plain/both/star":                              "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=3 | 1,Alice,1,Alice | 2,Bob,2,Bob | 3,Carol,3,Carol",
	"plain/left/distinct":                          "cols=[k:INT64 p:STRING id:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"plain/left/group":                             "cols=[k:INT64 n:INT64] rows=3 | 1,1 | 2,1 | 3,1",
	"plain/left/list":                              "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=3 | 1,Alice,1,Alice | 2,Bob,2,Bob | 3,Carol,3,Carol",
	"plain/left/ord":                               "cols=[p:STRING k:INT64 id:INT64] rows=3 | Alice,1,1 | Bob,2,2 | Carol,3,3",
	"plain/left/qual":                              "cols=[k:INT64] rows=3 | 1 | 2 | 3",
	"plain/left/star":                              "cols=[k:INT64 p:STRING id:INT64 customer:STRING total:FLOAT64] rows=3 | 1,Alice,1,Alice,150 | 2,Bob,2,Bob,200 | 3,Carol,3,Carol,0",
	"plain/right/distinct":                         "cols=[k:INT64 p:STRING id:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"plain/right/group":                            "cols=[k:INT64 n:INT64] rows=3 | 1,1 | 2,1 | 3,1",
	"plain/right/list":                             "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=3 | 1,Alice,1,Alice | 2,Bob,2,Bob | 3,Carol,3,Carol",
	"plain/right/ord":                              "cols=[p:STRING k:INT64 id:INT64] rows=3 | Alice,1,1 | Bob,2,2 | Carol,3,3",
	"plain/right/qual":                             "cols=[k:INT64] rows=3 | 1 | 2 | 3",
	"plain/right/star":                             "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=3 | 1,Alice,150,1,Alice | 2,Bob,200,2,Bob | 3,Carol,0,3,Carol",
	"sortkey-collide/both/distinct":                "cols=[id:INT64 customer:STRING id:INT64] rows=4 | 1,Gadget,1 | 1,Widget,1 | 2,Doohickey,2 | 2,Widget,2",
	"sortkey-collide/both/group":                   "cols=[id:INT64 n:INT64] rows=2 | 1,4 | 2,4",
	"sortkey-collide/both/list":                    "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=8 | 1,Gadget,1,Gadget | 1,Gadget,1,Widget | 1,Widget,1,Gadget | 1,Widget,1,Widget | 2,Doohickey,2,Doohickey | 2,Doohickey,2,Widget | 2,Widget,2,Doohickey | 2,Widget,2,Widget",
	"sortkey-collide/both/ord":                     "cols=[customer:STRING id:INT64 id:INT64] rows=8 | Doohickey,2,2 | Doohickey,2,2 | Gadget,1,1 | Gadget,1,1 | Widget,1,1 | Widget,1,1 | Widget,2,2 | Widget,2,2",
	"sortkey-collide/both/qual":                    "cols=[id:INT64] rows=8 | 1 | 1 | 1 | 1 | 2 | 2 | 2 | 2",
	"sortkey-collide/both/star":                    "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=8 | 1,Gadget,1,Gadget | 1,Gadget,1,Widget | 1,Widget,1,Gadget | 1,Widget,1,Widget | 2,Doohickey,2,Doohickey | 2,Doohickey,2,Widget | 2,Widget,2,Doohickey | 2,Widget,2,Widget",
	"sortkey-collide/left/distinct":                "cols=[id:INT64 customer:STRING id:INT64] rows=4 | 1,Gadget,1 | 1,Widget,1 | 2,Doohickey,2 | 2,Widget,2",
	"sortkey-collide/left/group":                   "cols=[id:INT64 n:INT64] rows=2 | 1,2 | 2,2",
	"sortkey-collide/left/list":                    "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=4 | 1,Gadget,1,Alice | 1,Widget,1,Alice | 2,Doohickey,2,Bob | 2,Widget,2,Bob",
	"sortkey-collide/left/ord":                     "cols=[customer:STRING id:INT64 id:INT64] rows=4 | Doohickey,2,2 | Gadget,1,1 | Widget,1,1 | Widget,2,2",
	"sortkey-collide/left/qual":                    "cols=[id:INT64] rows=4 | 1 | 1 | 2 | 2",
	"sortkey-collide/left/star":                    "cols=[id:INT64 customer:STRING id:INT64 customer:STRING total:FLOAT64] rows=4 | 1,Gadget,1,Alice,150 | 1,Widget,1,Alice,150 | 2,Doohickey,2,Bob,200 | 2,Widget,2,Bob,200",
	"sortkey-collide/right/distinct":               "cols=[id:INT64 customer:STRING id:INT64] rows=4 | 1,Gadget,1 | 1,Widget,1 | 2,Doohickey,2 | 2,Widget,2",
	"sortkey-collide/right/group":                  "cols=[id:INT64 n:INT64] rows=2 | 1,2 | 2,2",
	"sortkey-collide/right/list":                   "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=4 | 1,Gadget,1,Alice | 1,Widget,1,Alice | 2,Doohickey,2,Bob | 2,Widget,2,Bob",
	"sortkey-collide/right/ord":                    "cols=[customer:STRING id:INT64 id:INT64] rows=4 | Doohickey,2,2 | Gadget,1,1 | Widget,1,1 | Widget,2,2",
	"sortkey-collide/right/qual":                   "cols=[id:INT64] rows=4 | 1 | 1 | 2 | 2",
	"sortkey-collide/right/star":                   "cols=[id:INT64 customer:STRING total:FLOAT64 id:INT64 customer:STRING] rows=4 | 1,Alice,150,1,Gadget | 1,Alice,150,1,Widget | 2,Bob,200,2,Doohickey | 2,Bob,200,2,Widget",
	"sortkey-limit-collide/both/distinct":          "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Gadget,1 | 1,Widget,1 | 2,Widget,2",
	"sortkey-limit-collide/both/group":             "cols=[id:INT64 n:INT64] rows=2 | 1,4 | 2,1",
	"sortkey-limit-collide/both/list":              "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=5 | 1,Gadget,1,Gadget | 1,Gadget,1,Widget | 1,Widget,1,Gadget | 1,Widget,1,Widget | 2,Widget,2,Widget",
	"sortkey-limit-collide/both/ord":               "cols=[customer:STRING id:INT64 id:INT64] rows=5 | Gadget,1,1 | Gadget,1,1 | Widget,1,1 | Widget,1,1 | Widget,2,2",
	"sortkey-limit-collide/both/qual":              "cols=[id:INT64] rows=5 | 1 | 1 | 1 | 1 | 2",
	"sortkey-limit-collide/both/star":              "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=5 | 1,Gadget,1,Gadget | 1,Gadget,1,Widget | 1,Widget,1,Gadget | 1,Widget,1,Widget | 2,Widget,2,Widget",
	"sortkey-limit-collide/left/distinct":          "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Gadget,1 | 1,Widget,1 | 2,Widget,2",
	"sortkey-limit-collide/left/group":             "cols=[id:INT64 n:INT64] rows=2 | 1,2 | 2,1",
	"sortkey-limit-collide/left/list":              "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=3 | 1,Gadget,1,Alice | 1,Widget,1,Alice | 2,Widget,2,Bob",
	"sortkey-limit-collide/left/ord":               "cols=[customer:STRING id:INT64 id:INT64] rows=3 | Gadget,1,1 | Widget,1,1 | Widget,2,2",
	"sortkey-limit-collide/left/qual":              "cols=[id:INT64] rows=3 | 1 | 1 | 2",
	"sortkey-limit-collide/left/star":              "cols=[id:INT64 customer:STRING id:INT64 customer:STRING total:FLOAT64] rows=3 | 1,Gadget,1,Alice,150 | 1,Widget,1,Alice,150 | 2,Widget,2,Bob,200",
	"sortkey-limit-collide/right/distinct":         "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Gadget,1 | 1,Widget,1 | 2,Widget,2",
	"sortkey-limit-collide/right/group":            "cols=[id:INT64 n:INT64] rows=2 | 1,2 | 2,1",
	"sortkey-limit-collide/right/list":             "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=3 | 1,Gadget,1,Alice | 1,Widget,1,Alice | 2,Widget,2,Bob",
	"sortkey-limit-collide/right/ord":              "cols=[customer:STRING id:INT64 id:INT64] rows=3 | Gadget,1,1 | Widget,1,1 | Widget,2,2",
	"sortkey-limit-collide/right/qual":             "cols=[id:INT64] rows=3 | 1 | 1 | 2",
	"sortkey-limit-collide/right/star":             "cols=[id:INT64 customer:STRING total:FLOAT64 id:INT64 customer:STRING] rows=3 | 1,Alice,150,1,Gadget | 1,Alice,150,1,Widget | 2,Bob,200,2,Widget",
	"sortkey-limit/both/distinct":                  "cols=[k:INT64 p:STRING k:INT64] rows=3 | 1,Gadget,1 | 1,Widget,1 | 2,Widget,2",
	"sortkey-limit/both/group":                     "cols=[k:INT64 n:INT64] rows=2 | 1,4 | 2,1",
	"sortkey-limit/both/list":                      "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=5 | 1,Gadget,1,Gadget | 1,Gadget,1,Widget | 1,Widget,1,Gadget | 1,Widget,1,Widget | 2,Widget,2,Widget",
	"sortkey-limit/both/ord":                       "cols=[p:STRING k:INT64 k:INT64] rows=5 | Gadget,1,1 | Gadget,1,1 | Widget,1,1 | Widget,1,1 | Widget,2,2",
	"sortkey-limit/both/qual":                      "cols=[k:INT64] rows=5 | 1 | 1 | 1 | 1 | 2",
	"sortkey-limit/both/star":                      "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=5 | 1,Gadget,1,Gadget | 1,Gadget,1,Widget | 1,Widget,1,Gadget | 1,Widget,1,Widget | 2,Widget,2,Widget",
	"sortkey-limit/left/distinct":                  "cols=[k:INT64 p:STRING id:INT64] rows=3 | 1,Gadget,1 | 1,Widget,1 | 2,Widget,2",
	"sortkey-limit/left/group":                     "cols=[k:INT64 n:INT64] rows=2 | 1,2 | 2,1",
	"sortkey-limit/left/list":                      "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=3 | 1,Gadget,1,Alice | 1,Widget,1,Alice | 2,Widget,2,Bob",
	"sortkey-limit/left/ord":                       "cols=[p:STRING k:INT64 id:INT64] rows=3 | Gadget,1,1 | Widget,1,1 | Widget,2,2",
	"sortkey-limit/left/qual":                      "cols=[k:INT64] rows=3 | 1 | 1 | 2",
	"sortkey-limit/left/star":                      "cols=[k:INT64 p:STRING id:INT64 customer:STRING total:FLOAT64] rows=3 | 1,Gadget,1,Alice,150 | 1,Widget,1,Alice,150 | 2,Widget,2,Bob,200",
	"sortkey-limit/right/distinct":                 "cols=[k:INT64 p:STRING id:INT64] rows=3 | 1,Gadget,1 | 1,Widget,1 | 2,Widget,2",
	"sortkey-limit/right/group":                    "cols=[k:INT64 n:INT64] rows=2 | 1,2 | 2,1",
	"sortkey-limit/right/list":                     "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=3 | 1,Gadget,1,Alice | 1,Widget,1,Alice | 2,Widget,2,Bob",
	"sortkey-limit/right/ord":                      "cols=[p:STRING k:INT64 id:INT64] rows=3 | Gadget,1,1 | Widget,1,1 | Widget,2,2",
	"sortkey-limit/right/qual":                     "cols=[k:INT64] rows=3 | 1 | 1 | 2",
	"sortkey-limit/right/star":                     "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=3 | 1,Alice,150,1,Gadget | 1,Alice,150,1,Widget | 2,Bob,200,2,Widget",
	"sortkey/both/distinct":                        "cols=[k:INT64 p:STRING k:INT64] rows=4 | 1,Gadget,1 | 1,Widget,1 | 2,Doohickey,2 | 2,Widget,2",
	"sortkey/both/group":                           "cols=[k:INT64 n:INT64] rows=2 | 1,4 | 2,4",
	"sortkey/both/list":                            "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=8 | 1,Gadget,1,Gadget | 1,Gadget,1,Widget | 1,Widget,1,Gadget | 1,Widget,1,Widget | 2,Doohickey,2,Doohickey | 2,Doohickey,2,Widget | 2,Widget,2,Doohickey | 2,Widget,2,Widget",
	"sortkey/both/ord":                             "cols=[p:STRING k:INT64 k:INT64] rows=8 | Doohickey,2,2 | Doohickey,2,2 | Gadget,1,1 | Gadget,1,1 | Widget,1,1 | Widget,1,1 | Widget,2,2 | Widget,2,2",
	"sortkey/both/qual":                            "cols=[k:INT64] rows=8 | 1 | 1 | 1 | 1 | 2 | 2 | 2 | 2",
	"sortkey/both/star":                            "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=8 | 1,Gadget,1,Gadget | 1,Gadget,1,Widget | 1,Widget,1,Gadget | 1,Widget,1,Widget | 2,Doohickey,2,Doohickey | 2,Doohickey,2,Widget | 2,Widget,2,Doohickey | 2,Widget,2,Widget",
	"sortkey/left/distinct":                        "cols=[k:INT64 p:STRING id:INT64] rows=4 | 1,Gadget,1 | 1,Widget,1 | 2,Doohickey,2 | 2,Widget,2",
	"sortkey/left/group":                           "cols=[k:INT64 n:INT64] rows=2 | 1,2 | 2,2",
	"sortkey/left/list":                            "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=4 | 1,Gadget,1,Alice | 1,Widget,1,Alice | 2,Doohickey,2,Bob | 2,Widget,2,Bob",
	"sortkey/left/ord":                             "cols=[p:STRING k:INT64 id:INT64] rows=4 | Doohickey,2,2 | Gadget,1,1 | Widget,1,1 | Widget,2,2",
	"sortkey/left/qual":                            "cols=[k:INT64] rows=4 | 1 | 1 | 2 | 2",
	"sortkey/left/star":                            "cols=[k:INT64 p:STRING id:INT64 customer:STRING total:FLOAT64] rows=4 | 1,Gadget,1,Alice,150 | 1,Widget,1,Alice,150 | 2,Doohickey,2,Bob,200 | 2,Widget,2,Bob,200",
	"sortkey/right/distinct":                       "cols=[k:INT64 p:STRING id:INT64] rows=4 | 1,Gadget,1 | 1,Widget,1 | 2,Doohickey,2 | 2,Widget,2",
	"sortkey/right/group":                          "cols=[k:INT64 n:INT64] rows=2 | 1,2 | 2,2",
	"sortkey/right/list":                           "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=4 | 1,Gadget,1,Alice | 1,Widget,1,Alice | 2,Doohickey,2,Bob | 2,Widget,2,Bob",
	"sortkey/right/ord":                            "cols=[p:STRING k:INT64 id:INT64] rows=4 | Doohickey,2,2 | Gadget,1,1 | Widget,1,1 | Widget,2,2",
	"sortkey/right/qual":                           "cols=[k:INT64] rows=4 | 1 | 1 | 2 | 2",
	"sortkey/right/star":                           "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=4 | 1,Alice,150,1,Gadget | 1,Alice,150,1,Widget | 2,Bob,200,2,Doohickey | 2,Bob,200,2,Widget",
	"union-all-collide/both/distinct":              "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"union-all-collide/both/group":                 "cols=[id:INT64 n:INT64] rows=3 | 1,4 | 2,4 | 3,4",
	"union-all-collide/both/list":                  "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=12 | 1,Alice,1,Alice | 1,Alice,1,Alice | 1,Alice,1,Alice | 1,Alice,1,Alice | 2,Bob,2,Bob | 2,Bob,2,Bob | 2,Bob,2,Bob | 2,Bob,2,Bob | 3,Carol,3,Carol | 3,Carol,3,Carol | 3,Carol,3,Carol | 3,Carol,3,Carol",
	"union-all-collide/both/ord":                   "cols=[customer:STRING id:INT64 id:INT64] rows=12 | Alice,1,1 | Alice,1,1 | Alice,1,1 | Alice,1,1 | Bob,2,2 | Bob,2,2 | Bob,2,2 | Bob,2,2 | Carol,3,3 | Carol,3,3 | Carol,3,3 | Carol,3,3",
	"union-all-collide/both/qual":                  "cols=[id:INT64] rows=12 | 1 | 1 | 1 | 1 | 2 | 2 | 2 | 2 | 3 | 3 | 3 | 3",
	"union-all-collide/both/star":                  "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=12 | 1,Alice,1,Alice | 1,Alice,1,Alice | 1,Alice,1,Alice | 1,Alice,1,Alice | 2,Bob,2,Bob | 2,Bob,2,Bob | 2,Bob,2,Bob | 2,Bob,2,Bob | 3,Carol,3,Carol | 3,Carol,3,Carol | 3,Carol,3,Carol | 3,Carol,3,Carol",
	"union-all-collide/left/distinct":              "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"union-all-collide/left/group":                 "cols=[id:INT64 n:INT64] rows=3 | 1,2 | 2,2 | 3,2",
	"union-all-collide/left/list":                  "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=6 | 1,Alice,1,Alice | 1,Alice,1,Alice | 2,Bob,2,Bob | 2,Bob,2,Bob | 3,Carol,3,Carol | 3,Carol,3,Carol",
	"union-all-collide/left/ord":                   "cols=[customer:STRING id:INT64 id:INT64] rows=6 | Alice,1,1 | Alice,1,1 | Bob,2,2 | Bob,2,2 | Carol,3,3 | Carol,3,3",
	"union-all-collide/left/qual":                  "cols=[id:INT64] rows=6 | 1 | 1 | 2 | 2 | 3 | 3",
	"union-all-collide/left/star":                  "cols=[id:INT64 customer:STRING id:INT64 customer:STRING total:FLOAT64] rows=6 | 1,Alice,1,Alice,150 | 1,Alice,1,Alice,150 | 2,Bob,2,Bob,200 | 2,Bob,2,Bob,200 | 3,Carol,3,Carol,0 | 3,Carol,3,Carol,0",
	"union-all-collide/right/distinct":             "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"union-all-collide/right/group":                "cols=[id:INT64 n:INT64] rows=3 | 1,2 | 2,2 | 3,2",
	"union-all-collide/right/list":                 "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=6 | 1,Alice,1,Alice | 1,Alice,1,Alice | 2,Bob,2,Bob | 2,Bob,2,Bob | 3,Carol,3,Carol | 3,Carol,3,Carol",
	"union-all-collide/right/ord":                  "cols=[customer:STRING id:INT64 id:INT64] rows=6 | Alice,1,1 | Alice,1,1 | Bob,2,2 | Bob,2,2 | Carol,3,3 | Carol,3,3",
	"union-all-collide/right/qual":                 "cols=[id:INT64] rows=6 | 1 | 1 | 2 | 2 | 3 | 3",
	"union-all-collide/right/star":                 "cols=[id:INT64 customer:STRING total:FLOAT64 id:INT64 customer:STRING] rows=6 | 1,Alice,150,1,Alice | 1,Alice,150,1,Alice | 2,Bob,200,2,Bob | 2,Bob,200,2,Bob | 3,Carol,0,3,Carol | 3,Carol,0,3,Carol",
	"union-all/both/distinct":                      "cols=[k:INT64 p:STRING k:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"union-all/both/group":                         "cols=[k:INT64 n:INT64] rows=3 | 1,4 | 2,4 | 3,4",
	"union-all/both/list":                          "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=12 | 1,Alice,1,Alice | 1,Alice,1,Alice | 1,Alice,1,Alice | 1,Alice,1,Alice | 2,Bob,2,Bob | 2,Bob,2,Bob | 2,Bob,2,Bob | 2,Bob,2,Bob | 3,Carol,3,Carol | 3,Carol,3,Carol | 3,Carol,3,Carol | 3,Carol,3,Carol",
	"union-all/both/ord":                           "cols=[p:STRING k:INT64 k:INT64] rows=12 | Alice,1,1 | Alice,1,1 | Alice,1,1 | Alice,1,1 | Bob,2,2 | Bob,2,2 | Bob,2,2 | Bob,2,2 | Carol,3,3 | Carol,3,3 | Carol,3,3 | Carol,3,3",
	"union-all/both/qual":                          "cols=[k:INT64] rows=12 | 1 | 1 | 1 | 1 | 2 | 2 | 2 | 2 | 3 | 3 | 3 | 3",
	"union-all/both/star":                          "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=12 | 1,Alice,1,Alice | 1,Alice,1,Alice | 1,Alice,1,Alice | 1,Alice,1,Alice | 2,Bob,2,Bob | 2,Bob,2,Bob | 2,Bob,2,Bob | 2,Bob,2,Bob | 3,Carol,3,Carol | 3,Carol,3,Carol | 3,Carol,3,Carol | 3,Carol,3,Carol",
	"union-all/left/distinct":                      "cols=[k:INT64 p:STRING id:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"union-all/left/group":                         "cols=[k:INT64 n:INT64] rows=3 | 1,2 | 2,2 | 3,2",
	"union-all/left/list":                          "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=6 | 1,Alice,1,Alice | 1,Alice,1,Alice | 2,Bob,2,Bob | 2,Bob,2,Bob | 3,Carol,3,Carol | 3,Carol,3,Carol",
	"union-all/left/ord":                           "cols=[p:STRING k:INT64 id:INT64] rows=6 | Alice,1,1 | Alice,1,1 | Bob,2,2 | Bob,2,2 | Carol,3,3 | Carol,3,3",
	"union-all/left/qual":                          "cols=[k:INT64] rows=6 | 1 | 1 | 2 | 2 | 3 | 3",
	"union-all/left/star":                          "cols=[k:INT64 p:STRING id:INT64 customer:STRING total:FLOAT64] rows=6 | 1,Alice,1,Alice,150 | 1,Alice,1,Alice,150 | 2,Bob,2,Bob,200 | 2,Bob,2,Bob,200 | 3,Carol,3,Carol,0 | 3,Carol,3,Carol,0",
	"union-all/right/distinct":                     "cols=[k:INT64 p:STRING id:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"union-all/right/group":                        "cols=[k:INT64 n:INT64] rows=3 | 1,2 | 2,2 | 3,2",
	"union-all/right/list":                         "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=6 | 1,Alice,1,Alice | 1,Alice,1,Alice | 2,Bob,2,Bob | 2,Bob,2,Bob | 3,Carol,3,Carol | 3,Carol,3,Carol",
	"union-all/right/ord":                          "cols=[p:STRING k:INT64 id:INT64] rows=6 | Alice,1,1 | Alice,1,1 | Bob,2,2 | Bob,2,2 | Carol,3,3 | Carol,3,3",
	"union-all/right/qual":                         "cols=[k:INT64] rows=6 | 1 | 1 | 2 | 2 | 3 | 3",
	"union-all/right/star":                         "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=6 | 1,Alice,150,1,Alice | 1,Alice,150,1,Alice | 2,Bob,200,2,Bob | 2,Bob,200,2,Bob | 3,Carol,0,3,Carol | 3,Carol,0,3,Carol",
	"union-collide/both/distinct":                  "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"union-collide/both/group":                     "cols=[id:INT64 n:INT64] rows=3 | 1,1 | 2,1 | 3,1",
	"union-collide/both/list":                      "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=3 | 1,Alice,1,Alice | 2,Bob,2,Bob | 3,Carol,3,Carol",
	"union-collide/both/ord":                       "cols=[customer:STRING id:INT64 id:INT64] rows=3 | Alice,1,1 | Bob,2,2 | Carol,3,3",
	"union-collide/both/qual":                      "cols=[id:INT64] rows=3 | 1 | 2 | 3",
	"union-collide/both/star":                      "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=3 | 1,Alice,1,Alice | 2,Bob,2,Bob | 3,Carol,3,Carol",
	"union-collide/left/distinct":                  "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"union-collide/left/group":                     "cols=[id:INT64 n:INT64] rows=3 | 1,1 | 2,1 | 3,1",
	"union-collide/left/list":                      "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=3 | 1,Alice,1,Alice | 2,Bob,2,Bob | 3,Carol,3,Carol",
	"union-collide/left/ord":                       "cols=[customer:STRING id:INT64 id:INT64] rows=3 | Alice,1,1 | Bob,2,2 | Carol,3,3",
	"union-collide/left/qual":                      "cols=[id:INT64] rows=3 | 1 | 2 | 3",
	"union-collide/left/star":                      "cols=[id:INT64 customer:STRING id:INT64 customer:STRING total:FLOAT64] rows=3 | 1,Alice,1,Alice,150 | 2,Bob,2,Bob,200 | 3,Carol,3,Carol,0",
	"union-collide/right/distinct":                 "cols=[id:INT64 customer:STRING id:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"union-collide/right/group":                    "cols=[id:INT64 n:INT64] rows=3 | 1,1 | 2,1 | 3,1",
	"union-collide/right/list":                     "cols=[id:INT64 customer:STRING id:INT64 customer:STRING] rows=3 | 1,Alice,1,Alice | 2,Bob,2,Bob | 3,Carol,3,Carol",
	"union-collide/right/ord":                      "cols=[customer:STRING id:INT64 id:INT64] rows=3 | Alice,1,1 | Bob,2,2 | Carol,3,3",
	"union-collide/right/qual":                     "cols=[id:INT64] rows=3 | 1 | 2 | 3",
	"union-collide/right/star":                     "cols=[id:INT64 customer:STRING total:FLOAT64 id:INT64 customer:STRING] rows=3 | 1,Alice,150,1,Alice | 2,Bob,200,2,Bob | 3,Carol,0,3,Carol",
	"union/both/distinct":                          "cols=[k:INT64 p:STRING k:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"union/both/group":                             "cols=[k:INT64 n:INT64] rows=3 | 1,1 | 2,1 | 3,1",
	"union/both/list":                              "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=3 | 1,Alice,1,Alice | 2,Bob,2,Bob | 3,Carol,3,Carol",
	"union/both/ord":                               "cols=[p:STRING k:INT64 k:INT64] rows=3 | Alice,1,1 | Bob,2,2 | Carol,3,3",
	"union/both/qual":                              "cols=[k:INT64] rows=3 | 1 | 2 | 3",
	"union/both/star":                              "cols=[k:INT64 p:STRING k:INT64 p:STRING] rows=3 | 1,Alice,1,Alice | 2,Bob,2,Bob | 3,Carol,3,Carol",
	"union/left/distinct":                          "cols=[k:INT64 p:STRING id:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"union/left/group":                             "cols=[k:INT64 n:INT64] rows=3 | 1,1 | 2,1 | 3,1",
	"union/left/list":                              "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=3 | 1,Alice,1,Alice | 2,Bob,2,Bob | 3,Carol,3,Carol",
	"union/left/ord":                               "cols=[p:STRING k:INT64 id:INT64] rows=3 | Alice,1,1 | Bob,2,2 | Carol,3,3",
	"union/left/qual":                              "cols=[k:INT64] rows=3 | 1 | 2 | 3",
	"union/left/star":                              "cols=[k:INT64 p:STRING id:INT64 customer:STRING total:FLOAT64] rows=3 | 1,Alice,1,Alice,150 | 2,Bob,2,Bob,200 | 3,Carol,3,Carol,0",
	"union/right/distinct":                         "cols=[k:INT64 p:STRING id:INT64] rows=3 | 1,Alice,1 | 2,Bob,2 | 3,Carol,3",
	"union/right/group":                            "cols=[k:INT64 n:INT64] rows=3 | 1,1 | 2,1 | 3,1",
	"union/right/list":                             "cols=[k:INT64 p:STRING id:INT64 customer:STRING] rows=3 | 1,Alice,1,Alice | 2,Bob,2,Bob | 3,Carol,3,Carol",
	"union/right/ord":                              "cols=[p:STRING k:INT64 id:INT64] rows=3 | Alice,1,1 | Bob,2,2 | Carol,3,3",
	"union/right/qual":                             "cols=[k:INT64] rows=3 | 1 | 2 | 3",
	"union/right/star":                             "cols=[id:INT64 customer:STRING total:FLOAT64 k:INT64 p:STRING] rows=3 | 1,Alice,150,1,Alice | 2,Bob,200,2,Bob | 3,Carol,0,3,Carol",
}
