// SPDX-License-Identifier: AGPL-3.0-only

package coordinator

import (
	"context"
	"strings"
	"testing"
	"time"
)

// A DECORRELATED SUBQUERY KEEPS EVERY OUTER REFERENCE, WHEREVER IN ITS BODY
// IT IS WRITTEN — #1232, #1104, on FIVE ARMS.
//
// The corpus is arc_dc_decorrelation_cases_test.go: {IN, NOT IN, = ANY,
// <> ALL, EXISTS, NOT EXISTS, a scalar subquery in WHERE, a scalar subquery in
// the SELECT list} × {the fifty places an outer reference can sit in a body —
// its WHERE with an inner column, its WHERE naming only the outer row, a JOIN's
// ON, a LEFT/RIGHT JOIN's ON, a comma join's WHERE, the HAVING, the SELECT
// list, a nested derived table, a nested subquery, two references in two
// places} × {equality, inequality, a function over the outer column, a CAST,
// IS DISTINCT FROM, a NULL-yielding predicate, an outer row with NULL in the
// referenced column, an empty inner, duplicate inner keys} × {an enclosing
// query that is ONE relation, and one that is a JOIN whose two arms both
// publish `id`}.
//
// Every want is live PostgreSQL 17.11 (postgres:17-alpine, --locale=C, the
// dc_out / dc_in / dc_side / dc_nul rows arc_dc_decorrelation_fixture_test.go
// writes, plus lat_ord / lat_item for the two issues' own shapes), measured at
// 6b9c7acf before a line changed and re-measured at the tip. What the fixes
// moved, in cells of this table, on the single arm:
//
//	#1232  the body's JOIN ON was never read. The ON is where the outer
//	       reference of `o.id IN (SELECT b.order_id FROM lat_item b JOIN
//	       lat_item c ON c.id = b.id AND o.total > b.amount)` lives, so the
//	       body's join was built with `o.total` in a condition whose scope
//	       does not contain `o`: ZERO rows for PostgreSQL's two, silently.
//	       109 wrong cells at base; an INNER join's ON conjunct is now a
//	       WHERE conjunct and an outer join's ON declines the rewrite.
//	#1104  a condition naming ONLY the outer row was added to the build
//	       side's filter with its qualifier STRIPPED (IN) or dropped outright
//	       (EXISTS). It now gates the OUTER rows, which is what PostgreSQL
//	       does with it, and the negated operators — for which that is not a
//	       conjunction — decline and re-run per outer row.
//
// 193 of this table's 776 cells changed. None of the other 583 moved, and no
// cell that agreed with PostgreSQL at base is refused at the tip.
//
// The three PINS below are boundaries, not answers, and each names what
// closes it. A pin that starts agreeing FAILS: PostgreSQL's row set for the
// cell is already recorded above it.
const (
	// An outer reference inside a DERIVED TABLE in the body's FROM. This
	// engine plans a derived table's body as its own query block, where the
	// enclosing relation names nothing — the standing 0A000-class gap
	// (#614/#1045, ADR-0021 §1p), refused with its two workarounds named.
	// Pre-existing at 6b9c7acf on all five arms.
	dcCorrelatedDerivedRefusal = "from an enclosing query is not supported"
	// An outer reference written WITHOUT a qualifier. The logical classifier
	// has no catalog for the body's own relations, so it cannot tell the
	// enclosing `total` from an inner column of the same name — and TPC-H
	// Q02's official spelling writes every correlated key unqualified, with
	// both names in the enclosing map, so reading an unqualified name as
	// outer would change Q02's row set. The unqualified spelling therefore
	// keeps the disposition it had: it goes to the build side, where the
	// column is absent and the failure is LOUD. Closing it is a catalog at
	// the classifier, not a spelling rule (ADR-0021 §1r). Pre-existing at
	// 6b9c7acf.
	dcBareOuterRefRefusal = "does not exist in the input schema"
	// An aggregate inside a subquery whose ARGUMENT names only the enclosing
	// query. PostgreSQL puts such an aggregate at the ENCLOSING query's
	// level and then raises 42803 for these statements; this engine refuses
	// by name (ADR-0021 §1g). Both refuse, which is the assertion.
	dcOuterAggregateRefusal = "names only the enclosing query"
)

// dcPostgresRowSets is the oracle: one recorded row set per cell, measured on
// live PostgreSQL 17.11 over the fixture this package writes.
var dcPostgresRowSets = map[string]string{
	"IN/noJoin/whereEq":                      "rows=2 1 | 2",
	"NOTIN/noJoin/whereEq":                   "rows=3 3 | 9 | NULL",
	"EXISTS/noJoin/whereEq":                  "rows=2 1 | 2",
	"NOTEXISTS/noJoin/whereEq":               "rows=3 3 | 9 | NULL",
	"ANY/noJoin/whereEq":                     "rows=2 1 | 2",
	"ALL/noJoin/whereEq":                     "rows=3 3 | 9 | NULL",
	"SCALARWHERE/noJoin/whereEq":             "rows=2 1 | 2",
	"IN/noJoin/whereNe":                      "rows=2 1 | 2",
	"NOTIN/noJoin/whereNe":                   "rows=3 3 | 9 | NULL",
	"EXISTS/noJoin/whereNe":                  "rows=4 1 | 2 | 3 | 9",
	"NOTEXISTS/noJoin/whereNe":               "rows=1 NULL",
	"ANY/noJoin/whereNe":                     "rows=2 1 | 2",
	"ALL/noJoin/whereNe":                     "rows=3 3 | 9 | NULL",
	"SCALARWHERE/noJoin/whereNe":             "rows=1 2",
	"IN/noJoin/whereFn":                      "rows=2 1 | 2",
	"NOTIN/noJoin/whereFn":                   "rows=3 3 | 9 | NULL",
	"EXISTS/noJoin/whereFn":                  "rows=2 1 | 2",
	"NOTEXISTS/noJoin/whereFn":               "rows=3 3 | 9 | NULL",
	"ANY/noJoin/whereFn":                     "rows=2 1 | 2",
	"ALL/noJoin/whereFn":                     "rows=3 3 | 9 | NULL",
	"SCALARWHERE/noJoin/whereFn":             "rows=2 1 | 2",
	"IN/noJoin/whereCast":                    "rows=2 1 | 2",
	"NOTIN/noJoin/whereCast":                 "rows=3 3 | 9 | NULL",
	"EXISTS/noJoin/whereCast":                "rows=2 1 | 2",
	"NOTEXISTS/noJoin/whereCast":             "rows=3 3 | 9 | NULL",
	"ANY/noJoin/whereCast":                   "rows=2 1 | 2",
	"ALL/noJoin/whereCast":                   "rows=3 3 | 9 | NULL",
	"SCALARWHERE/noJoin/whereCast":           "rows=2 1 | 2",
	"IN/noJoin/whereIDF":                     "rows=0 ",
	"NOTIN/noJoin/whereIDF":                  "rows=4 1 | 2 | 3 | 9",
	"EXISTS/noJoin/whereIDF":                 "rows=5 1 | 2 | 3 | 9 | NULL",
	"NOTEXISTS/noJoin/whereIDF":              "rows=0 ",
	"ANY/noJoin/whereIDF":                    "rows=0 ",
	"ALL/noJoin/whereIDF":                    "rows=4 1 | 2 | 3 | 9",
	"SCALARWHERE/noJoin/whereIDF":            "rows=0 ",
	"IN/noJoin/whereOuterOnly":               "rows=1 2",
	"NOTIN/noJoin/whereOuterOnly":            "rows=3 1 | 3 | 9",
	"EXISTS/noJoin/whereOuterOnly":           "rows=2 2 | NULL",
	"NOTEXISTS/noJoin/whereOuterOnly":        "rows=3 1 | 3 | 9",
	"ANY/noJoin/whereOuterOnly":              "rows=1 2",
	"ALL/noJoin/whereOuterOnly":              "rows=3 1 | 3 | 9",
	"SCALARWHERE/noJoin/whereOuterOnly":      "rows=0 ",
	"IN/noJoin/whereOuterEq":                 "rows=2 1 | 2",
	"NOTIN/noJoin/whereOuterEq":              "rows=3 3 | 9 | NULL",
	"EXISTS/noJoin/whereOuterEq":             "rows=2 1 | 2",
	"NOTEXISTS/noJoin/whereOuterEq":          "rows=3 3 | 9 | NULL",
	"ANY/noJoin/whereOuterEq":                "rows=2 1 | 2",
	"ALL/noJoin/whereOuterEq":                "rows=3 3 | 9 | NULL",
	"SCALARWHERE/noJoin/whereOuterEq":        "rows=0 ",
	"IN/noJoin/whereOuterNull":               "rows=0 ",
	"NOTIN/noJoin/whereOuterNull":            "rows=4 1 | 2 | 3 | 9",
	"EXISTS/noJoin/whereOuterNull":           "rows=1 NULL",
	"NOTEXISTS/noJoin/whereOuterNull":        "rows=4 1 | 2 | 3 | 9",
	"ANY/noJoin/whereOuterNull":              "rows=0 ",
	"ALL/noJoin/whereOuterNull":              "rows=4 1 | 2 | 3 | 9",
	"SCALARWHERE/noJoin/whereOuterNull":      "rows=0 ",
	"IN/noJoin/whereOuterFn":                 "rows=1 2",
	"NOTIN/noJoin/whereOuterFn":              "rows=3 1 | 3 | 9",
	"EXISTS/noJoin/whereOuterFn":             "rows=2 2 | NULL",
	"NOTEXISTS/noJoin/whereOuterFn":          "rows=3 1 | 3 | 9",
	"ANY/noJoin/whereOuterFn":                "rows=1 2",
	"ALL/noJoin/whereOuterFn":                "rows=3 1 | 3 | 9",
	"SCALARWHERE/noJoin/whereOuterFn":        "rows=0 ",
	"IN/noJoin/whereBoth":                    "rows=1 2",
	"NOTIN/noJoin/whereBoth":                 "rows=4 1 | 3 | 9 | NULL",
	"EXISTS/noJoin/whereBoth":                "rows=1 2",
	"NOTEXISTS/noJoin/whereBoth":             "rows=4 1 | 3 | 9 | NULL",
	"ANY/noJoin/whereBoth":                   "rows=1 2",
	"ALL/noJoin/whereBoth":                   "rows=4 1 | 3 | 9 | NULL",
	"SCALARWHERE/noJoin/whereBoth":           "rows=1 2",
	"IN/noJoin/whereEmpty":                   "rows=0 ",
	"NOTIN/noJoin/whereEmpty":                "rows=5 1 | 2 | 3 | 9 | NULL",
	"EXISTS/noJoin/whereEmpty":               "rows=0 ",
	"NOTEXISTS/noJoin/whereEmpty":            "rows=5 1 | 2 | 3 | 9 | NULL",
	"ANY/noJoin/whereEmpty":                  "rows=0 ",
	"ALL/noJoin/whereEmpty":                  "rows=5 1 | 2 | 3 | 9 | NULL",
	"SCALARWHERE/noJoin/whereEmpty":          "rows=0 ",
	"IN/noJoin/onEq":                         "rows=2 1 | 2",
	"NOTIN/noJoin/onEq":                      "rows=3 3 | 9 | NULL",
	"EXISTS/noJoin/onEq":                     "rows=2 1 | 2",
	"NOTEXISTS/noJoin/onEq":                  "rows=3 3 | 9 | NULL",
	"ANY/noJoin/onEq":                        "rows=2 1 | 2",
	"ALL/noJoin/onEq":                        "rows=3 3 | 9 | NULL",
	"SCALARWHERE/noJoin/onEq":                "rows=2 1 | 2",
	"IN/noJoin/onNe":                         "rows=1 1",
	"NOTIN/noJoin/onNe":                      "rows=3 2 | 3 | 9",
	"EXISTS/noJoin/onNe":                     "rows=3 1 | 2 | NULL",
	"NOTEXISTS/noJoin/onNe":                  "rows=2 3 | 9",
	"ANY/noJoin/onNe":                        "rows=1 1",
	"ALL/noJoin/onNe":                        "rows=3 2 | 3 | 9",
	"SCALARWHERE/noJoin/onNe":                "rows=1 1",
	"IN/noJoin/onFn":                         "rows=2 1 | 2",
	"NOTIN/noJoin/onFn":                      "rows=3 3 | 9 | NULL",
	"EXISTS/noJoin/onFn":                     "rows=2 1 | 2",
	"NOTEXISTS/noJoin/onFn":                  "rows=3 3 | 9 | NULL",
	"ANY/noJoin/onFn":                        "rows=2 1 | 2",
	"ALL/noJoin/onFn":                        "rows=3 3 | 9 | NULL",
	"SCALARWHERE/noJoin/onFn":                "rows=2 1 | 2",
	"IN/noJoin/onIDF":                        "rows=0 ",
	"NOTIN/noJoin/onIDF":                     "rows=4 1 | 2 | 3 | 9",
	"EXISTS/noJoin/onIDF":                    "rows=5 1 | 2 | 3 | 9 | NULL",
	"NOTEXISTS/noJoin/onIDF":                 "rows=0 ",
	"ANY/noJoin/onIDF":                       "rows=0 ",
	"ALL/noJoin/onIDF":                       "rows=4 1 | 2 | 3 | 9",
	"SCALARWHERE/noJoin/onIDF":               "rows=0 ",
	"IN/noJoin/onOuterOnly":                  "rows=1 2",
	"NOTIN/noJoin/onOuterOnly":               "rows=3 1 | 3 | 9",
	"EXISTS/noJoin/onOuterOnly":              "rows=2 2 | NULL",
	"NOTEXISTS/noJoin/onOuterOnly":           "rows=3 1 | 3 | 9",
	"ANY/noJoin/onOuterOnly":                 "rows=1 2",
	"ALL/noJoin/onOuterOnly":                 "rows=3 1 | 3 | 9",
	"SCALARWHERE/noJoin/onOuterOnly":         "rows=1 2",
	"IN/noJoin/onOuterNull":                  "rows=0 ",
	"NOTIN/noJoin/onOuterNull":               "rows=4 1 | 2 | 3 | 9",
	"EXISTS/noJoin/onOuterNull":              "rows=1 NULL",
	"NOTEXISTS/noJoin/onOuterNull":           "rows=4 1 | 2 | 3 | 9",
	"ANY/noJoin/onOuterNull":                 "rows=0 ",
	"ALL/noJoin/onOuterNull":                 "rows=4 1 | 2 | 3 | 9",
	"SCALARWHERE/noJoin/onOuterNull":         "rows=0 ",
	"IN/noJoin/onSelf":                       "rows=1 1",
	"NOTIN/noJoin/onSelf":                    "rows=3 2 | 3 | 9",
	"EXISTS/noJoin/onSelf":                   "rows=4 1 | 2 | 3 | NULL",
	"NOTEXISTS/noJoin/onSelf":                "rows=1 9",
	"ANY/noJoin/onSelf":                      "rows=1 1",
	"ALL/noJoin/onSelf":                      "rows=3 2 | 3 | 9",
	"SCALARWHERE/noJoin/onSelf":              "rows=0 ",
	"IN/noJoin/onWhereSplit":                 "rows=1 2",
	"NOTIN/noJoin/onWhereSplit":              "rows=4 1 | 3 | 9 | NULL",
	"EXISTS/noJoin/onWhereSplit":             "rows=1 2",
	"NOTEXISTS/noJoin/onWhereSplit":          "rows=4 1 | 3 | 9 | NULL",
	"ANY/noJoin/onWhereSplit":                "rows=1 2",
	"ALL/noJoin/onWhereSplit":                "rows=4 1 | 3 | 9 | NULL",
	"SCALARWHERE/noJoin/onWhereSplit":        "rows=1 2",
	"IN/noJoin/onLeftPad":                    "rows=0 ",
	"NOTIN/noJoin/onLeftPad":                 "rows=0 ",
	"EXISTS/noJoin/onLeftPad":                "rows=5 1 | 2 | 3 | 9 | NULL",
	"NOTEXISTS/noJoin/onLeftPad":             "rows=0 ",
	"ANY/noJoin/onLeftPad":                   "rows=0 ",
	"ALL/noJoin/onLeftPad":                   "rows=0 ",
	"SCALARWHERE/noJoin/onLeftPad":           "rows=0 ",
	"IN/noJoin/onLeftOuter":                  "rows=0 ",
	"NOTIN/noJoin/onLeftOuter":               "rows=0 ",
	"EXISTS/noJoin/onLeftOuter":              "rows=5 1 | 2 | 3 | 9 | NULL",
	"NOTEXISTS/noJoin/onLeftOuter":           "rows=0 ",
	"ANY/noJoin/onLeftOuter":                 "rows=0 ",
	"ALL/noJoin/onLeftOuter":                 "rows=0 ",
	"SCALARWHERE/noJoin/onLeftOuter":         "rows=0 ",
	"IN/noJoin/onLeftEq":                     "rows=0 ",
	"NOTIN/noJoin/onLeftEq":                  "rows=0 ",
	"EXISTS/noJoin/onLeftEq":                 "rows=5 1 | 2 | 3 | 9 | NULL",
	"NOTEXISTS/noJoin/onLeftEq":              "rows=0 ",
	"ANY/noJoin/onLeftEq":                    "rows=0 ",
	"ALL/noJoin/onLeftEq":                    "rows=0 ",
	"SCALARWHERE/noJoin/onLeftEq":            "rows=0 ",
	"IN/noJoin/having":                       "rows=2 1 | 2",
	"NOTIN/noJoin/having":                    "rows=3 3 | 9 | NULL",
	"EXISTS/noJoin/having":                   "rows=4 1 | 2 | 3 | 9",
	"NOTEXISTS/noJoin/having":                "rows=1 NULL",
	"ANY/noJoin/having":                      "rows=2 1 | 2",
	"ALL/noJoin/having":                      "rows=3 3 | 9 | NULL",
	"IN/noJoin/havingOuter":                  "rows=1 2",
	"NOTIN/noJoin/havingOuter":               "rows=3 1 | 3 | 9",
	"EXISTS/noJoin/havingOuter":              "rows=2 2 | NULL",
	"NOTEXISTS/noJoin/havingOuter":           "rows=3 1 | 3 | 9",
	"ANY/noJoin/havingOuter":                 "rows=1 2",
	"ALL/noJoin/havingOuter":                 "rows=3 1 | 3 | 9",
	"IN/noJoin/selectOuter":                  "rows=0 ",
	"NOTIN/noJoin/selectOuter":               "rows=4 1 | 2 | 3 | 9",
	"EXISTS/noJoin/selectOuter":              "rows=5 1 | 2 | 3 | 9 | NULL",
	"NOTEXISTS/noJoin/selectOuter":           "rows=0 ",
	"ANY/noJoin/selectOuter":                 "rows=0 ",
	"ALL/noJoin/selectOuter":                 "rows=4 1 | 2 | 3 | 9",
	"SCALARWHERE/noJoin/selectOuter":         "ERR ERROR: aggregate functions are not allowed in WHERE (SQLSTATE 42803)",
	"IN/noJoin/selectOuterOnly":              "rows=0 ",
	"NOTIN/noJoin/selectOuterOnly":           "rows=4 1 | 2 | 3 | 9",
	"EXISTS/noJoin/selectOuterOnly":          "rows=5 1 | 2 | 3 | 9 | NULL",
	"NOTEXISTS/noJoin/selectOuterOnly":       "rows=0 ",
	"ANY/noJoin/selectOuterOnly":             "rows=0 ",
	"ALL/noJoin/selectOuterOnly":             "rows=4 1 | 2 | 3 | 9",
	"SCALARWHERE/noJoin/selectOuterOnly":     "ERR ERROR: aggregate functions are not allowed in WHERE (SQLSTATE 42803)",
	"IN/noJoin/nestedDerived":                "rows=2 1 | 2",
	"NOTIN/noJoin/nestedDerived":             "rows=3 3 | 9 | NULL",
	"EXISTS/noJoin/nestedDerived":            "rows=4 1 | 2 | 3 | 9",
	"NOTEXISTS/noJoin/nestedDerived":         "rows=1 NULL",
	"ANY/noJoin/nestedDerived":               "rows=2 1 | 2",
	"ALL/noJoin/nestedDerived":               "rows=3 3 | 9 | NULL",
	"SCALARWHERE/noJoin/nestedDerived":       "rows=1 2",
	"IN/noJoin/nestedSubq":                   "rows=1 2",
	"NOTIN/noJoin/nestedSubq":                "rows=4 1 | 3 | 9 | NULL",
	"EXISTS/noJoin/nestedSubq":               "rows=4 1 | 2 | 3 | 9",
	"NOTEXISTS/noJoin/nestedSubq":            "rows=1 NULL",
	"ANY/noJoin/nestedSubq":                  "rows=1 2",
	"ALL/noJoin/nestedSubq":                  "rows=4 1 | 3 | 9 | NULL",
	"SCALARWHERE/noJoin/nestedSubq":          "rows=1 2",
	"IN/noJoin/nestedSubqOuter":              "rows=1 2",
	"NOTIN/noJoin/nestedSubqOuter":           "rows=3 1 | 3 | 9",
	"EXISTS/noJoin/nestedSubqOuter":          "rows=2 2 | NULL",
	"NOTEXISTS/noJoin/nestedSubqOuter":       "rows=3 1 | 3 | 9",
	"ANY/noJoin/nestedSubqOuter":             "rows=1 2",
	"ALL/noJoin/nestedSubqOuter":             "rows=3 1 | 3 | 9",
	"SCALARWHERE/noJoin/nestedSubqOuter":     "rows=1 2",
	"IN/noJoin/twoOnWhere":                   "rows=1 1",
	"NOTIN/noJoin/twoOnWhere":                "rows=4 2 | 3 | 9 | NULL",
	"EXISTS/noJoin/twoOnWhere":               "rows=1 1",
	"NOTEXISTS/noJoin/twoOnWhere":            "rows=4 2 | 3 | 9 | NULL",
	"ANY/noJoin/twoOnWhere":                  "rows=1 1",
	"ALL/noJoin/twoOnWhere":                  "rows=4 2 | 3 | 9 | NULL",
	"SCALARWHERE/noJoin/twoOnWhere":          "rows=1 1",
	"IN/noJoin/twoWhere":                     "rows=1 1",
	"NOTIN/noJoin/twoWhere":                  "rows=4 2 | 3 | 9 | NULL",
	"EXISTS/noJoin/twoWhere":                 "rows=1 1",
	"NOTEXISTS/noJoin/twoWhere":              "rows=4 2 | 3 | 9 | NULL",
	"ANY/noJoin/twoWhere":                    "rows=1 1",
	"ALL/noJoin/twoWhere":                    "rows=4 2 | 3 | 9 | NULL",
	"SCALARWHERE/noJoin/twoWhere":            "rows=1 1",
	"IN/noJoin/twoOuterOnly":                 "rows=1 2",
	"NOTIN/noJoin/twoOuterOnly":              "rows=4 1 | 3 | 9 | NULL",
	"EXISTS/noJoin/twoOuterOnly":             "rows=1 2",
	"NOTEXISTS/noJoin/twoOuterOnly":          "rows=4 1 | 3 | 9 | NULL",
	"ANY/noJoin/twoOuterOnly":                "rows=1 2",
	"ALL/noJoin/twoOuterOnly":                "rows=4 1 | 3 | 9 | NULL",
	"SCALARWHERE/noJoin/twoOuterOnly":        "rows=1 2",
	"IN/noJoin/whereOuterShadow":             "rows=1 2",
	"NOTIN/noJoin/whereOuterShadow":          "rows=3 1 | 3 | 9",
	"EXISTS/noJoin/whereOuterShadow":         "rows=2 2 | NULL",
	"NOTEXISTS/noJoin/whereOuterShadow":      "rows=3 1 | 3 | 9",
	"ANY/noJoin/whereOuterShadow":            "rows=1 2",
	"ALL/noJoin/whereOuterShadow":            "rows=3 1 | 3 | 9",
	"SCALARWHERE/noJoin/whereOuterShadow":    "rows=0 ",
	"IN/noJoin/onOuterShadow":                "rows=1 2",
	"NOTIN/noJoin/onOuterShadow":             "rows=3 1 | 3 | 9",
	"EXISTS/noJoin/onOuterShadow":            "rows=2 2 | NULL",
	"NOTEXISTS/noJoin/onOuterShadow":         "rows=3 1 | 3 | 9",
	"ANY/noJoin/onOuterShadow":               "rows=1 2",
	"ALL/noJoin/onOuterShadow":               "rows=3 1 | 3 | 9",
	"SCALARWHERE/noJoin/onOuterShadow":       "rows=0 ",
	"IN/noJoin/havingShadow":                 "rows=1 2",
	"NOTIN/noJoin/havingShadow":              "rows=3 1 | 3 | 9",
	"EXISTS/noJoin/havingShadow":             "rows=2 2 | NULL",
	"NOTEXISTS/noJoin/havingShadow":          "rows=3 1 | 3 | 9",
	"ANY/noJoin/havingShadow":                "rows=1 2",
	"ALL/noJoin/havingShadow":                "rows=3 1 | 3 | 9",
	"IN/noJoin/whereShadowCorr":              "rows=1 2",
	"NOTIN/noJoin/whereShadowCorr":           "rows=4 1 | 3 | 9 | NULL",
	"EXISTS/noJoin/whereShadowCorr":          "rows=1 2",
	"NOTEXISTS/noJoin/whereShadowCorr":       "rows=4 1 | 3 | 9 | NULL",
	"ANY/noJoin/whereShadowCorr":             "rows=1 2",
	"ALL/noJoin/whereShadowCorr":             "rows=4 1 | 3 | 9 | NULL",
	"SCALARWHERE/noJoin/whereShadowCorr":     "rows=1 2",
	"IN/noJoin/whereOuterBare":               "rows=1 2",
	"NOTIN/noJoin/whereOuterBare":            "rows=3 1 | 3 | 9",
	"EXISTS/noJoin/whereOuterBare":           "rows=2 2 | NULL",
	"NOTEXISTS/noJoin/whereOuterBare":        "rows=3 1 | 3 | 9",
	"ANY/noJoin/whereOuterBare":              "rows=1 2",
	"ALL/noJoin/whereOuterBare":              "rows=3 1 | 3 | 9",
	"SCALARWHERE/noJoin/whereOuterBare":      "rows=0 ",
	"IN/noJoin/whereOuterTwoCols":            "rows=0 ",
	"NOTIN/noJoin/whereOuterTwoCols":         "rows=5 1 | 2 | 3 | 9 | NULL",
	"EXISTS/noJoin/whereOuterTwoCols":        "rows=0 ",
	"NOTEXISTS/noJoin/whereOuterTwoCols":     "rows=5 1 | 2 | 3 | 9 | NULL",
	"ANY/noJoin/whereOuterTwoCols":           "rows=0 ",
	"ALL/noJoin/whereOuterTwoCols":           "rows=5 1 | 2 | 3 | 9 | NULL",
	"SCALARWHERE/noJoin/whereOuterTwoCols":   "rows=0 ",
	"IN/noJoin/onBareOuter":                  "rows=1 2",
	"NOTIN/noJoin/onBareOuter":               "rows=3 1 | 3 | 9",
	"EXISTS/noJoin/onBareOuter":              "rows=2 2 | NULL",
	"NOTEXISTS/noJoin/onBareOuter":           "rows=3 1 | 3 | 9",
	"ANY/noJoin/onBareOuter":                 "rows=1 2",
	"ALL/noJoin/onBareOuter":                 "rows=3 1 | 3 | 9",
	"SCALARWHERE/noJoin/onBareOuter":         "rows=1 2",
	"IN/noJoin/commaCorr":                    "rows=2 1 | 2",
	"NOTIN/noJoin/commaCorr":                 "rows=3 3 | 9 | NULL",
	"EXISTS/noJoin/commaCorr":                "rows=2 1 | 2",
	"NOTEXISTS/noJoin/commaCorr":             "rows=3 3 | 9 | NULL",
	"ANY/noJoin/commaCorr":                   "rows=2 1 | 2",
	"ALL/noJoin/commaCorr":                   "rows=3 3 | 9 | NULL",
	"SCALARWHERE/noJoin/commaCorr":           "rows=2 1 | 2",
	"IN/noJoin/commaNe":                      "rows=1 1",
	"NOTIN/noJoin/commaNe":                   "rows=3 2 | 3 | 9",
	"EXISTS/noJoin/commaNe":                  "rows=3 1 | 2 | NULL",
	"NOTEXISTS/noJoin/commaNe":               "rows=2 3 | 9",
	"ANY/noJoin/commaNe":                     "rows=1 1",
	"ALL/noJoin/commaNe":                     "rows=3 2 | 3 | 9",
	"SCALARWHERE/noJoin/commaNe":             "rows=1 1",
	"IN/noJoin/commaOuterOnly":               "rows=1 2",
	"NOTIN/noJoin/commaOuterOnly":            "rows=3 1 | 3 | 9",
	"EXISTS/noJoin/commaOuterOnly":           "rows=2 2 | NULL",
	"NOTEXISTS/noJoin/commaOuterOnly":        "rows=3 1 | 3 | 9",
	"ANY/noJoin/commaOuterOnly":              "rows=1 2",
	"ALL/noJoin/commaOuterOnly":              "rows=3 1 | 3 | 9",
	"SCALARWHERE/noJoin/commaOuterOnly":      "rows=1 2",
	"IN/noJoin/havingWithWhere":              "rows=1 1",
	"NOTIN/noJoin/havingWithWhere":           "rows=4 2 | 3 | 9 | NULL",
	"EXISTS/noJoin/havingWithWhere":          "rows=3 1 | 3 | 9",
	"NOTEXISTS/noJoin/havingWithWhere":       "rows=2 2 | NULL",
	"ANY/noJoin/havingWithWhere":             "rows=1 1",
	"ALL/noJoin/havingWithWhere":             "rows=4 2 | 3 | 9 | NULL",
	"IN/noJoin/havingOuterWithWhere":         "rows=0 ",
	"NOTIN/noJoin/havingOuterWithWhere":      "rows=4 1 | 2 | 3 | 9",
	"EXISTS/noJoin/havingOuterWithWhere":     "rows=2 2 | NULL",
	"NOTEXISTS/noJoin/havingOuterWithWhere":  "rows=3 1 | 3 | 9",
	"ANY/noJoin/havingOuterWithWhere":        "rows=0 ",
	"ALL/noJoin/havingOuterWithWhere":        "rows=4 1 | 2 | 3 | 9",
	"IN/noJoin/onRightPad":                   "rows=1 1",
	"NOTIN/noJoin/onRightPad":                "rows=0 ",
	"EXISTS/noJoin/onRightPad":               "rows=5 1 | 2 | 3 | 9 | NULL",
	"NOTEXISTS/noJoin/onRightPad":            "rows=0 ",
	"ANY/noJoin/onRightPad":                  "rows=1 1",
	"ALL/noJoin/onRightPad":                  "rows=0 ",
	"SCALARWHERE/noJoin/onRightPad":          "rows=1 1",
	"IN/noJoin/selectOuterJoin":              "rows=0 ",
	"NOTIN/noJoin/selectOuterJoin":           "rows=4 1 | 2 | 3 | 9",
	"EXISTS/noJoin/selectOuterJoin":          "rows=5 1 | 2 | 3 | 9 | NULL",
	"NOTEXISTS/noJoin/selectOuterJoin":       "rows=0 ",
	"ANY/noJoin/selectOuterJoin":             "rows=0 ",
	"ALL/noJoin/selectOuterJoin":             "rows=4 1 | 2 | 3 | 9",
	"SCALARWHERE/noJoin/selectOuterJoin":     "ERR ERROR: aggregate functions are not allowed in WHERE (SQLSTATE 42803)",
	"IN/noJoin/nullInner":                    "rows=1 1",
	"NOTIN/noJoin/nullInner":                 "rows=0 ",
	"EXISTS/noJoin/nullInner":                "rows=5 1 | 2 | 3 | 9 | NULL",
	"NOTEXISTS/noJoin/nullInner":             "rows=0 ",
	"ANY/noJoin/nullInner":                   "rows=1 1",
	"ALL/noJoin/nullInner":                   "rows=0 ",
	"SCALARWHERE/noJoin/nullInner":           "rows=1 1",
	"IN/noJoin/nullInnerCorr":                "rows=1 1",
	"NOTIN/noJoin/nullInnerCorr":             "rows=1 9",
	"EXISTS/noJoin/nullInnerCorr":            "rows=4 1 | 2 | 3 | NULL",
	"NOTEXISTS/noJoin/nullInnerCorr":         "rows=1 9",
	"ANY/noJoin/nullInnerCorr":               "rows=1 1",
	"ALL/noJoin/nullInnerCorr":               "rows=1 9",
	"SCALARWHERE/noJoin/nullInnerCorr":       "rows=1 1",
	"IN/noJoin/nullInnerOuter":               "rows=0 ",
	"NOTIN/noJoin/nullInnerOuter":            "rows=3 1 | 3 | 9",
	"EXISTS/noJoin/nullInnerOuter":           "rows=2 2 | NULL",
	"NOTEXISTS/noJoin/nullInnerOuter":        "rows=3 1 | 3 | 9",
	"ANY/noJoin/nullInnerOuter":              "rows=0 ",
	"ALL/noJoin/nullInnerOuter":              "rows=3 1 | 3 | 9",
	"SCALARWHERE/noJoin/nullInnerOuter":      "rows=0 ",
	"SCALARSELECT/noJoin/whereEq":            "rows=5 1,1 | 2,2 | 3,NULL | 9,NULL | NULL,NULL",
	"SCALARSELECT/noJoin/whereNe":            "rows=5 1,2 | 2,2 | 3,2 | 9,5 | NULL,NULL",
	"SCALARSELECT/noJoin/whereFn":            "rows=5 1,1 | 2,2 | 3,NULL | 9,NULL | NULL,NULL",
	"SCALARSELECT/noJoin/whereCast":          "rows=5 1,1 | 2,2 | 3,NULL | 9,NULL | NULL,NULL",
	"SCALARSELECT/noJoin/whereIDF":           "rows=5 1,5 | 2,5 | 3,5 | 9,5 | NULL,5",
	"SCALARSELECT/noJoin/whereOuterOnly":     "rows=5 1,NULL | 2,5 | 3,NULL | 9,NULL | NULL,5",
	"SCALARSELECT/noJoin/whereOuterEq":       "rows=5 1,5 | 2,5 | 3,NULL | 9,NULL | NULL,NULL",
	"SCALARSELECT/noJoin/whereOuterNull":     "rows=5 1,NULL | 2,NULL | 3,NULL | 9,NULL | NULL,5",
	"SCALARSELECT/noJoin/whereOuterFn":       "rows=5 1,NULL | 2,5 | 3,NULL | 9,NULL | NULL,5",
	"SCALARSELECT/noJoin/whereBoth":          "rows=5 1,NULL | 2,2 | 3,NULL | 9,NULL | NULL,NULL",
	"SCALARSELECT/noJoin/whereEmpty":         "rows=5 1,NULL | 2,NULL | 3,NULL | 9,NULL | NULL,NULL",
	"SCALARSELECT/noJoin/onEq":               "rows=5 1,1 | 2,2 | 3,NULL | 9,NULL | NULL,NULL",
	"SCALARSELECT/noJoin/onNe":               "rows=5 1,1 | 2,1 | 3,NULL | 9,NULL | NULL,2",
	"SCALARSELECT/noJoin/onFn":               "rows=5 1,1 | 2,2 | 3,NULL | 9,NULL | NULL,NULL",
	"SCALARSELECT/noJoin/onIDF":              "rows=5 1,2 | 2,1 | 3,2 | 9,2 | NULL,2",
	"SCALARSELECT/noJoin/onOuterOnly":        "rows=5 1,NULL | 2,2 | 3,NULL | 9,NULL | NULL,2",
	"SCALARSELECT/noJoin/onOuterNull":        "rows=5 1,NULL | 2,NULL | 3,NULL | 9,NULL | NULL,2",
	"SCALARSELECT/noJoin/onSelf":             "rows=5 1,5 | 2,5 | 3,5 | 9,NULL | NULL,5",
	"SCALARSELECT/noJoin/onWhereSplit":       "rows=5 1,NULL | 2,2 | 3,NULL | 9,NULL | NULL,NULL",
	"SCALARSELECT/noJoin/onLeftPad":          "rows=5 1,7 | 2,7 | 3,NULL | 9,NULL | NULL,8",
	"SCALARSELECT/noJoin/onLeftOuter":        "rows=5 1,NULL | 2,8 | 3,NULL | 9,NULL | NULL,8",
	"SCALARSELECT/noJoin/onLeftEq":           "rows=5 1,7 | 2,8 | 3,NULL | 9,NULL | NULL,NULL",
	"SCALARSELECT/noJoin/selectOuter":        "ERR ERROR: column \"o.id\" must appear in the GROUP BY clause or be used in an aggregate function (SQLSTATE 42803)",
	"SCALARSELECT/noJoin/selectOuterOnly":    "ERR ERROR: column \"o.id\" must appear in the GROUP BY clause or be used in an aggregate function (SQLSTATE 42803)",
	"SCALARSELECT/noJoin/nestedDerived":      "rows=5 1,2 | 2,2 | 3,2 | 9,5 | NULL,NULL",
	"SCALARSELECT/noJoin/nestedSubq":         "rows=5 1,2 | 2,2 | 3,2 | 9,2 | NULL,NULL",
	"SCALARSELECT/noJoin/nestedSubqOuter":    "rows=5 1,NULL | 2,2 | 3,NULL | 9,NULL | NULL,2",
	"SCALARSELECT/noJoin/twoOnWhere":         "rows=5 1,1 | 2,NULL | 3,NULL | 9,NULL | NULL,NULL",
	"SCALARSELECT/noJoin/twoWhere":           "rows=5 1,1 | 2,NULL | 3,NULL | 9,NULL | NULL,NULL",
	"SCALARSELECT/noJoin/twoOuterOnly":       "rows=5 1,NULL | 2,2 | 3,NULL | 9,NULL | NULL,NULL",
	"SCALARSELECT/noJoin/whereOuterShadow":   "rows=5 1,NULL | 2,9 | 3,NULL | 9,NULL | NULL,9",
	"SCALARSELECT/noJoin/onOuterShadow":      "rows=5 1,NULL | 2,9 | 3,NULL | 9,NULL | NULL,9",
	"SCALARSELECT/noJoin/whereShadowCorr":    "rows=5 1,NULL | 2,2 | 3,NULL | 9,NULL | NULL,NULL",
	"SCALARSELECT/noJoin/whereOuterBare":     "rows=5 1,NULL | 2,5 | 3,NULL | 9,NULL | NULL,5",
	"SCALARSELECT/noJoin/whereOuterTwoCols":  "rows=5 1,NULL | 2,NULL | 3,NULL | 9,NULL | NULL,NULL",
	"SCALARSELECT/noJoin/onBareOuter":        "rows=5 1,NULL | 2,2 | 3,NULL | 9,NULL | NULL,2",
	"SCALARSELECT/noJoin/commaCorr":          "rows=5 1,1 | 2,2 | 3,NULL | 9,NULL | NULL,NULL",
	"SCALARSELECT/noJoin/commaNe":            "rows=5 1,1 | 2,1 | 3,NULL | 9,NULL | NULL,2",
	"SCALARSELECT/noJoin/commaOuterOnly":     "rows=5 1,NULL | 2,2 | 3,NULL | 9,NULL | NULL,2",
	"SCALARSELECT/noJoin/onRightPad":         "rows=5 1,1 | 2,1 | 3,NULL | 9,NULL | NULL,2",
	"SCALARSELECT/noJoin/selectOuterJoin":    "ERR ERROR: column \"o.id\" must appear in the GROUP BY clause or be used in an aggregate function (SQLSTATE 42803)",
	"SCALARSELECT/noJoin/nullInner":          "rows=5 1,1 | 2,1 | 3,1 | 9,1 | NULL,1",
	"SCALARSELECT/noJoin/nullInnerCorr":      "rows=5 1,1 | 2,1 | 3,1 | 9,NULL | NULL,1",
	"SCALARSELECT/noJoin/nullInnerOuter":     "rows=5 1,NULL | 2,1 | 3,NULL | 9,NULL | NULL,1",
	"IN/onOuter/whereEq":                     "rows=2 1,7 | 2,8",
	"NOTIN/onOuter/whereEq":                  "rows=1 9,9",
	"EXISTS/onOuter/whereEq":                 "rows=2 1,7 | 2,8",
	"NOTEXISTS/onOuter/whereEq":              "rows=1 9,9",
	"ANY/onOuter/whereEq":                    "rows=2 1,7 | 2,8",
	"ALL/onOuter/whereEq":                    "rows=1 9,9",
	"SCALARWHERE/onOuter/whereEq":            "rows=2 1,7 | 2,8",
	"IN/onOuter/whereNe":                     "rows=2 1,7 | 2,8",
	"NOTIN/onOuter/whereNe":                  "rows=1 9,9",
	"EXISTS/onOuter/whereNe":                 "rows=3 1,7 | 2,8 | 9,9",
	"NOTEXISTS/onOuter/whereNe":              "rows=0 ",
	"ANY/onOuter/whereNe":                    "rows=2 1,7 | 2,8",
	"ALL/onOuter/whereNe":                    "rows=1 9,9",
	"SCALARWHERE/onOuter/whereNe":            "rows=1 2,8",
	"IN/onOuter/whereFn":                     "rows=2 1,7 | 2,8",
	"NOTIN/onOuter/whereFn":                  "rows=1 9,9",
	"EXISTS/onOuter/whereFn":                 "rows=2 1,7 | 2,8",
	"NOTEXISTS/onOuter/whereFn":              "rows=1 9,9",
	"ANY/onOuter/whereFn":                    "rows=2 1,7 | 2,8",
	"ALL/onOuter/whereFn":                    "rows=1 9,9",
	"SCALARWHERE/onOuter/whereFn":            "rows=2 1,7 | 2,8",
	"IN/onOuter/whereCast":                   "rows=2 1,7 | 2,8",
	"NOTIN/onOuter/whereCast":                "rows=1 9,9",
	"EXISTS/onOuter/whereCast":               "rows=2 1,7 | 2,8",
	"NOTEXISTS/onOuter/whereCast":            "rows=1 9,9",
	"ANY/onOuter/whereCast":                  "rows=2 1,7 | 2,8",
	"ALL/onOuter/whereCast":                  "rows=1 9,9",
	"SCALARWHERE/onOuter/whereCast":          "rows=2 1,7 | 2,8",
	"IN/onOuter/whereIDF":                    "rows=0 ",
	"NOTIN/onOuter/whereIDF":                 "rows=3 1,7 | 2,8 | 9,9",
	"EXISTS/onOuter/whereIDF":                "rows=3 1,7 | 2,8 | 9,9",
	"NOTEXISTS/onOuter/whereIDF":             "rows=0 ",
	"ANY/onOuter/whereIDF":                   "rows=0 ",
	"ALL/onOuter/whereIDF":                   "rows=3 1,7 | 2,8 | 9,9",
	"SCALARWHERE/onOuter/whereIDF":           "rows=0 ",
	"IN/onOuter/whereOuterOnly":              "rows=1 2,8",
	"NOTIN/onOuter/whereOuterOnly":           "rows=2 1,7 | 9,9",
	"EXISTS/onOuter/whereOuterOnly":          "rows=1 2,8",
	"NOTEXISTS/onOuter/whereOuterOnly":       "rows=2 1,7 | 9,9",
	"ANY/onOuter/whereOuterOnly":             "rows=1 2,8",
	"ALL/onOuter/whereOuterOnly":             "rows=2 1,7 | 9,9",
	"SCALARWHERE/onOuter/whereOuterOnly":     "rows=0 ",
	"IN/onOuter/whereOuterEq":                "rows=2 1,7 | 2,8",
	"NOTIN/onOuter/whereOuterEq":             "rows=1 9,9",
	"EXISTS/onOuter/whereOuterEq":            "rows=2 1,7 | 2,8",
	"NOTEXISTS/onOuter/whereOuterEq":         "rows=1 9,9",
	"ANY/onOuter/whereOuterEq":               "rows=2 1,7 | 2,8",
	"ALL/onOuter/whereOuterEq":               "rows=1 9,9",
	"SCALARWHERE/onOuter/whereOuterEq":       "rows=0 ",
	"IN/onOuter/whereOuterNull":              "rows=0 ",
	"NOTIN/onOuter/whereOuterNull":           "rows=3 1,7 | 2,8 | 9,9",
	"EXISTS/onOuter/whereOuterNull":          "rows=0 ",
	"NOTEXISTS/onOuter/whereOuterNull":       "rows=3 1,7 | 2,8 | 9,9",
	"ANY/onOuter/whereOuterNull":             "rows=0 ",
	"ALL/onOuter/whereOuterNull":             "rows=3 1,7 | 2,8 | 9,9",
	"SCALARWHERE/onOuter/whereOuterNull":     "rows=0 ",
	"IN/onOuter/whereOuterFn":                "rows=1 2,8",
	"NOTIN/onOuter/whereOuterFn":             "rows=2 1,7 | 9,9",
	"EXISTS/onOuter/whereOuterFn":            "rows=1 2,8",
	"NOTEXISTS/onOuter/whereOuterFn":         "rows=2 1,7 | 9,9",
	"ANY/onOuter/whereOuterFn":               "rows=1 2,8",
	"ALL/onOuter/whereOuterFn":               "rows=2 1,7 | 9,9",
	"SCALARWHERE/onOuter/whereOuterFn":       "rows=0 ",
	"IN/onOuter/whereBoth":                   "rows=1 2,8",
	"NOTIN/onOuter/whereBoth":                "rows=2 1,7 | 9,9",
	"EXISTS/onOuter/whereBoth":               "rows=1 2,8",
	"NOTEXISTS/onOuter/whereBoth":            "rows=2 1,7 | 9,9",
	"ANY/onOuter/whereBoth":                  "rows=1 2,8",
	"ALL/onOuter/whereBoth":                  "rows=2 1,7 | 9,9",
	"SCALARWHERE/onOuter/whereBoth":          "rows=1 2,8",
	"IN/onOuter/whereEmpty":                  "rows=0 ",
	"NOTIN/onOuter/whereEmpty":               "rows=3 1,7 | 2,8 | 9,9",
	"EXISTS/onOuter/whereEmpty":              "rows=0 ",
	"NOTEXISTS/onOuter/whereEmpty":           "rows=3 1,7 | 2,8 | 9,9",
	"ANY/onOuter/whereEmpty":                 "rows=0 ",
	"ALL/onOuter/whereEmpty":                 "rows=3 1,7 | 2,8 | 9,9",
	"SCALARWHERE/onOuter/whereEmpty":         "rows=0 ",
	"IN/onOuter/onEq":                        "rows=2 1,7 | 2,8",
	"NOTIN/onOuter/onEq":                     "rows=1 9,9",
	"EXISTS/onOuter/onEq":                    "rows=2 1,7 | 2,8",
	"NOTEXISTS/onOuter/onEq":                 "rows=1 9,9",
	"ANY/onOuter/onEq":                       "rows=2 1,7 | 2,8",
	"ALL/onOuter/onEq":                       "rows=1 9,9",
	"SCALARWHERE/onOuter/onEq":               "rows=2 1,7 | 2,8",
	"IN/onOuter/onNe":                        "rows=1 1,7",
	"NOTIN/onOuter/onNe":                     "rows=2 2,8 | 9,9",
	"EXISTS/onOuter/onNe":                    "rows=2 1,7 | 2,8",
	"NOTEXISTS/onOuter/onNe":                 "rows=1 9,9",
	"ANY/onOuter/onNe":                       "rows=1 1,7",
	"ALL/onOuter/onNe":                       "rows=2 2,8 | 9,9",
	"SCALARWHERE/onOuter/onNe":               "rows=1 1,7",
	"IN/onOuter/onFn":                        "rows=2 1,7 | 2,8",
	"NOTIN/onOuter/onFn":                     "rows=1 9,9",
	"EXISTS/onOuter/onFn":                    "rows=2 1,7 | 2,8",
	"NOTEXISTS/onOuter/onFn":                 "rows=1 9,9",
	"ANY/onOuter/onFn":                       "rows=2 1,7 | 2,8",
	"ALL/onOuter/onFn":                       "rows=1 9,9",
	"SCALARWHERE/onOuter/onFn":               "rows=2 1,7 | 2,8",
	"IN/onOuter/onIDF":                       "rows=0 ",
	"NOTIN/onOuter/onIDF":                    "rows=3 1,7 | 2,8 | 9,9",
	"EXISTS/onOuter/onIDF":                   "rows=3 1,7 | 2,8 | 9,9",
	"NOTEXISTS/onOuter/onIDF":                "rows=0 ",
	"ANY/onOuter/onIDF":                      "rows=0 ",
	"ALL/onOuter/onIDF":                      "rows=3 1,7 | 2,8 | 9,9",
	"SCALARWHERE/onOuter/onIDF":              "rows=0 ",
	"IN/onOuter/onOuterOnly":                 "rows=1 2,8",
	"NOTIN/onOuter/onOuterOnly":              "rows=2 1,7 | 9,9",
	"EXISTS/onOuter/onOuterOnly":             "rows=1 2,8",
	"NOTEXISTS/onOuter/onOuterOnly":          "rows=2 1,7 | 9,9",
	"ANY/onOuter/onOuterOnly":                "rows=1 2,8",
	"ALL/onOuter/onOuterOnly":                "rows=2 1,7 | 9,9",
	"SCALARWHERE/onOuter/onOuterOnly":        "rows=1 2,8",
	"IN/onOuter/onOuterNull":                 "rows=0 ",
	"NOTIN/onOuter/onOuterNull":              "rows=3 1,7 | 2,8 | 9,9",
	"EXISTS/onOuter/onOuterNull":             "rows=0 ",
	"NOTEXISTS/onOuter/onOuterNull":          "rows=3 1,7 | 2,8 | 9,9",
	"ANY/onOuter/onOuterNull":                "rows=0 ",
	"ALL/onOuter/onOuterNull":                "rows=3 1,7 | 2,8 | 9,9",
	"SCALARWHERE/onOuter/onOuterNull":        "rows=0 ",
	"IN/onOuter/onSelf":                      "rows=1 1,7",
	"NOTIN/onOuter/onSelf":                   "rows=2 2,8 | 9,9",
	"EXISTS/onOuter/onSelf":                  "rows=2 1,7 | 2,8",
	"NOTEXISTS/onOuter/onSelf":               "rows=1 9,9",
	"ANY/onOuter/onSelf":                     "rows=1 1,7",
	"ALL/onOuter/onSelf":                     "rows=2 2,8 | 9,9",
	"SCALARWHERE/onOuter/onSelf":             "rows=0 ",
	"IN/onOuter/onWhereSplit":                "rows=1 2,8",
	"NOTIN/onOuter/onWhereSplit":             "rows=2 1,7 | 9,9",
	"EXISTS/onOuter/onWhereSplit":            "rows=1 2,8",
	"NOTEXISTS/onOuter/onWhereSplit":         "rows=2 1,7 | 9,9",
	"ANY/onOuter/onWhereSplit":               "rows=1 2,8",
	"ALL/onOuter/onWhereSplit":               "rows=2 1,7 | 9,9",
	"SCALARWHERE/onOuter/onWhereSplit":       "rows=1 2,8",
	"IN/onOuter/onLeftPad":                   "rows=0 ",
	"NOTIN/onOuter/onLeftPad":                "rows=0 ",
	"EXISTS/onOuter/onLeftPad":               "rows=3 1,7 | 2,8 | 9,9",
	"NOTEXISTS/onOuter/onLeftPad":            "rows=0 ",
	"ANY/onOuter/onLeftPad":                  "rows=0 ",
	"ALL/onOuter/onLeftPad":                  "rows=0 ",
	"SCALARWHERE/onOuter/onLeftPad":          "rows=0 ",
	"IN/onOuter/onLeftOuter":                 "rows=0 ",
	"NOTIN/onOuter/onLeftOuter":              "rows=0 ",
	"EXISTS/onOuter/onLeftOuter":             "rows=3 1,7 | 2,8 | 9,9",
	"NOTEXISTS/onOuter/onLeftOuter":          "rows=0 ",
	"ANY/onOuter/onLeftOuter":                "rows=0 ",
	"ALL/onOuter/onLeftOuter":                "rows=0 ",
	"SCALARWHERE/onOuter/onLeftOuter":        "rows=0 ",
	"IN/onOuter/onLeftEq":                    "rows=0 ",
	"NOTIN/onOuter/onLeftEq":                 "rows=0 ",
	"EXISTS/onOuter/onLeftEq":                "rows=3 1,7 | 2,8 | 9,9",
	"NOTEXISTS/onOuter/onLeftEq":             "rows=0 ",
	"ANY/onOuter/onLeftEq":                   "rows=0 ",
	"ALL/onOuter/onLeftEq":                   "rows=0 ",
	"SCALARWHERE/onOuter/onLeftEq":           "rows=0 ",
	"IN/onOuter/having":                      "rows=2 1,7 | 2,8",
	"NOTIN/onOuter/having":                   "rows=1 9,9",
	"EXISTS/onOuter/having":                  "rows=3 1,7 | 2,8 | 9,9",
	"NOTEXISTS/onOuter/having":               "rows=0 ",
	"ANY/onOuter/having":                     "rows=2 1,7 | 2,8",
	"ALL/onOuter/having":                     "rows=1 9,9",
	"IN/onOuter/havingOuter":                 "rows=1 2,8",
	"NOTIN/onOuter/havingOuter":              "rows=2 1,7 | 9,9",
	"EXISTS/onOuter/havingOuter":             "rows=1 2,8",
	"NOTEXISTS/onOuter/havingOuter":          "rows=2 1,7 | 9,9",
	"ANY/onOuter/havingOuter":                "rows=1 2,8",
	"ALL/onOuter/havingOuter":                "rows=2 1,7 | 9,9",
	"IN/onOuter/selectOuter":                 "rows=0 ",
	"NOTIN/onOuter/selectOuter":              "rows=3 1,7 | 2,8 | 9,9",
	"EXISTS/onOuter/selectOuter":             "rows=3 1,7 | 2,8 | 9,9",
	"NOTEXISTS/onOuter/selectOuter":          "rows=0 ",
	"ANY/onOuter/selectOuter":                "rows=0 ",
	"ALL/onOuter/selectOuter":                "rows=3 1,7 | 2,8 | 9,9",
	"SCALARWHERE/onOuter/selectOuter":        "ERR ERROR: aggregate functions are not allowed in WHERE (SQLSTATE 42803)",
	"IN/onOuter/selectOuterOnly":             "rows=0 ",
	"NOTIN/onOuter/selectOuterOnly":          "rows=3 1,7 | 2,8 | 9,9",
	"EXISTS/onOuter/selectOuterOnly":         "rows=3 1,7 | 2,8 | 9,9",
	"NOTEXISTS/onOuter/selectOuterOnly":      "rows=0 ",
	"ANY/onOuter/selectOuterOnly":            "rows=0 ",
	"ALL/onOuter/selectOuterOnly":            "rows=3 1,7 | 2,8 | 9,9",
	"SCALARWHERE/onOuter/selectOuterOnly":    "ERR ERROR: aggregate functions are not allowed in WHERE (SQLSTATE 42803)",
	"IN/onOuter/nestedDerived":               "rows=2 1,7 | 2,8",
	"NOTIN/onOuter/nestedDerived":            "rows=1 9,9",
	"EXISTS/onOuter/nestedDerived":           "rows=3 1,7 | 2,8 | 9,9",
	"NOTEXISTS/onOuter/nestedDerived":        "rows=0 ",
	"ANY/onOuter/nestedDerived":              "rows=2 1,7 | 2,8",
	"ALL/onOuter/nestedDerived":              "rows=1 9,9",
	"SCALARWHERE/onOuter/nestedDerived":      "rows=1 2,8",
	"IN/onOuter/nestedSubq":                  "rows=1 2,8",
	"NOTIN/onOuter/nestedSubq":               "rows=2 1,7 | 9,9",
	"EXISTS/onOuter/nestedSubq":              "rows=3 1,7 | 2,8 | 9,9",
	"NOTEXISTS/onOuter/nestedSubq":           "rows=0 ",
	"ANY/onOuter/nestedSubq":                 "rows=1 2,8",
	"ALL/onOuter/nestedSubq":                 "rows=2 1,7 | 9,9",
	"SCALARWHERE/onOuter/nestedSubq":         "rows=1 2,8",
	"IN/onOuter/nestedSubqOuter":             "rows=1 2,8",
	"NOTIN/onOuter/nestedSubqOuter":          "rows=2 1,7 | 9,9",
	"EXISTS/onOuter/nestedSubqOuter":         "rows=1 2,8",
	"NOTEXISTS/onOuter/nestedSubqOuter":      "rows=2 1,7 | 9,9",
	"ANY/onOuter/nestedSubqOuter":            "rows=1 2,8",
	"ALL/onOuter/nestedSubqOuter":            "rows=2 1,7 | 9,9",
	"SCALARWHERE/onOuter/nestedSubqOuter":    "rows=1 2,8",
	"IN/onOuter/twoOnWhere":                  "rows=1 1,7",
	"NOTIN/onOuter/twoOnWhere":               "rows=2 2,8 | 9,9",
	"EXISTS/onOuter/twoOnWhere":              "rows=1 1,7",
	"NOTEXISTS/onOuter/twoOnWhere":           "rows=2 2,8 | 9,9",
	"ANY/onOuter/twoOnWhere":                 "rows=1 1,7",
	"ALL/onOuter/twoOnWhere":                 "rows=2 2,8 | 9,9",
	"SCALARWHERE/onOuter/twoOnWhere":         "rows=1 1,7",
	"IN/onOuter/twoWhere":                    "rows=1 1,7",
	"NOTIN/onOuter/twoWhere":                 "rows=2 2,8 | 9,9",
	"EXISTS/onOuter/twoWhere":                "rows=1 1,7",
	"NOTEXISTS/onOuter/twoWhere":             "rows=2 2,8 | 9,9",
	"ANY/onOuter/twoWhere":                   "rows=1 1,7",
	"ALL/onOuter/twoWhere":                   "rows=2 2,8 | 9,9",
	"SCALARWHERE/onOuter/twoWhere":           "rows=1 1,7",
	"IN/onOuter/twoOuterOnly":                "rows=1 2,8",
	"NOTIN/onOuter/twoOuterOnly":             "rows=2 1,7 | 9,9",
	"EXISTS/onOuter/twoOuterOnly":            "rows=1 2,8",
	"NOTEXISTS/onOuter/twoOuterOnly":         "rows=2 1,7 | 9,9",
	"ANY/onOuter/twoOuterOnly":               "rows=1 2,8",
	"ALL/onOuter/twoOuterOnly":               "rows=2 1,7 | 9,9",
	"SCALARWHERE/onOuter/twoOuterOnly":       "rows=1 2,8",
	"IN/onOuter/whereOuterShadow":            "rows=1 2,8",
	"NOTIN/onOuter/whereOuterShadow":         "rows=2 1,7 | 9,9",
	"EXISTS/onOuter/whereOuterShadow":        "rows=1 2,8",
	"NOTEXISTS/onOuter/whereOuterShadow":     "rows=2 1,7 | 9,9",
	"ANY/onOuter/whereOuterShadow":           "rows=1 2,8",
	"ALL/onOuter/whereOuterShadow":           "rows=2 1,7 | 9,9",
	"SCALARWHERE/onOuter/whereOuterShadow":   "rows=0 ",
	"IN/onOuter/onOuterShadow":               "rows=1 2,8",
	"NOTIN/onOuter/onOuterShadow":            "rows=2 1,7 | 9,9",
	"EXISTS/onOuter/onOuterShadow":           "rows=1 2,8",
	"NOTEXISTS/onOuter/onOuterShadow":        "rows=2 1,7 | 9,9",
	"ANY/onOuter/onOuterShadow":              "rows=1 2,8",
	"ALL/onOuter/onOuterShadow":              "rows=2 1,7 | 9,9",
	"SCALARWHERE/onOuter/onOuterShadow":      "rows=0 ",
	"IN/onOuter/havingShadow":                "rows=1 2,8",
	"NOTIN/onOuter/havingShadow":             "rows=2 1,7 | 9,9",
	"EXISTS/onOuter/havingShadow":            "rows=1 2,8",
	"NOTEXISTS/onOuter/havingShadow":         "rows=2 1,7 | 9,9",
	"ANY/onOuter/havingShadow":               "rows=1 2,8",
	"ALL/onOuter/havingShadow":               "rows=2 1,7 | 9,9",
	"IN/onOuter/whereShadowCorr":             "rows=1 2,8",
	"NOTIN/onOuter/whereShadowCorr":          "rows=2 1,7 | 9,9",
	"EXISTS/onOuter/whereShadowCorr":         "rows=1 2,8",
	"NOTEXISTS/onOuter/whereShadowCorr":      "rows=2 1,7 | 9,9",
	"ANY/onOuter/whereShadowCorr":            "rows=1 2,8",
	"ALL/onOuter/whereShadowCorr":            "rows=2 1,7 | 9,9",
	"SCALARWHERE/onOuter/whereShadowCorr":    "rows=1 2,8",
	"IN/onOuter/whereOuterBare":              "rows=1 2,8",
	"NOTIN/onOuter/whereOuterBare":           "rows=2 1,7 | 9,9",
	"EXISTS/onOuter/whereOuterBare":          "rows=1 2,8",
	"NOTEXISTS/onOuter/whereOuterBare":       "rows=2 1,7 | 9,9",
	"ANY/onOuter/whereOuterBare":             "rows=1 2,8",
	"ALL/onOuter/whereOuterBare":             "rows=2 1,7 | 9,9",
	"SCALARWHERE/onOuter/whereOuterBare":     "rows=0 ",
	"IN/onOuter/whereOuterTwoCols":           "rows=0 ",
	"NOTIN/onOuter/whereOuterTwoCols":        "rows=3 1,7 | 2,8 | 9,9",
	"EXISTS/onOuter/whereOuterTwoCols":       "rows=0 ",
	"NOTEXISTS/onOuter/whereOuterTwoCols":    "rows=3 1,7 | 2,8 | 9,9",
	"ANY/onOuter/whereOuterTwoCols":          "rows=0 ",
	"ALL/onOuter/whereOuterTwoCols":          "rows=3 1,7 | 2,8 | 9,9",
	"SCALARWHERE/onOuter/whereOuterTwoCols":  "rows=0 ",
	"IN/onOuter/onBareOuter":                 "rows=1 2,8",
	"NOTIN/onOuter/onBareOuter":              "rows=2 1,7 | 9,9",
	"EXISTS/onOuter/onBareOuter":             "rows=1 2,8",
	"NOTEXISTS/onOuter/onBareOuter":          "rows=2 1,7 | 9,9",
	"ANY/onOuter/onBareOuter":                "rows=1 2,8",
	"ALL/onOuter/onBareOuter":                "rows=2 1,7 | 9,9",
	"SCALARWHERE/onOuter/onBareOuter":        "rows=1 2,8",
	"IN/onOuter/commaCorr":                   "rows=2 1,7 | 2,8",
	"NOTIN/onOuter/commaCorr":                "rows=1 9,9",
	"EXISTS/onOuter/commaCorr":               "rows=2 1,7 | 2,8",
	"NOTEXISTS/onOuter/commaCorr":            "rows=1 9,9",
	"ANY/onOuter/commaCorr":                  "rows=2 1,7 | 2,8",
	"ALL/onOuter/commaCorr":                  "rows=1 9,9",
	"SCALARWHERE/onOuter/commaCorr":          "rows=2 1,7 | 2,8",
	"IN/onOuter/commaNe":                     "rows=1 1,7",
	"NOTIN/onOuter/commaNe":                  "rows=2 2,8 | 9,9",
	"EXISTS/onOuter/commaNe":                 "rows=2 1,7 | 2,8",
	"NOTEXISTS/onOuter/commaNe":              "rows=1 9,9",
	"ANY/onOuter/commaNe":                    "rows=1 1,7",
	"ALL/onOuter/commaNe":                    "rows=2 2,8 | 9,9",
	"SCALARWHERE/onOuter/commaNe":            "rows=1 1,7",
	"IN/onOuter/commaOuterOnly":              "rows=1 2,8",
	"NOTIN/onOuter/commaOuterOnly":           "rows=2 1,7 | 9,9",
	"EXISTS/onOuter/commaOuterOnly":          "rows=1 2,8",
	"NOTEXISTS/onOuter/commaOuterOnly":       "rows=2 1,7 | 9,9",
	"ANY/onOuter/commaOuterOnly":             "rows=1 2,8",
	"ALL/onOuter/commaOuterOnly":             "rows=2 1,7 | 9,9",
	"SCALARWHERE/onOuter/commaOuterOnly":     "rows=1 2,8",
	"IN/onOuter/havingWithWhere":             "rows=1 1,7",
	"NOTIN/onOuter/havingWithWhere":          "rows=2 2,8 | 9,9",
	"EXISTS/onOuter/havingWithWhere":         "rows=2 1,7 | 9,9",
	"NOTEXISTS/onOuter/havingWithWhere":      "rows=1 2,8",
	"ANY/onOuter/havingWithWhere":            "rows=1 1,7",
	"ALL/onOuter/havingWithWhere":            "rows=2 2,8 | 9,9",
	"IN/onOuter/havingOuterWithWhere":        "rows=0 ",
	"NOTIN/onOuter/havingOuterWithWhere":     "rows=3 1,7 | 2,8 | 9,9",
	"EXISTS/onOuter/havingOuterWithWhere":    "rows=1 2,8",
	"NOTEXISTS/onOuter/havingOuterWithWhere": "rows=2 1,7 | 9,9",
	"ANY/onOuter/havingOuterWithWhere":       "rows=0 ",
	"ALL/onOuter/havingOuterWithWhere":       "rows=3 1,7 | 2,8 | 9,9",
	"IN/onOuter/onRightPad":                  "rows=1 1,7",
	"NOTIN/onOuter/onRightPad":               "rows=0 ",
	"EXISTS/onOuter/onRightPad":              "rows=3 1,7 | 2,8 | 9,9",
	"NOTEXISTS/onOuter/onRightPad":           "rows=0 ",
	"ANY/onOuter/onRightPad":                 "rows=1 1,7",
	"ALL/onOuter/onRightPad":                 "rows=0 ",
	"SCALARWHERE/onOuter/onRightPad":         "rows=1 1,7",
	"IN/onOuter/selectOuterJoin":             "rows=0 ",
	"NOTIN/onOuter/selectOuterJoin":          "rows=3 1,7 | 2,8 | 9,9",
	"EXISTS/onOuter/selectOuterJoin":         "rows=3 1,7 | 2,8 | 9,9",
	"NOTEXISTS/onOuter/selectOuterJoin":      "rows=0 ",
	"ANY/onOuter/selectOuterJoin":            "rows=0 ",
	"ALL/onOuter/selectOuterJoin":            "rows=3 1,7 | 2,8 | 9,9",
	"SCALARWHERE/onOuter/selectOuterJoin":    "ERR ERROR: aggregate functions are not allowed in WHERE (SQLSTATE 42803)",
	"IN/onOuter/nullInner":                   "rows=1 1,7",
	"NOTIN/onOuter/nullInner":                "rows=0 ",
	"EXISTS/onOuter/nullInner":               "rows=3 1,7 | 2,8 | 9,9",
	"NOTEXISTS/onOuter/nullInner":            "rows=0 ",
	"ANY/onOuter/nullInner":                  "rows=1 1,7",
	"ALL/onOuter/nullInner":                  "rows=0 ",
	"SCALARWHERE/onOuter/nullInner":          "rows=1 1,7",
	"IN/onOuter/nullInnerCorr":               "rows=1 1,7",
	"NOTIN/onOuter/nullInnerCorr":            "rows=1 9,9",
	"EXISTS/onOuter/nullInnerCorr":           "rows=2 1,7 | 2,8",
	"NOTEXISTS/onOuter/nullInnerCorr":        "rows=1 9,9",
	"ANY/onOuter/nullInnerCorr":              "rows=1 1,7",
	"ALL/onOuter/nullInnerCorr":              "rows=1 9,9",
	"SCALARWHERE/onOuter/nullInnerCorr":      "rows=1 1,7",
	"IN/onOuter/nullInnerOuter":              "rows=0 ",
	"NOTIN/onOuter/nullInnerOuter":           "rows=2 1,7 | 9,9",
	"EXISTS/onOuter/nullInnerOuter":          "rows=1 2,8",
	"NOTEXISTS/onOuter/nullInnerOuter":       "rows=2 1,7 | 9,9",
	"ANY/onOuter/nullInnerOuter":             "rows=0 ",
	"ALL/onOuter/nullInnerOuter":             "rows=2 1,7 | 9,9",
	"SCALARWHERE/onOuter/nullInnerOuter":     "rows=0 ",
	"SCALARSELECT/onOuter/whereEq":           "rows=3 1,7,1 | 2,8,2 | 9,9,NULL",
	"SCALARSELECT/onOuter/whereNe":           "rows=3 1,7,2 | 2,8,2 | 9,9,5",
	"SCALARSELECT/onOuter/whereFn":           "rows=3 1,7,1 | 2,8,2 | 9,9,NULL",
	"SCALARSELECT/onOuter/whereCast":         "rows=3 1,7,1 | 2,8,2 | 9,9,NULL",
	"SCALARSELECT/onOuter/whereIDF":          "rows=3 1,7,5 | 2,8,5 | 9,9,5",
	"SCALARSELECT/onOuter/whereOuterOnly":    "rows=3 1,7,NULL | 2,8,5 | 9,9,NULL",
	"SCALARSELECT/onOuter/whereOuterEq":      "rows=3 1,7,5 | 2,8,5 | 9,9,NULL",
	"SCALARSELECT/onOuter/whereOuterNull":    "rows=3 1,7,NULL | 2,8,NULL | 9,9,NULL",
	"SCALARSELECT/onOuter/whereOuterFn":      "rows=3 1,7,NULL | 2,8,5 | 9,9,NULL",
	"SCALARSELECT/onOuter/whereBoth":         "rows=3 1,7,NULL | 2,8,2 | 9,9,NULL",
	"SCALARSELECT/onOuter/whereEmpty":        "rows=3 1,7,NULL | 2,8,NULL | 9,9,NULL",
	"SCALARSELECT/onOuter/onEq":              "rows=3 1,7,1 | 2,8,2 | 9,9,NULL",
	"SCALARSELECT/onOuter/onNe":              "rows=3 1,7,1 | 2,8,1 | 9,9,NULL",
	"SCALARSELECT/onOuter/onFn":              "rows=3 1,7,1 | 2,8,2 | 9,9,NULL",
	"SCALARSELECT/onOuter/onIDF":             "rows=3 1,7,2 | 2,8,1 | 9,9,2",
	"SCALARSELECT/onOuter/onOuterOnly":       "rows=3 1,7,NULL | 2,8,2 | 9,9,NULL",
	"SCALARSELECT/onOuter/onOuterNull":       "rows=3 1,7,NULL | 2,8,NULL | 9,9,NULL",
	"SCALARSELECT/onOuter/onSelf":            "rows=3 1,7,5 | 2,8,5 | 9,9,NULL",
	"SCALARSELECT/onOuter/onWhereSplit":      "rows=3 1,7,NULL | 2,8,2 | 9,9,NULL",
	"SCALARSELECT/onOuter/onLeftPad":         "rows=3 1,7,7 | 2,8,7 | 9,9,NULL",
	"SCALARSELECT/onOuter/onLeftOuter":       "rows=3 1,7,NULL | 2,8,8 | 9,9,NULL",
	"SCALARSELECT/onOuter/onLeftEq":          "rows=3 1,7,7 | 2,8,8 | 9,9,NULL",
	"SCALARSELECT/onOuter/selectOuter":       "ERR ERROR: column \"o.id\" must appear in the GROUP BY clause or be used in an aggregate function (SQLSTATE 42803)",
	"SCALARSELECT/onOuter/selectOuterOnly":   "ERR ERROR: column \"o.id\" must appear in the GROUP BY clause or be used in an aggregate function (SQLSTATE 42803)",
	"SCALARSELECT/onOuter/nestedDerived":     "rows=3 1,7,2 | 2,8,2 | 9,9,5",
	"SCALARSELECT/onOuter/nestedSubq":        "rows=3 1,7,2 | 2,8,2 | 9,9,2",
	"SCALARSELECT/onOuter/nestedSubqOuter":   "rows=3 1,7,NULL | 2,8,2 | 9,9,NULL",
	"SCALARSELECT/onOuter/twoOnWhere":        "rows=3 1,7,1 | 2,8,NULL | 9,9,NULL",
	"SCALARSELECT/onOuter/twoWhere":          "rows=3 1,7,1 | 2,8,NULL | 9,9,NULL",
	"SCALARSELECT/onOuter/twoOuterOnly":      "rows=3 1,7,NULL | 2,8,2 | 9,9,NULL",
	"SCALARSELECT/onOuter/whereOuterShadow":  "rows=3 1,7,NULL | 2,8,9 | 9,9,NULL",
	"SCALARSELECT/onOuter/onOuterShadow":     "rows=3 1,7,NULL | 2,8,9 | 9,9,NULL",
	"SCALARSELECT/onOuter/whereShadowCorr":   "rows=3 1,7,NULL | 2,8,2 | 9,9,NULL",
	"SCALARSELECT/onOuter/whereOuterBare":    "rows=3 1,7,NULL | 2,8,5 | 9,9,NULL",
	"SCALARSELECT/onOuter/whereOuterTwoCols": "rows=3 1,7,NULL | 2,8,NULL | 9,9,NULL",
	"SCALARSELECT/onOuter/onBareOuter":       "rows=3 1,7,NULL | 2,8,2 | 9,9,NULL",
	"SCALARSELECT/onOuter/commaCorr":         "rows=3 1,7,1 | 2,8,2 | 9,9,NULL",
	"SCALARSELECT/onOuter/commaNe":           "rows=3 1,7,1 | 2,8,1 | 9,9,NULL",
	"SCALARSELECT/onOuter/commaOuterOnly":    "rows=3 1,7,NULL | 2,8,2 | 9,9,NULL",
	"SCALARSELECT/onOuter/onRightPad":        "rows=3 1,7,1 | 2,8,1 | 9,9,NULL",
	"SCALARSELECT/onOuter/selectOuterJoin":   "ERR ERROR: column \"o.id\" must appear in the GROUP BY clause or be used in an aggregate function (SQLSTATE 42803)",
	"SCALARSELECT/onOuter/nullInner":         "rows=3 1,7,1 | 2,8,1 | 9,9,1",
	"SCALARSELECT/onOuter/nullInnerCorr":     "rows=3 1,7,1 | 2,8,1 | 9,9,NULL",
	"SCALARSELECT/onOuter/nullInnerOuter":    "rows=3 1,7,NULL | 2,8,1 | 9,9,NULL",
	"ISSUE/1232":                             "rows=2 1 | 2",
	"ISSUE/1232-whereCtl":                    "rows=2 1 | 2",
	"ISSUE/1232-existsCtl":                   "rows=2 1 | 2",
	"ISSUE/1232-existsWhereCtl":              "rows=2 1 | 2",
	"ISSUE/1232-plainJoinCtl":                "rows=4 1,1 | 1,2 | 2,3 | 2,4",
	"ISSUE/1104-in":                          "rows=2 1 | 2",
	"ISSUE/1104-notin":                       "rows=1 3",
	"ISSUE/1104-exists":                      "rows=2 1 | 2",
	"ISSUE/1104-notexists":                   "rows=1 3",
	"ISSUE/1104-existsOnly":                  "rows=2 1 | 2",
	"ISSUE/1104-notexistsOnly":               "rows=1 3",
	"ISSUE/1104-scalar":                      "rows=0 ",
}

// dcRefusedCorrelatedDerived: the cells whose body holds a correlated DERIVED
// TABLE. Pre-existing on all five arms at 6b9c7acf.
var dcRefusedCorrelatedDerived = []string{
	"ALL/noJoin/nestedDerived",
	"ALL/onOuter/nestedDerived",
	"ANY/noJoin/nestedDerived",
	"ANY/onOuter/nestedDerived",
	"EXISTS/noJoin/nestedDerived",
	"EXISTS/onOuter/nestedDerived",
	"IN/noJoin/nestedDerived",
	"IN/onOuter/nestedDerived",
	"NOTEXISTS/noJoin/nestedDerived",
	"NOTEXISTS/onOuter/nestedDerived",
	"NOTIN/noJoin/nestedDerived",
	"NOTIN/onOuter/nestedDerived",
	"SCALARSELECT/noJoin/nestedDerived",
	"SCALARSELECT/onOuter/nestedDerived",
	"SCALARWHERE/noJoin/nestedDerived",
	"SCALARWHERE/onOuter/nestedDerived",
}

// dcRefusedBareOuterRef: the cells whose outer reference is written with NO
// qualifier, which the classifier cannot tell from an inner column of the same
// name. Pre-existing on all five arms at 6b9c7acf.
var dcRefusedBareOuterRef = []string{
	"ALL/noJoin/onBareOuter",
	"ALL/noJoin/whereOuterBare",
	"ALL/onOuter/onBareOuter",
	"ALL/onOuter/whereOuterBare",
	"ANY/noJoin/onBareOuter",
	"ANY/noJoin/whereOuterBare",
	"ANY/onOuter/onBareOuter",
	"ANY/onOuter/whereOuterBare",
	"IN/noJoin/onBareOuter",
	"IN/noJoin/whereOuterBare",
	"IN/onOuter/onBareOuter",
	"IN/onOuter/whereOuterBare",
	"NOTIN/noJoin/onBareOuter",
	"NOTIN/noJoin/whereOuterBare",
	"NOTIN/onOuter/onBareOuter",
	"NOTIN/onOuter/whereOuterBare",
}

// dcRefusedOuterAggregate: the cells whose subquery aggregates an argument
// naming only the enclosing query. PostgreSQL raises 42803 for each.
var dcRefusedOuterAggregate = []string{
	"SCALARSELECT/noJoin/selectOuter",
	"SCALARSELECT/noJoin/selectOuterJoin",
	"SCALARSELECT/noJoin/selectOuterOnly",
	"SCALARSELECT/onOuter/selectOuter",
	"SCALARSELECT/onOuter/selectOuterJoin",
	"SCALARSELECT/onOuter/selectOuterOnly",
	"SCALARWHERE/noJoin/selectOuter",
	"SCALARWHERE/noJoin/selectOuterJoin",
	"SCALARWHERE/noJoin/selectOuterOnly",
	"SCALARWHERE/onOuter/selectOuter",
	"SCALARWHERE/onOuter/selectOuterJoin",
	"SCALARWHERE/onOuter/selectOuterOnly",
}

// dcArms stands the five arms up over the shared fixture, exactly as the arc-R1
// table does — the single-process pipeline, the same under a 512 KiB budget,
// and the stage DAG broadcast, shuffled and morselled.
func dcArms(t *testing.T, ctx context.Context) []r1Arm {
	t.Helper()
	return r1Arms(t, ctx)
}

func TestArcDCADecorrelatedBodyKeepsEveryOuterReferenceOnEveryArm(t *testing.T) {
	if testing.Short() {
		t.Skip("-short: five arms over a 776-cell table")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 40*time.Minute)
	t.Cleanup(cancel)
	arms := dcArms(t, ctx)
	derived := r1Set(dcRefusedCorrelatedDerived)
	bare := r1Set(dcRefusedBareOuterRef)
	outerAgg := r1Set(dcRefusedOuterAggregate)

	seen := make(map[string]bool, len(dcPostgresRowSets))
	for _, tc := range dcCases() {
		want, ok := dcPostgresRowSets[tc.name]
		if !ok {
			t.Fatalf("%s: no PostgreSQL row set recorded — the table and the "+
				"measurement have diverged", tc.name)
		}
		seen[tc.name] = true
		t.Run(tc.name, func(t *testing.T) {
			for _, arm := range arms {
				got := arm.run(tc.sql)
				refusal := ""
				switch {
				case derived[tc.name]:
					refusal = dcCorrelatedDerivedRefusal
				case bare[tc.name]:
					refusal = dcBareOuterRefRefusal
				case outerAgg[tc.name]:
					refusal = dcOuterAggregateRefusal
				}
				if refusal != "" {
					// A PIN THAT STARTS AGREEING FAILS. When the boundary
					// closes, the cell is asserted against PostgreSQL — which
					// is already recorded above — and the pin is deleted.
					if !strings.Contains(got, refusal) {
						t.Errorf("%s\n  arm  %s\n  got  %s\n  the pinned refusal (%q) is gone: "+
							"assert PostgreSQL's row set %s and delete this cell's pin",
							tc.sql, arm.name, got, refusal, want)
					}
					continue
				}
				if got != want {
					t.Errorf("%s\n  arm  %s\n  got  %s\n  want %s (PostgreSQL 17.11)",
						tc.sql, arm.name, got, want)
				}
			}
		})
	}
	for name := range dcPostgresRowSets {
		if !seen[name] {
			t.Errorf("%s: a PostgreSQL row set is recorded for a cell the table "+
				"no longer writes", name)
		}
	}
}
