// SPDX-License-Identifier: AGPL-3.0-only

package worker

import (
	"bytes"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"testing"

	"github.com/derekmwright/wadjet/internal/engine/batch"
	"github.com/derekmwright/wadjet/internal/storage/parquet"
	"github.com/derekmwright/wadjet/internal/wshf"
)

// The unconstrained mark rides the `.wshf` column header in-band: bit 7 of
// a DECIMAL column's precision byte (wshf.DecimalUnconstrainedBit, ADR-0010's
// 2026-10-05 amendment, ADR-0024 §10). These gates hold the two halves of that
// claim: a file with no marked column is byte-for-byte the file c67ebf5b's
// encoder wrote, and a marked column's mark comes back on the SAME position —
// never by name: the fixture's two DECIMAL columns are both named "v".

// goldenUnmarkedWSHF is c67ebf5b's encoder's output for markFixtureBatch under
// markFixtureSchema(false, false, false) (generated by running this fixture
// in a c67ebf5b tree).
const goldenUnmarkedWSHF = "57534846010000000500020069640201007611020a010076110a2601007305010077110c26030000000100000007000000000000001800000001000000000000000200000000000000030000000000000001000000070000000000000030000000fa00000000000000000000000000000064000000000000000000000000000000000000000000000000000000000000000100000007000000000000003000000000ba1dd205000000000000000000000000e40b540200000000000000000000000000000000000000000000000000000001000000070000000000000004000000733073310200000004000000040000000100000007000000000000003000000000a89c134602000000000000000000000010a5d4e8000000000000000000000000000000000000000000000000000000"

func markFixtureSchema(m1, m2, m4 bool) []parquet.Column {
	return []parquet.Column{
		{Name: "id", Type: parquet.TypeInt64, Nullable: true},
		{Name: "v", Type: parquet.TypeDecimal, Precision: 10, Scale: 2, Nullable: true, Unconstrained: m1},
		{Name: "v", Type: parquet.TypeDecimal, Precision: 38, Scale: 10, Nullable: true, Unconstrained: m2},
		{Name: "s", Type: parquet.TypeString, Nullable: true},
		{Name: "w", Type: parquet.TypeDecimal, Precision: 38, Scale: 12, Nullable: true, Unconstrained: m4},
	}
}

// markFixtureSchema: a batch with two DECIMAL columns of ONE name ("v") — the
// constrained one first — beside an INT64, a STRING and a third DECIMAL.
func markFixtureBatch(schema []parquet.Column) *batch.RecordBatch {
	b := batch.NewRecordBatch(schema, 3)
	vals := [][3]int64{{1, 250, 25000000000}, {2, 100, 10000000000}, {3, 0, 0}}
	for i, r := range vals {
		b.Columns[0].Nulls.SetValid(i)
		b.Columns[0].Int64Data[i] = r[0]
		if i == 2 {
			continue // row 3: every other column NULL
		}
		b.Columns[1].Nulls.SetValid(i)
		b.Columns[1].DecimalData.Data[i] = batch.Int128{Lo: uint64(r[1])}
		b.Columns[2].Nulls.SetValid(i)
		b.Columns[2].DecimalData.Data[i] = batch.Int128{Lo: uint64(r[2])}
		b.Columns[3].Nulls.SetValid(i)
		b.Columns[3].BytesData.Set(i, []byte(fmt.Sprintf("s%d", i)))
		b.Columns[4].Nulls.SetValid(i)
		b.Columns[4].DecimalData.Data[i] = batch.Int128{Lo: uint64(r[2]) * 100}
	}
	return b
}

func encodeMarkFixture(tb testing.TB, schema []parquet.Column) []byte {
	tb.Helper()
	var buf bytes.Buffer
	sw := newShuffleWriter(&buf, schema)
	if err := sw.writeHeader(); err != nil {
		tb.Fatalf("writeHeader: %v", err)
	}
	b := markFixtureBatch(schema)
	if err := sw.writeChunk(b.Columns, nil, 3); err != nil {
		tb.Fatalf("writeChunk: %v", err)
	}
	data := buf.Bytes()
	binary.LittleEndian.PutUint32(data[4:], sw.numChunks)
	return data
}

func requireMarkFixtureValues(t *testing.T, how string, want, got *batch.RecordBatch) {
	t.Helper()
	if got.Len != want.Len {
		t.Fatalf("%s: %d rows, want %d", how, got.Len, want.Len)
	}
	for ci, c := range want.Schema {
		w, g := want.Columns[ci], got.Columns[ci]
		for i := 0; i < want.Len; i++ {
			if w.Nulls.IsNull(i) != g.Nulls.IsNull(i) {
				t.Fatalf("%s: column %d row %d null mismatch", how, ci, i)
			}
			if w.Nulls.IsNull(i) {
				continue
			}
			var same bool
			switch c.Type {
			case parquet.TypeInt64:
				same = w.Int64Data[i] == g.Int64Data[i]
			case parquet.TypeString:
				same = bytes.Equal(w.BytesData.Value(i), g.BytesData.Value(i))
			case parquet.TypeDecimal:
				same = w.DecimalData.Data[i] == g.DecimalData.Data[i]
			}
			if !same {
				t.Fatalf("%s: column %d row %d value mismatch", how, ci, i)
			}
		}
	}
}

func marksOf(schema []parquet.Column) []bool {
	out := make([]bool, len(schema))
	for i, c := range schema {
		out[i] = c.Unconstrained
	}
	return out
}

// decodeEveryWay decodes data through every WSHF reader: the one decoder
// (DecodeBatches, NewChunkReader) and the worker's streaming reader.
func decodeEveryWay(t *testing.T, data []byte) map[string][]*batch.RecordBatch {
	t.Helper()
	out := map[string][]*batch.RecordBatch{}
	bs, err := wshf.DecodeBatches(data)
	if err != nil {
		t.Fatalf("DecodeBatches: %v", err)
	}
	out["DecodeBatches"] = bs
	cr, err := wshf.NewChunkReader(data)
	if err != nil {
		t.Fatalf("NewChunkReader: %v", err)
	}
	out["ChunkReader"] = drain(t, cr.Next)
	sr := openStreaming(t, data)
	defer sr.Close()
	out["streaming"] = drain(t, sr.Next)
	out["streaming-WSHC"] = func() []*batch.RecordBatch {
		c := CompressShuffleData(data)
		if !bytes.HasPrefix(c, compressedMagic[:]) {
			return out["streaming"]
		}
		r := openStreaming(t, c)
		defer r.Close()
		return drain(t, r.Next)
	}()
	return out
}

func TestWSHFUnmarkedColumnsEncodeAsBase(t *testing.T) {
	got := encodeMarkFixture(t, markFixtureSchema(false, false, false))
	if h := hex.EncodeToString(got); h != goldenUnmarkedWSHF {
		t.Fatalf("an unmarked batch no longer encodes as c67ebf5b encoded it:\n got  %s\n want %s", h, goldenUnmarkedWSHF)
	}
	for how, bs := range decodeEveryWay(t, got) {
		for _, b := range bs {
			if m := marksOf(b.Schema); fmt.Sprint(m) != fmt.Sprint([]bool{false, false, false, false, false}) {
				t.Errorf("%s: an unmarked file decodes with marks %v", how, m)
			}
		}
	}
}

func TestWSHFMarkRoundTripsByPosition(t *testing.T) {
	base, err := hex.DecodeString(goldenUnmarkedWSHF)
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range []struct {
		name       string
		m1, m2, m4 bool
	}{
		{"second v marked", false, true, false},
		{"first v marked", true, false, false},
		{"mixed: second v and w marked", false, true, true},
		{"every decimal marked", true, true, true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			schema := markFixtureSchema(tc.m1, tc.m2, tc.m4)
			got := encodeMarkFixture(t, schema)
			// The marked file differs from the unmarked one in the marked
			// columns' precision bytes alone, by the bit.
			if len(got) != len(base) {
				t.Fatalf("a mark changed the file's length: %d vs %d", len(got), len(base))
			}
			var diffs []int
			for i := range got {
				if got[i] != base[i] {
					if got[i] != base[i]|wshf.DecimalUnconstrainedBit {
						t.Fatalf("byte %d is %#x, want the unmarked %#x with the mark bit", i, got[i], base[i])
					}
					diffs = append(diffs, i)
				}
			}
			want := 0
			for _, m := range []bool{tc.m1, tc.m2, tc.m4} {
				if m {
					want++
				}
			}
			if len(diffs) != want {
				t.Fatalf("%d bytes carry the mark, want %d (%v)", len(diffs), want, diffs)
			}
			wantMarks := fmt.Sprint(marksOf(schema))
			ref := markFixtureBatch(schema)
			for how, bs := range decodeEveryWay(t, got) {
				if len(bs) != 1 {
					t.Fatalf("%s: %d batches, want 1", how, len(bs))
				}
				b := bs[0]
				if m := fmt.Sprint(marksOf(b.Schema)); m != wantMarks {
					t.Errorf("%s: marks %s, want %s (by position)", how, m, wantMarks)
				}
				for ci, c := range schema {
					g := b.Schema[ci]
					if g.Name != c.Name || g.Type != c.Type || g.Precision != c.Precision || g.Scale != c.Scale {
						t.Errorf("%s: column %d decodes as %+v, want %+v", how, ci, g, c)
					}
				}
				requireMarkFixtureValues(t, how, ref, b)
			}
		})
	}
}

func TestWSHFPrecisionByteRefusesAPrecisionTheBitWouldCover(t *testing.T) {
	for _, p := range []int{1, 38, 127} {
		if b, err := wshf.DecimalPrecisionByte(p, false); err != nil || int(b) != p {
			t.Errorf("precision %d: byte %#x, %v", p, b, err)
		}
	}
	if _, err := wshf.DecimalPrecisionByte(128, false); err == nil {
		t.Errorf("precision 128 was written into the mark bit")
	}
	schema := []parquet.Column{{Name: "v", Type: parquet.TypeDecimal, Precision: 200, Scale: 2}}
	var buf bytes.Buffer
	if err := newShuffleWriter(&buf, schema).writeHeader(); err == nil {
		t.Errorf("writeHeader accepted DECIMAL precision 200")
	}
	_ = binary.LittleEndian
}
