// SPDX-License-Identifier: MIT

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// moduleRoot is where the checks run: two directories up from this package.
const moduleRoot = "../.."

func repoPackages(t *testing.T) []pkg {
	t.Helper()
	pkgs, err := loadPackages(moduleRoot)
	if err != nil {
		t.Fatalf("listing the module's packages: %v", err)
	}
	if len(pkgs) < 50 {
		t.Fatalf("go list reported %d packages; the scan is broken, not the code", len(pkgs))
	}
	return pkgs
}

// TestNoMITPackageReachesAGPLCode is the boundary itself.
//
// The MIT artifacts — the `wadjet` library and the `wadjet` binary — are
// distributable under the MIT terms only while nothing they link is AGPL.
// That is a transitive property of the import graph, so it is asserted
// rather than reviewed: an import added three packages down fails here,
// naming the path.
func TestNoMITPackageReachesAGPLCode(t *testing.T) {
	for _, v := range CheckImportBoundary(repoPackages(t)) {
		t.Errorf("%s", v)
	}
}

// TestEveryTestCrossingIsDeclared: a test binary may link both halves — it is
// never distributed — but each MIT directory whose tests do so is named in
// regions.go with the reason, and a declaration that has stopped being true
// fails too.
func TestEveryTestCrossingIsDeclared(t *testing.T) {
	for _, v := range CheckTestCrossings(repoPackages(t)) {
		t.Errorf("%s", v)
	}
}

// TestEveryGoFileCarriesItsRegionsSPDXHeader: the license a file is under is
// answerable at the point of reading it, and a file that moves between
// regions fails until its header moves with it.
func TestEveryGoFileCarriesItsRegionsSPDXHeader(t *testing.T) {
	vs, checked, err := CheckSPDX(moduleRoot)
	if err != nil {
		t.Fatalf("walking the tree: %v", err)
	}
	if checked < 2000 {
		t.Fatalf("only %d .go files were checked; the walk is broken, not the code", checked)
	}
	for _, v := range vs {
		t.Errorf("%s", v)
	}
}

// TestEveryRegionDirectoryCarriesItsOwnLicenseText: pkg.go.dev and most
// license scanners resolve a package's license from the nearest LICENSE at or
// above it. With an MIT file at the root, an AGPL directory without its own
// copy is published as MIT — the wrong license, not a missing one.
func TestEveryRegionDirectoryCarriesItsOwnLicenseText(t *testing.T) {
	for _, v := range CheckLicenseFiles(moduleRoot, repoPackages(t)) {
		t.Errorf("%s", v)
	}
}

// TestLicensingDocNamesTheDeclaredRegions holds the document and the code
// together in both directions: a region the document does not list, and a
// directory the document lists that the code does not declare.
func TestLicensingDocNamesTheDeclaredRegions(t *testing.T) {
	for _, v := range CheckLicensingDoc(moduleRoot, repoPackages(t)) {
		t.Errorf("%s", v)
	}
}

// TestAnAGPLImportInAnMITPackageIsCaught is the boundary gate's own gate.
//
// A checker that passes because it looks at nothing passes exactly as
// quietly as a clean tree, so the violation is constructed and the gate is
// required to find it — and to name the path it took, which is the part that
// makes a failure actionable.
func TestAnAGPLImportInAnMITPackageIsCaught(t *testing.T) {
	const mod = modulePath
	pkgs := []pkg{
		{importPath: mod + "/wadjet", dir: "wadjet", imports: []string{mod + "/internal/planner/physical"}},
		{importPath: mod + "/internal/planner/physical", dir: "internal/planner/physical",
			imports: []string{mod + "/internal/coordinator/dagplan"}},
		{importPath: mod + "/internal/coordinator/dagplan", dir: "internal/coordinator/dagplan"},
	}
	vs := CheckImportBoundary(pkgs)
	if len(vs) == 0 {
		t.Fatal("an MIT package importing an AGPL package was not reported")
	}
	var found bool
	for _, v := range vs {
		if v.Where == "wadjet" && strings.Contains(v.What, "internal/planner/physical -> internal/coordinator/dagplan") {
			found = true
		}
	}
	if !found {
		t.Fatalf("the violation does not name the import path that produced it: %v", vs)
	}
}

// TestAMissingOrWrongHeaderIsCaught is the SPDX gate's own gate: a file with
// no header, and a file whose header names the other region.
func TestAMissingOrWrongHeaderIsCaught(t *testing.T) {
	root := t.TempDir()
	mustWrite := func(rel, body string) {
		t.Helper()
		path := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	mustWrite("wadjet/ok.go", "// SPDX-License-Identifier: MIT\n\npackage wadjet\n")
	mustWrite("wadjet/bare.go", "package wadjet\n")
	mustWrite("internal/coordinator/wrong.go", "// SPDX-License-Identifier: MIT\n\npackage coordinator\n")
	mustWrite("gen/dataplane/gen.go", "// Code generated by protoc. DO NOT EDIT.\n\npackage dataplane\n")

	vs, checked, err := CheckSPDX(root)
	if err != nil {
		t.Fatal(err)
	}
	if checked != 3 {
		t.Errorf("checked %d files, want 3 (the generated one is skipped)", checked)
	}
	got := map[string]string{}
	for _, v := range vs {
		got[v.Where] = v.What
	}
	if _, ok := got["wadjet/bare.go"]; !ok {
		t.Error("a file with no SPDX header was not reported")
	}
	if what, ok := got["internal/coordinator/wrong.go"]; !ok {
		t.Error("a file whose header names the other region was not reported")
	} else if !strings.Contains(what, "AGPL-3.0-only") {
		t.Errorf("the report does not say which header the file should carry: %q", what)
	}
	if _, ok := got["wadjet/ok.go"]; ok {
		t.Error("a correct header was reported as a violation")
	}
	if _, ok := got["gen/dataplane/gen.go"]; ok {
		t.Error("a generated file was required to carry a header a regeneration would drop")
	}
}

// TestTheLongestDeclaredPrefixWins: internal/server is AGPL and its pgwire
// and mcp subdirectories are not, which is only true if the more specific
// declaration beats the more general one.
func TestTheLongestDeclaredPrefixWins(t *testing.T) {
	cases := map[string]string{
		"internal/server":               agpl,
		"internal/server/grpcstuff":     agpl,
		"internal/server/pgwire":        mit,
		"internal/server/pgwire/subpkg": mit,
		"internal/server/mcp":           mit,
		"internal/coordinator":          agpl,
		"internal/coordinator/dagplan":  agpl,
		"internal/planner/physical":     mit,
		"wadjet":                        mit,
		"cmd/wadjet":                    mit,
		"cmd/wadjetd":                   agpl,
		"internal/serverless_lookalike": mit,
		"internal/coordinatorish":       mit,
	}
	for dir, want := range cases {
		if got := licenseOf(dir); got != want {
			t.Errorf("licenseOf(%q) = %s, want %s", dir, got, want)
		}
	}
}
