package typematrix

import (
	"testing"

	"github.com/derekmwright/wadjet/internal/storage/parquet"
)

// TestColumnsCoversAllTypes pins Columns() to the engine's full type system
// (CLAUDE.md's Type System list, 22 types). Corpus() is GENERATED by ranging
// over Columns() (its own doc comment: "a 23rd type is covered by adding one
// row to Columns() instead of by remembering to write ten queries") — so a
// type silently missing from this table is a type with NO differential
// coverage from any of the five gates that consume this package, exactly the
// gap that let #391 hide behind 19 of the previous 22 types having none at
// all.
func TestColumnsCoversAllTypes(t *testing.T) {
	want := []parquet.TypeID{
		parquet.TypeBool, parquet.TypeInt32, parquet.TypeInt64, parquet.TypeFloat32,
		parquet.TypeFloat64, parquet.TypeString, parquet.TypeBytes, parquet.TypeTimestamp,
		parquet.TypeIPv4, parquet.TypeIPv6, parquet.TypeCIDR, parquet.TypeMAC,
		parquet.TypePort, parquet.TypeProtocol, parquet.TypeDuration, parquet.TypeUUID,
		parquet.TypeDate, parquet.TypeDecimal, parquet.TypeArray, parquet.TypeRow,
		parquet.TypeMap, parquet.TypeVector,
	}

	cols := Columns()
	if len(cols) != len(want) {
		t.Fatalf("Columns() has %d entries, want %d (one per type) — a type was added or dropped "+
			"without updating this test's want list", len(cols), len(want))
	}

	seenTypes := make(map[parquet.TypeID]string, len(cols))
	seenNames := make(map[string]bool, len(cols))
	for _, c := range cols {
		if c.Name == "" {
			t.Errorf("type %v has an empty column name", c.Type)
		}
		if seenNames[c.Name] {
			t.Errorf("column name %q used more than once in Columns()", c.Name)
		}
		seenNames[c.Name] = true

		if prior, ok := seenTypes[c.Type]; ok {
			t.Errorf("type %v appears twice in Columns() (%s and %s)", c.Type, prior, c.Name)
		}
		seenTypes[c.Type] = c.Name
	}
	for _, typ := range want {
		if _, ok := seenTypes[typ]; !ok {
			t.Errorf("Columns() has no entry for type %v — the type-matrix gates cannot see it", typ)
		}
	}
}

// TestColumnsAndCorpusAreDeterministic pins the ordering contract Corpus's
// own doc comment claims: "Ordering is deterministic (Columns() order, then
// template order) so a failing entry name is stable across runs and across
// processes." Every gate that consumes this package keys its pins by entry
// NAME, not index, so nondeterministic ordering would not flip a gate's
// pass/fail — but it would make a failure's reported name unstable across
// runs, silently breaking every pin's `ratchet.finish` "matches no corpus
// entry" check on whichever run reordered.
func TestColumnsAndCorpusAreDeterministic(t *testing.T) {
	c1, c2 := Columns(), Columns()
	if len(c1) != len(c2) {
		t.Fatalf("Columns() length varies across calls: %d vs %d", len(c1), len(c2))
	}
	for i := range c1 {
		if c1[i] != c2[i] {
			t.Errorf("Columns()[%d] differs across calls:\n  first:  %+v\n  second: %+v", i, c1[i], c2[i])
		}
	}

	q1, q2 := Corpus(), Corpus()
	if len(q1) != len(q2) {
		t.Fatalf("Corpus() length varies across calls: %d vs %d", len(q1), len(q2))
	}
	for i := range q1 {
		if q1[i] != q2[i] {
			t.Errorf("Corpus()[%d] differs across calls:\n  first:  %+v\n  second: %+v", i, q1[i], q2[i])
		}
	}
}

// TestCorpusNamesAreUniqueAndNonEmpty pins the corpus's own keying contract:
// every gate looks a divergence's pin up by Query.Name (tmPinFor / tmdPinFor),
// so a blank or duplicated name would let one pin silently exempt more than
// the one entry it names, or let an entry never be reachable by name at all.
func TestCorpusNamesAreUniqueAndNonEmpty(t *testing.T) {
	seen := make(map[string]bool)
	for _, q := range Corpus() {
		if q.Name == "" {
			t.Errorf("corpus entry has an empty name (SQL: %s)", q.SQL)
			continue
		}
		if seen[q.Name] {
			t.Errorf("corpus entry name %q used more than once", q.Name)
		}
		seen[q.Name] = true
		if q.SQL == "" {
			t.Errorf("corpus entry %q has no SQL", q.Name)
		}
	}
}
